### ISSUE TITLE
Python extra verbose in 80x IBs

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#13201]
[dlange@cmsdev01 src]$ python
Python 2.7.11 (default, Jan 21 2016, 17:19:47) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Name collision 'vt52' between
    vt52|dec vt52
and vt52|dec vt52
...now  dec vt52
Cannot remove alias 'dec vt52'
Name collision 'vt100-nav' between
    vt100-nav|vt100 without advanced video option
and vt100-nav|vt100 without advanced video option
...now  vt100 without advanced video option
Cannot remove alias 'vt100 without advanced video option'
Name collision 'vt102' between
    vt102|dec vt102
and vt102|dec vt102
...now  dec vt102
Cannot remove alias 'dec vt102'
Name collision 'vt100' between
    vt100|vt100-am|dec vt100 (w/advanced video)
and vt100|vt100-am|dec vt100 (w/advanced video)
...now  vt100-am|dec vt100 (w/advanced video)
...now  dec vt100 (w/advanced video)
Cannot remove alias 'dec vt100 (w/advanced video)'
Name collision 'vt220' between
    vt220|vt200|dec vt220
and vt220|vt200|dec vt220
...now  vt200|dec vt220
...now  dec vt220
Cannot remove alias 'dec vt220'
Name collision 'ansi' between
    ansi|ansi/pc-term compatible with color
and ansi|ansi/pc-term compatible with color
...now  ansi/pc-term compatible with color
Cannot remove alias 'ansi/pc-term compatible with color'
Name collision 'linux' between
    linux|linux console
and linux|linux console
...now  linux console
Cannot remove alias 'linux console'
Name collision 'dumb' between
    dumb|80-column dumb tty
and dumb|80-column dumb tty
...now  80-column dumb tty
Cannot remove alias '80-column dumb tty'

**Comment by davidlange6** [comment]
assign core

**Comment by bendavid** [comment]
I have also seen this running madgraph btw (which runs python underneath anyway), though it seems to have no ill effect beyond the extra output.

**Comment by davidlt** [comment]
Went to cmsdev01 and executed python, didn't get this output. Looks like some internal failures/assert/unknown state maybe related to term cap database.

**Comment by cbernet** [comment]
Hi David, all, I got here by googling this printout :-)  I also have the problem.

**Comment by davidlt** [comment]
It's due to terminfo/termcap not matching up on your system and what's in CMSSW.

**Comment by davidlt** [comment]
I might fix it with arrival of GCC 6.1.0, but I am still debating with myself.

**Comment by bendavid** [comment]
Well this occurs on lxplus, which I think can safely be considered a "reference" system for running CMSSW.

**Comment by davidlt** [comment]
The build is never API/ABI stable and is never fully relocatable. We never test if packages we build pass tests (e.g. we don't even know if compiler, i.e. GCC, generates code in expected way). Doing `dnf/yum` `upgrade/update` can break it. Which recently happened on Fedora 22 builds where NSS was updated and finally it wasn't compatible with what we shipped as part of `bootstrap-bundle` package. You couldn't even bootstrap anymore because RPM wasn't working due to broken NSS setup.

Things are fragile, quite stable of ancient beasts as RHEL/CentOS as there are strict rules on what can/cannot be updated/modified meaning that API/ABI usually will be stable, but not behaviour (.e.g, sometimes getting 5 times slower std::log is expected after upgrade/update).

In this case it's relatively easy to fix. I just remove `ncurses` package from our distribution and that is fine because we always requested from `ncurses` to be installed on the system. So, we install `ncurses-devel` instead on our build machines. But in order to do that, I have rebuild the bootstrap itself. Which is easiest with GCC 6.1.0, because it's soon to arrive. But yes, it can also be done for GCC 5.3.0.

I used to play with `ncurses` termcap and terminfo, but I never managed to get all externals happy with modifications. Removing `ncurses` from distribution is the best for many reasons.

**Comment by rijuvenator** [comment]
Hi,

Was this problem ever solved? It still seems to be happening on lxplus, using CMSSW_8_1_0_pre8

**Comment by bartosik-hep** [comment]
@davidlt, @davidlange6  I have the same issue. There is no 8X release at the moment running on GCC greater than 5.3.0. Is there any way to suppress the message or to solve the issue in a 8X release?

**Comment by rijuvenator** [comment]
If you don't care about errors, simply do

```
python script.py 2>/dev/null
```

If you care about errors, I have a workaround.

Put this in your bash profile:

`exec 3>&1`

Then, anytime you run a Python script with, for example,

`import ROOT as R`

replace it with this:

```
import sys, os
import ROOT as R
fd3 = os.fdopen(3, 'w')
sys.stderr = fd3
```

Then you can run all your Python scripts with

```
python script.py 2>/dev/null
```

This will redirect the ROOT error messages to `/dev/null`, then set `stderr` to point to file descriptor 3, so that you still see all Python error messages (because they will get redirected to the terminal), but you won't see the ROOT error messages.

**Comment by MengqingWu** [comment]
@davidlange6  I have the same issue with 8_0_11, but can not remember this existed from the beginning or not. It shows today..

**Comment by binka04** [comment]
Hii, davidlange6,
Has the problem been fixed ? , I am using CMSSW_8_1_0_pre9, slc6_amd64_gcc530. I am seeing such kind of error message while running a python script in cmslpc account.
The python script import the following.
from os import environ
from ROOT import *
from math import sqrt
gROOT.ProcessLine(".L ~/tdrstyle.C")
gROOT.ProcessLine("setTDRStyle()")
from optparse import OptionParser

The link to python script is here:
 https://github.com/awhitbeck/RA2bZinvEst/blob/RA2b_V12_v0.1.2/src/formatIntegrationInputs.py 

 and I am attaching output message in a pdf file here. It will be great help to me, if you can suggest me what is the reason of bug. 


[Thanks.]
[ouput.pdf](https://github.com/cms-sw/cmssw/files/2521784/ouput.pdf)
