### ISSUE TITLE
Loop time not recorded if exception happens and end Run transition

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#14259]
The 'Total loop' times (wallclock and CPU) are recorded from the 'postGlobalEndRunSignal' in the Timing module. If an exception occurs, that signal does not go off and an uninitialized value is used when calculating the time.

https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/FWCore/Services/plugins/Timing.cc#L142

**Comment by Dr15Jones** [comment]
assign core

**Comment by wddgit** [comment]
After investigating and testing I came to the conclusion the problem only happens after an exception during beginRun. I submitted a PR to initialize the variables and deal with that situation in a reasonable manner. The loop time and things derived from it will be printed with a value of zero instead of something based on an uninitialized double. See #14309

**Comment by Dr15Jones** [comment]
+1
