### ISSUE TITLE
Utilities/RFIOAdaptor fails to compile with gcc700 because castor missing

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#17375]
The builds of Utilities/RFIOAdaptor using gcc700 are failing becuase of a missing header `#include "shift/stager_api.h"`. This header comes from the `castor` package. However, the build of gcc700 does not include the castor header file directory when building the package.

**Comment by Dr15Jones** [comment]
@davidlt

**Comment by Dr15Jones** [comment]
assign core

**Comment by davidlt** [comment]
That's because I removed CASTOR. There is just too much clean up for C++17 needed in it (probably way more than in CMSSW + anything else). I started looking around the status of CASTOR. I found that RFIO protocol is dead, it's official on their website and it's even marked as red in some ATLAS Twiki pages. It's not to be used. They already have disabled write ability via RFIO. You can still read, but that will also probably be disabled. The official requirement is to use root protocol for accessing data from CASTOR thus I am not fully sure what is the real need for it.

For now it's disabled and it's the last thing on the list to look at.

**Comment by davidlt** [comment]
@davidlange6 the need for RFIO should be discussed somewhere (ORP, Core Software?):
- RFIO deprecated: http://castor.web.cern.ch/
- Ticket for disabling RFIO write ability: https://cern.service-now.com/service-portal/view-outage.do?n=OTG0033733
Contents:
```
Description:
Starting from January 2017, the RFIO access protocol will be limited to only read operations on all CASTOR instances at CERN. Any RFIO write operation to CASTOR will be blocked.

This change is a first step towards fully decommissioning RFIO, as announced at the October's ITUM (IT Technical User Meeting).

Users still using RFIO will be contacted in order to help them migrating to the xroot protocol.

Update: the change is effective as of Monday, January 16th.
```
CASTOR wants people to use `xroot` protocol, which is great from my point of view (means we can remove some stuff).

**Comment by davidlange6** [comment]
I thought the cms castor data at cern was read only since years. Anyway, it's not really for the software groups I think. If we want to find out other users of rfio out there then it's a question for facilities ops.

Cheers,
David


On 3 Feb 2017, at 17:57, davidlt <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> the need for RFIO should be discussed somewhere (ORP, Core Software?):

  *   RFIO deprecated: http://castor.web.cern.ch/
  *   Ticket for disabling RFIO write ability: https://cern.service-now.com/service-portal/view-outage.do?n=OTG0033733
Contents:

Description:
Starting from January 2017, the RFIO access protocol will be limited to only read operations on all CASTOR instances at CERN. Any RFIO write operation to CASTOR will be blocked.

This change is a first step towards fully decommissioning RFIO, as announced at the October's ITUM (IT Technical User Meeting).

Users still using RFIO will be contacted in order to help them migrating to the xroot protocol.

Update: the change is effective as of Monday, January 16th.


CASTOR wants people to use xroot protocol, which is great from my point of view (means we can remove some stuff).

**Comment by Dr15Jones** [comment]
@ericvaandering Do you know if any sites are still using RFIO protocol?

**Comment by ericvaandering** [comment]
I don't know. @hufnagel may know or Stefan Lammel.

**Comment by hufnagel** [comment]
Easy to check, just grep SITECONF/SITE/PhEDEx/storage.xml for functional rfio:// mappings.

I see rules for T0_CH_CERN and T1_CH_CERN which should be removed. I also see rules for T1_UK_RAL that seem to be functional (makes sense since RAL is using castor disk) and T3_IR_IPM (not sure if that is valid).

Either way, if you we want to abandon the rfio protocol it seems we need to follow up on this. I can look at the CERN rules, Stephan would have to follow up with the other two sites if they really need rfio. In principle they could also switch to xrootd.

**Comment by davidlt** [comment]
That's the thing. RFIO is being decommissioned and xrootd interface to CASTOR is the official recommendation. Just wanted to re-iterate why we are looking into this.

**Comment by hufnagel** [comment]
That's only for CERN though, RAL might have their own requirements. We need to have Site Support check up with them. If for whatever reason they say they can't switch to xrootd and want to stay with rfio...

**Comment by hufnagel** [comment]
CERN doesn't set policy on how to use castor for other sites deploying it.

**Comment by davidlt** [comment]
Make sense, I didn't think about other sites here.

**Comment by davidlt** [comment]
ping

Do we have any updates on this topic?

**Comment by davidlange6** [comment]
did someone get this question to the site people?

**Comment by davidlange6** [comment]
so yes is my answer - do we need support from the product developers (or do I read correctly that the product in question is deprecated
(http://castor.web.cern.ch) - in which case a discussion with cms and ral is needed

**Comment by davidlange6** [comment]
and @davidlt - did you try 2.1.16?

**Comment by davidlt** [comment]
CASTOR is alive, but RFIO is dead for a long time. It's deprecated and CERN (at least) started limiting it's capabilities (no more writes). If someone uses rfio they should change that root protocol.

ATLAS has with with some red words:

> The rfio protocol (nsls, rfdir, rfcp, ...) is **highly deprecated** when accessing data stored at CERN and it will be dropped in a near future (except for special users and activities, such as Tier0, Tier3 and CAF).

**Comment by davidlt** [comment]
No, I have not. I did look into ChangeLogs and don't expect much.

**Comment by davidlange6** [comment]
thats "at cern"...
let me bounce this thread to site folks

**Comment by davidlt** [comment]
CHEP 2013, "Streamlining CASTOR to manage the LHC data torrent"
http://inspirehep.net/record/1302106/files/jpconf14_513_042031.pdf?version=1
```
A further simplification of the CASTOR system is foreseen. Among the currently supported
protocols, RFIO, Root, GridFTP, and XRoot, the latter will take the role of the main native
protocol instead of RFIO, while Root is about to be deprecated. GridFTP is gradually taken
over by XRoot for the WAN transfers. The adoption of XRoot as the main file transfer protocol
opens the possibility to exploit its upcoming features, including for instance the support of
XRoot federations or the support of the HTTP protocol. On the other side, only few disk pools
for each experiment would serve as staging areas for the Tier-0 work flow, thus allowing for
further streamlining operational procedures.
```

**Comment by gastonlp** [comment]
Dear All, 

I've checked the storage.xml files for all the sites in SITECONF and none of them appear to have rules for accessing castor over rfio. There is however, a small set of sites (7 T2 / ~15 T3) that expose the rfio protocol. These sites use DPM.

Regards, 
Gaston Lyons
Site Support Team.

**Comment by davidlange6** [comment]
so lets drop support unless any of those sites speak up?

**Comment by hufnagel** [comment]
RAL has rules for accessing castor over rfio in storage.xml.

        
        <lfn-to-pfn protocol="rfio" path-match="/+store/unmerged/(.*)" result="rfio:///?svcClass=cmsDisk&amp;path=/castor/ads.rl.ac.uk/prod/cms/store/unmerged/$1"/>
        <lfn-to-pfn protocol="rfio" path-match="/+store/backfill/test02/(.*)" result="rfio:///?svcClass=cmsDisk&amp;path=/castor/ads.rl.ac.uk/prod/cms/disk/store/backfill/test02/$1"/>
        <lfn-to-pfn protocol="rfio" chain="direct2" path-match="(.*)" result="rfio:///?path=$1"/>
        <pfn-to-lfn protocol="rfio" chain="direct2" path-match=".*?path=(.*)" result="$1"/>
        

The rules don't seem to be active in site-local-conf, but they are there.

Before we drop this, IMO we need explicit confirmation from RAL that they don't need jobs to be able to read directly from castor anymore over rfio (and if they confirm that I would suggest Site Supports asks them to cleanup their storage.xml file).

**Comment by smuzaffar** [comment]
RAL does not use rfio any more. They have cleaned up storage.xml https://gitlab.cern.ch/SITECONF/T1_UK_RAL/blob/master/PhEDEx/storage.xml
I am cleaning up cmssw now to drop rfio plugin

**Comment by Dr15Jones** [comment]
+1
