### ISSUE TITLE
cleanup PhysicsTools/CandUtils from duplicates available in CommonTools/CandUtils

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#19306]
most of the package classes in PhysicsTools/CandUtils are present in CommonTools/CandUtils.

**Comment by slava77** [comment]
assign analysis,reconstruction

**Comment by davidlange6** [comment]
i looked at whats involved 

not including self references, CommonTools headers are included 50 times, ones in PhysicsTools 18 times - so seems the thing to do is to get rid of these

AddFourMomenta.h
src/TopQuarkAnalysis/TopPairBSM/src/BoostedTopProducer.cc
src/HeavyFlavorAnalysis/RecoDecay/src/BPHDecayMomentum.cc
src/HeavyFlavorAnalysis/RecoDecay/src/BPHPlusMinusCandidate.cc
src/PhysicsTools/PatAlgos/plugins/PATCompositeCandidateProducer.cc
src/PhysicsTools/PatExamples/plugins/PatJPsiProducer.cc
src/PhysicsTools/Heppy/src/FSRWeightAlgo.cc
src/HLTrigger/JetMET/interface/HLTCATopTagFilter.h
src/HLTrigger/JetMET/interface/HLTCAWZTagFilter.h

Thrust.h
src/TopQuarkAnalysis/TopEventSelection/src/TtFullHadSignalSel.cc
src/GeneratorInterface/PomwigInterface/test/SDDijetsAnalyzer.cc
src/PhysicsTools/CandAlgos/plugins/EventShapeVarsProducer.cc

Booster.h and CenterOfMassBooster.h
rc/PhysicsTools/Heppy/src/FSRWeightAlgo.cc
src/ElectroWeakAnalysis/ZEE/interface/AnalysisErsatz.h
src/ElectroWeakAnalysis/ZEE/interface/AnalysisErsatz.h

EventShapeVariables.h (actually this is not in CommonTools - so its "ok")
src/TopQuarkAnalysis/TopEventSelection/src/TtFullHadSignalSel.cc
src/PhysicsTools/CandAlgos/plugins/EventShapeVarsProducer.h

CandMatcherNew.h (ok, no longer so new)
src/PhysicsTools/HepMCCandAlgos/plugins/MCTruthCompositeMatcherNew.cc

pdgIdUtils.h
src/PhysicsTools/JetMCAlgos/plugins/HadronAndPartonSelector.cc

the only interesting commit since 2009 I see in PhysicsTools/CandUtils is in EventShapeVariables.cc which is only in that package.. 

So its basically a matter of changing PhysicsTools to CommonTools in 18 places (plus maybe some build files..) and then deleting any duplicated class from PhysicsTools..

**Comment by perrotta** [comment]
@davidlange6 please have a look at #22584

In it I migrated all what above but Thrust.h, which was removed from CommonTools in 2009 by https://github.com/cms-sw/cmssw/commit/37a389609502aa52ef38394480843a27d0466f34#diff-b79b8f5cb1bfcdc21796e551b50a70fe

**Comment by perrotta** [comment]
+1
- #22584 fixes it

**Comment by smuzaffar** [comment]
this has been fix via @22584
