### ISSUE TITLE
PFEnergyCalibration with large changes in "e"

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20173]
This issue is to follow up on changes observed in connection to #20067
After a switch to PFCalibration_v7_mc	from PFCalibration_v6_mc,
the workflows from run1 or 2016 (data) processing have a significant increase in low-et photons (typically pt<0.1 GeV). These photons show up as a downstream effect of PFEnergyCalibration::energyEmHad having inputs with h = 0, e small (under or around 1 GeV) and outputs with e of 3 to 5 GeV.

Most inputs will be needed from JME (@spandeyehep), but some information will also be needed on the logic used in the PFAlgo to interpret values returned by energyEmHad that may or may not lead to an extra photon. (@bachtis @cbernet )

Some debugging info from me is available in https://github.com/cms-sw/cmssw/pull/20067#issuecomment-322397352

**Comment by slava77** [comment]
assign reconstruction,alca

**Comment by spandeyehep** [comment]
Dear @slava77 ,
Following up on [1] where switching to PFCalibration_mc_v7 from PFCalibration_mc_v6 created an excess of low-pt photons, we tried to understand what is going on.

Our initial checks were consistent with your debugging report that we did in wf 4.53 (4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT).
This anomaly is because of higher values of fbEndCap (ecal-energy correction factor in EndCap)[2] in PFCalibration_mc_v7 as compared to PFCalibration_mc_v6. To get into more details about how this over-corrected energy is being translated into creation of extra photons and also, how non-zero ecal & zero hcal energy is being calibrated by our PFEnergyCalibration.cc [3] script, we tried to understand implementation of PFAlgo.cc in a bit more details [4].

Upto line # 818, everything seems to be good & all the "good electrons" and "good photons" have been created.

Between lines # 819-# 1348 [5], algorithm mainly looks for tracks:
- which are NOT associated with any HCAL cluster (i.e. associated with only ECAL cluster)
- these tracks are not "locked or removed" because they were not associated with already identified "good electrons"

Now jump to line # 1355 [6]: We have no hcal cluster (i.e. hcal = 0), an ECAL cluster with linked track-momentum.
- Calibrate this ECAL cluster using PFEnrgyCalibration.cc [3] under a charged hadron hypothesis.

Now comes the key line # 1415 [7]:
- If there is an excess ecal cluster energy (after calibration) as compared to track momentum then create a photon.
Line #1457
if ( [neutralEnergy](http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0#1419) > std::max(0.5,[nSigmaECAL_](http://cmslxr.fnal.gov/ident?v=CMSSW_9_0_0&_i=nSigmaECAL_)*[resol](http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0#1456)) ) {
*** create a photon out of the excessive neutral energy ****
}

A few debug statements for one event confirming the above understanding are listed below [8].

One important note is that this parameter [nSigmaECAL_](http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/python/particleFlow_cfi.py?v=CMSSW_9_0_0#0213) = 0, so neutralEnergy corresponding to this category always gets created if it is greater than 0.5,  unless it get protected by some other means in PFEnergyCalibration.cc [9] (as happened in v6 but not in v7). Please see [8].

Assuming that this is some oversight here & the matching with track has to be within some resolution, we updated [nSigmaECAL_](http://cmslxr.fnal.gov/ident?v=CMSSW_9_0_0&_i=nSigmaECAL_) = 1, and reran the same wf for v6 & v7. With this condition, v6 & v7 behave similarly. Please see the attached distribution.

![photons_overlay_all](https://user-images.githubusercontent.com/16074786/29809748-fb9711c6-8cba-11e7-8b66-8c85f9f7bdef.gif)


We are trying to understand a few more details but we thought we should share this information with you now. Hope some more PF experts (@bachtis @cbernet  ) can also look into it. Please do let us know if you have any further suggestions.

Thanks & regards,
Shubham and Seema


[1] https://github.com/cms-sw/cmssw/pull/20067
[2] https://spandey.web.cern.ch/spandey/JetMet/fbEndCap_log.gif
Blue: PFCalibration_mc_v7
Red: PFCalibration_mc_v6
[3] https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc
[4] http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0
[5] http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0#0819
[6] http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0#1355
[7] http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0#1415
[8]  ----------------------------------------------------------------------------------------------
**For v6:**
In PFEnergyCalibration.cc

  eta:1.613328
  Initialzing:
  t:3.523883 ,a:0.405073 ,b:-0.307245
  After protection check:
  t:3.523883 ,a:1.000000 ,b:1.000000
  New estimate of energy
t = thresh+a*e+b*h: 0.000000 + 1.000000 * 1.529639 + 1.000000 * 0.000000 = 1.529639
*Angular correction*****
     In condition:else for ang correction
*BOTTOM******
Raw Energies: tt = 3.523883 ,ee = 1.529639 ,hh = 0.000000
Corrected Energies: t = 3.523883 ,e = 1.529639 ,h = 0.000000
**********

**For v7:**
In PFEnergyCalibration.cc

  eta:1.613328
  Initialzing:
  t:3.523883 ,a:0.405073 ,b:-0.110081
  After protection check:
  t:3.523883 ,a:0.405073 ,b:-0.110081
  New estimate of energy
t = thresh+a*e+b*h: 3.500000 + 0.405073 * 1.529639 + -0.110081 * 0.000000 = 4.119615
*Angular correction*****
     In condition:if ( e > 0. && thresh > 0. ) for ang correction
     etaCorrE: 0.996248 ,etaCorrH: 0.997577
In condition:if ( e > 0. && thresh > 0. ) for final e estimation
before correction:1.529639
After correction: threshE + etaCorrE * a * e = 3.500000+0.996248*0.405073*1.529639 = 4.117290
Corss-check:4.117290
*BOTTOM******
Raw Energies: tt = 3.523883 ,ee = 1.529639 ,hh = 0.000000
Corrected Energies: t = 4.119615 ,e = 4.117290 ,h = 0.000000
xxxxxxxxxxxxxx
hello, e-tt = 0.593407
xxxxxxxxxxxxxx
Neutral Energy = calibEcal - trackMomentum =0.593407, And corresponding trackMomentum = 3.523883
Raw Energies: tt = 3.523883 ,ee = 1.529639 ,hh = 0.000000
Corrected Energies: t = 4.119615 ,e = 4.117290 ,h = 0.000000
##############################

**In PFAlgo.cc :**

calibEcal = 4.117290
trackMomentum = 3.523883
[Neutral Energy](http://cmslxr.fnal.gov/source/RecoParticleFlow/PFProducer/src/PFAlgo.cc?v=CMSSW_9_0_0#1458) = (calibEcal - trackMomentum)/slopeEcal = 0.22 GeV
==>
Creates photon of energy = 0.22 GeV ==> pT ~ 0.08 GeV
#################################
[9] https://github.com/spandeyehep/PFCalibration/blob/anomaly_testing/PFEnergyCalibration.cc#L295

**Comment by slava77** [comment]
@hatakeyamak @bendavid 
I was trying to clean up old open issue.
Would this one be somehow addressed by #25703?

**Comment by hatakeyamak** [comment]
Will look into it...

**Comment by christopheralanwest** [comment]
@hatakeyamak @bendavid Has this issue been resolved?

**Comment by slava77** [comment]
@hatakeyamak @bendavid 

is the problem still present in the more recent (than the 2017 variant) calibration?

**Comment by tvami** [comment]
kindly ping @hatakeyamak 
(or @slava77 if you know more about the status of this)

**Comment by tvami** [comment]
Hi @hatakeyamak have you had the chance to look into this?

**Comment by hatakeyamak** [comment]
Yes, and have some idea what we may want to do, but need more time for making a concrete proposal/suggestion.

**Comment by hatakeyamak** [comment]
@slava77 @spandeyehep @seemasharmafnal all
Obviously this is a very old thread, but finally I looked through it and thought through it. My conclusion is that the code is fine as it is and the changes discussed above due to calibration update is fine.

I would consider that what was happening with v6 is a little more undesired and the behavior is better with v7. In the case of v6, the calibration just slightly went into the regime that `protection` takes place and no calibration was applied. But, under EH hadron calibration assumption, we expect some level of >1 calibration, and this calibration is properly considered when evaluating if the calorimeter energy exceeds the track momentum.
Using the calibrated calo energy under EH-hadron hypothesis to determine photon energy is not quite right, so the EH-hadron calibration is un-done at: https://github.com/cms-sw/cmssw/blob/CMSSW_12_0_X/RecoParticleFlow/PFProducer/src/PFAlgo.cc#L795
There could be other ways to treat this complicated case, but I think the current implementation is reasonable.

So, to me, we can close this issue without making any change.

**Comment by tvami** [comment]
+alca
* Based on the previous comment, there are no changes foreseen by the PF experts and the issue can be closed

**Comment by slava77** [comment]
+reconstruction
