### ISSUE TITLE
LogWarning from HcalSeverityLevelComputer:  level 8 already defined in 2017 HLT

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20247]
Sometime shortly before 9_3_0_pre3 this warning started showing up in 2017 matrix workflows running HLT (e.g. 136.788 step2)

```
%MSG-w HcalSeverityLevelComputer:  (NoModuleName) 23-Aug-2017 16:53:57 CEST  pre-events
HcalSeverityLevelComputer: Warning: level 8 already defined. Ignoring new definition.
```

This may be an indication of a problem in the setup.

@kpedro88  @deguio @abdoulline

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
assign hlt

**Comment by kpedro88** [comment]
@jaehyeok please take a look

**Comment by jaehyeok** [comment]
The error message is caused by https://its.cern.ch/jira/browse/CMSHLT-1406, which introduced multiple "sevLevel = cms.int32( 8 )" definitions.

This should be fixed by https://its.cern.ch/jira/browse/CMSHLT-1447 (item [2]). 

Btw, this error message does not have any impact on the performance because all rechits with severitylevel <10 are considered good at HLT.

**Comment by Martin-Grunewald** [comment]
And in turn the above fix should be part of the upcoming HLT menu ("Beatrice" - V3.0).

**Comment by slava77** [comment]
+1

this was apparently fixed
looking at jenkins outputs in 136.788 in CMSSW_9_4_X_2017-10-23-1200
I can confirm that the warning is gone
