### ISSUE TITLE
make phase-2 track time "reco" (smearing) in TrackTimeValueMapProducer reproducible

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20621]
TrackTimeValueMapProducer uses random engine to smear track time parameters.
This is not reproducible in a multi-threaded job.

The fix becomes increasingly important with increased use of tracks with time and 4D vertex in the reconstruction downstream.

**Comment by slava77** [comment]
assign reconstruction,upgrade

**Comment by slava77** [comment]
@kpedro88 
was there any follow up to this issue?

@lgray @bendavid

**Comment by kpedro88** [comment]
I don't think there has been yet. I encourage @lgray or @bendavid to follow the approach I used in #20240.

**Comment by slava77** [comment]
> I don't think there has been yet. I encourage @lgray or @bendavid to follow the approach I used in #20240.

Has there been progress on this one?

**Comment by kpedro88** [comment]
I haven't seen any progress on this.

**Comment by lgray** [comment]
I'll make some time. Today and tomorrow are a bit spoken for, however. Will
try for the weekend.

**Comment by kpedro88** [comment]
Here is a branch:
https://github.com/cms-sw/cmssw/compare/master...kpedro88:TrackTimeDeterministicSeed

It turns out this module can be used twice in an event (a separate copy is made for gsf electron tracks), so I arbitrarily added the leading track chi2 into the seed calculation.

I'm running a matrix test now (wf 20034.2).
