### ISSUE TITLE
broken step MERGE -s PAT in unit test of TauAnalysis/MCEmbeddingTools

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20706]
The tau embedding test is now broken, apparently since #20566.
One example of error is in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20705/23343/unitTests.log
The error is in the MERGE miniAOD step.

to reproduce, checkout TauAnalysis/MCEmbeddingTools and then
run ```scram b runtests```

@gpetruc @swayand @roger-wolf 
please comment if a fix can be made reasonably quickly.
If specifics of the fix will require too much effort, this unit test should be dropped or abridged, as discussed during integration of #17095 (or its preceding PRs).

**Comment by slava77** [comment]
assign reconstruction,analysis

**Comment by gpetruc** [comment]
I've had a quick look. The problem is that the embedding implements track merging - thus creating a new track collection - but doesn't merge or re-run the de/dx info for it.

A one-line fix is to add `process.merge_step += process.doAlldEdXEstimators` in https://github.com/cms-sw/cmssw/blob/master/TauAnalysis/MCEmbeddingTools/python/customisers.py#L358 which will re-run dE/dx.
With more human effort, one could save some CPU time by implementing a merger for the dE/dx info.

I can make the PR with the one-line fix if you like

Giovanni

**Comment by roger-wolf** [comment]
Hi Giovanni,

this would be great. I do not see at the moment, how one of our students 
could implement such a merger within the next days. We will put it on 
our agenda to find a better solution asa our resources allow to.

Cheers,
Roger

**Comment by gpetruc** [comment]
done in #20716

**Comment by slava77** [comment]
+1

fixed in #20716
