### ISSUE TITLE
Use a common setup for electron and muon effective areas

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20704]
muonRelMiniIsoPUCorrected from #20612 has set up an alternative way to compute effective area isolation.
Compare that to egamma code using RecoEgamma/EgammaTools/interface/EffectiveAreas.h
and e.g. RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEffAreaPFIsoCut.cc for electrons

@Sam-Harper @jainshilpi @varuns23 @drkovalskyi @folguera

**Comment by slava77** [comment]
assign analysis,reconstruction

**Comment by slava77** [comment]
there is actually another common approach to do this introduced in #20626
but here the result comes via a producer.

**Comment by drkovalskyi** [comment]
The whole solution is 5 lines of code. Let's not overdo it.

**Comment by slava77** [comment]
On 9/30/17 9:54 AM, drkovalskyi wrote:
> The whole solution is 5 lines of code. Let's not overdo it.

One hardcoded solution is like that indeed.

However, one needs to support multiple versions
and the eta regions are not necessarily cast in stone.

**Comment by Sam-Harper** [comment]
it should be noted that I'm really not keen on the whole effective area mindset. We dont care if we measure the isolation correctly, we just want to distinguish leptons from fakes. This is a completely different situation from reconstruction where we want to correct the measured quanitity such as jet energy.

To me  it would be much clearer if we called it "relaxing the cut value with increasing pileup". 

An isolation cut should be of the form

< X + Y*rho + Z*Et

where X is the underlying event /noise, Y is the pileup term, ie contribution from pileup and Z is the leakage term, ie how much energy from the electron leaks into the isolation region.  X, Y and Z can be (and often are) functions of eta.  Note instead of rho you could use any pileup sensitive variable. 

So I dont see why we need a common framework for what is essentially an arbitary cut. But perhaps I dont understand the issue?

Best,
Sam

**Comment by drkovalskyi** [comment]
At the moment our primary goal in Muon POG is to get all standard selections done centrally to avoid mistakes and different interpretations. It gives us consistency, speeds up analysis synchronization and helps to share code between PAGs. We never recommended EA-based corrections and use it now in one selector simply because it was found to be a good choice by SUSY PAG for their use case. We don't plan to make any changes and start using EA more widely. 

Muon EA-correction has one implementation with the constants specific to muons (I'm not claiming they should be, but they are at the moment). If NanoAOD producers or some other code re-implements it, we should fix that. It can easily be done when all major PRs for 94X are integrated. 

In future we may find a way to use a common strategy for PU corrections in Egamma and Muon POGs, but due to limited manpower it may take a lot of time for us to get there.

**Comment by slava77** [comment]
Sam,
Just to clarify, I was referring to the specific existing implementation of the effective areas
and the fact that the same logic is now implemented for muons as well with a different code.

Dima,
thank you for clarification that the implementation of the muon EA for SUSY is expected to stay likely as a single case situation.

In case the number of variations for muons actually grows, please reconsider this github issue.
I will keep this issue open for some time, although it sounds like it may end up eventually closed with no actual actions.

**Comment by drkovalskyi** [comment]
I don't mind to keep it open. For now the only action item I see is to avoid duplication with NanoAOD code.

**Comment by slava77** [comment]
closing due to low interest or lack of expected gain
