### ISSUE TITLE
clang-tidy confusion for HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#21179]
in the most recent cleanup pass for clang-tidy, I ended up in an infinite loop of adding then removing  override keywords in BPHMultiSelect.h. Eg, here:

+  bool accept( const reco::Candidate & cand ) const override  { return false; }
+  bool accept( const BPHDecayMomentum& cand ) const override { return false; } 
+  bool accept( const BPHDecayVertex  & cand ) const override { return false; } 
+  bool accept( const BPHKinematicFit & cand ) const override { return false; } 

that is, without override, clang-tidy suggest do add it:

build/dlange/clang/CMSSW_10_0_X_2017-11-05-2300/src/HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h:85:8: warning: annotate this function with 'override' or (rarely) 'final' [modernize-use-override]
  bool accept( const BPHDecayMomentum& cand ) const { return false; } 

[partial set of printouts] and with override, clang-tidy suggests to drop it

/build/dlange/clang/CMSSW_10_0_X_2017-11-05-2300/src/HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h:85:53: error: only virtual member functions can be marked 'override' [clang-diagnostic-error]
  bool accept( const BPHDecayMomentum& cand ) const override { return false; } 

/build/dlange/clang/CMSSW_10_0_X_2017-11-05-2300/src/HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h:129:6: note: in instantiation of template class 'BPHMultiSelect<BPHRecoSelect>' requested here
bool BPHMultiSelect<BPHRecoSelect    >::accept(
     ^
/build/dlange/clang/CMSSW_10_0_X_2017-11-05-2300/src/HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h:86:53: error: non-virtual member function marked 'override' hides virtual member function [clang-diagnostic-error]
  bool accept( const BPHDecayVertex  & cand ) const override { return false; } 

[again, partial set of printouts]
I _think_ its confused (at least in part) because all the types used as a template argument have a virtual accept method

BPHMultiSelect<BPHRecoSelect    >  ptSel( BPHSelectOperation::or_mode );
BPHMultiSelect<BPHRecoSelect    > etaSel( BPHSelectOperation::or_mode );
BPHMultiSelect<BPHMomentumSelect>   mSel( BPHSelectOperation::or_mode );
BPHMultiSelect<BPHVertexSelect  >   vSel( BPHSelectOperation::or_mode );

Eg:
  virtual bool accept( const BPHDecayVertex& cand ) const = 0;

which are implemented in BPHMultiSelect:

template<>
bool BPHMultiSelect<BPHVertexSelect  >::accept(
                                        const BPHDecayVertex  & cand ) const;

Ok - after that long saga - the issue is why is clang-tidy confused by this construction? (or is this just a bug in clang-tidy...)

**Comment by Dr15Jones** [comment]
So `BPHMultiSelect<...>` inherits from its template parameter. Searching for that name gives me the following hits
```
BPHMultiSelect<BPHRecoSelect>
BPHMultiSelect<BPHMomentumSelect>
BPHMultiSelect<BPHVertexSelect  >
```

`BPHRecoSelect` has two accept methods 
https://github.com/cms-sw/cmssw/blob/a1a699103d53ed00ae87f2a2578dd7e4b6bd0b5b/HeavyFlavorAnalysis/RecoDecay/interface/BPHRecoSelect.h#L53
which means 3 of the accept methods of `BPHMultiSelect` are not overrides for this class.

`BPHMomentumSelect` has one accept method
https://github.com/cms-sw/cmssw/blob/a1a699103d53ed00ae87f2a2578dd7e4b6bd0b5b/HeavyFlavorAnalysis/RecoDecay/interface/BPHMomentumSelect.h#L46
which means 4 of the methods in `BPHMultiSelect` are not overrides for this class.

`BPHVertexSelect` has one accept method
https://github.com/cms-sw/cmssw/blob/a1a699103d53ed00ae87f2a2578dd7e4b6bd0b5b/HeavyFlavorAnalysis/RecoDecay/interface/BPHVertexSelect.h#L46
which means 4 of the methods in `BPHMultiSelect` are not overrides for this class.

It is not possible to mark any of the `accept` methods of `BPHMultiSelect` as `override` since which ones are actually overrides changes for each template argument used.

**Comment by smuzaffar** [comment]
Looks like @Dr15Jones redesigned this code ( https://github.com/cms-sw/cmssw/pull/26523 ).
@davidlange6 , should we close this issue?

**Comment by davidlange6** [comment]
looks like it
