### ISSUE TITLE
clang-tidy issues for TemplatedSecondaryVertex

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#21180]
The second infinite loop issue I had in the recent clang-tidy cleanup pass was  in TemplatedSecondaryVertex, which starts with:

template <class SV>
class TemplatedSecondaryVertex : public SV {
    public:
	TemplatedSecondaryVertex() {}
	TemplatedSecondaryVertex(const reco::Vertex &pv,
	                const SV &sv,
	                const GlobalVector &direction,
	                bool withPVError = false) :
		SV(sv),dist1d_(computeDist1d(pv, sv, direction, withPVError)),dist2d_(computeDist2d(pv, sv, direction, withPVError)),dist3d_(computeDist3d(pv, sv, direction, withPVError)) {}

		~TemplatedSecondaryVertex()  {} 

among of the templated types is reco::Vertex

typedef TemplatedSecondaryVertex<reco::Vertex> SecondaryVertex;

which eventually triggers this complaint about override (which other classes wan

/build/cmsbld/jenkins-workarea/workspace/run-pr-code-ckecks/CMSSW_10_0_X_2017-11-03-2300/src/RecoBTag/SecondaryVertex/interface/TemplatedSecondaryVertex.h:20:30: error: only virtual member functions can be marked 'override' [clang-diagnostic-error]
        ~TemplatedSecondaryVertex() override {}
                                    ^
/build/cmsbld/jenkins-workarea/workspace/run-pr-code-ckecks/CMSSW_10_0_X_2017-11-03-2300/src/RecoBTag/SecondaryVertex/plugins/BVertexFilter.cc:98:33: note: in instantiation of template class 'reco::TemplatedSecondaryVertex<reco::Vertex>' requested here
            if(svFilter(primary,reco::TemplatedSecondaryVertex<VTX>(primary,*it,axis,true),axis))  {

reco::Vertex does not have a virtual destructor. Should it?

**Comment by davidlange6** [comment]
assign reconstruction, core

**Comment by Dr15Jones** [comment]
The `reco::Vertex` class
https://github.com/cms-sw/cmssw/blob/master/DataFormats/VertexReco/interface/Vertex.h

Doesn't have any virtual functions so it was not intended to have its functionality modified via inheritance. Therefore adding a virtual destructor seems a bit odd since that would be the only virtual function.

What happens if we do not use a virtual function. If the inheriting class is made on the heap and then deleted as a `reco::Vertex` and not as the original type, the memory allocator will be told the wrong size to release for memory. Not good, but I can't see that actual use case happening since `reco::Vertex` has no virtual functions so why were you passing its ownership around like that?

So I'm tending towards not adding the virtual destructor.

**Comment by slava77** [comment]
should it be closed as "not an issue"?
