### ISSUE TITLE
Add an UnorderedPath to the framework

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21627]
Most EDAnalyzers and OutputModules only depend on data products from EDProducers and do not have hidden dependencies with other modules. In those cases, it is safe to allow the framework to schedule running those module immediately. In principal that can be done by putting each such module on its on EndPath. In practice, having that many EndPaths can make it difficult to build a schedule (plus internally the framework has to do extra work for all those EndPaths). 

Another approach would be to allow a user to set a collection of modules which are supposed to be run each Run, LuminosityBlock and Event but which the order does not need to be specified. [Unlike a Path or EndPath where the modules are guaranteed to be run in that exact order]. This concept is akin to a Path (since it would be run at the time all Paths and EndPaths are run). A potential name for the concept is UnorderedPath.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@fwyzard in hypernews brought up the idea of allowing EDAnalyzers (and by extension OutputModules) to be added to Tasks to enable the exact same functionality as an UnorderedPath.

**Comment by Dr15Jones** [comment]
Question: Why do EndPaths (and EDAnalyzers on Paths) not already act like an UnorderedPath?

Answer: In the original design proposal from the threaded framework, EndPaths were supposed to work like UnorderedPaths. Unfortunately, during the implementation of the threaded framework we discovered quite a number of cases where there were hidden (from the framework) dependencies between EDAnalyzers and OutputModules. To avoid rewriting all that code, we decided to have Paths and EndPaths guarantee to run the modules serially in the exact order specified. This also has the added benefit of making it easier for people to reason and debug configurations.

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/29024 effectively makes all Paths/EndPaths work like the `UnorderedPath` sketched here.

What has changed since https://github.com/cms-sw/cmssw/issues/21627#issuecomment-348515614 is that we believe (hope) there are not many modules left with "illegal dependencies", and the PR https://github.com/cms-sw/cmssw/pull/29024 adds a configuration construct `cms.wait()` to make EDProducers/EDAnalyzers act as a synchronization points (in addition to EDFilters) within a Path. Therefore it could make more sense to change the underlying behavior for the majority of the cases and migrate the minority to use `cms.wait()` (that should be eventually addressed anyway) than to migrate the majority to something new.

Just to note explicitly, the `Task` continues to behave distinctly from the `Sequence`: all modules in a Sequence are guaranteed to be run (if filters allow), but modules in a `Task` are run only if some other module to be run depends on them.

**Comment by makortel** [comment]
+1
