### ISSUE TITLE
Remove BoundaryPlane and friends

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#21637]
as discussed in #21558 this code looks to be unused (and its not new)

**Comment by davidlange6** [comment]
assign reconstruction

**Comment by slava77** [comment]
@namapane 
please take a look
the Boundary{Plane,Surface} classes are in MagneticField/VolumeGeometry
Are these a part of still incomplete development or are they now obsolete?

**Comment by namapane** [comment]
Both, in fact. These were intended to be the internals of the STEP propagator, with the idea that magnetic volumes would know their boundary surface and each of these surfaces would know what volumes were present on the other side, so that propagation would not need a global search for the volume at each iteration. However, this plan never took shape because (a) we obtained a very satisfactory speedup by optimizing global search and using a cache for the volume search and (b) somebody you possibly know (!) volunteered to implement a fast and efficient propagator with a less ambitious design. 
Realistically I see no chance we ever get back on implementing this design; it was a cool idea, but life is short.

**Comment by slava77** [comment]
+1

done in #23022 . This is merged in the master and is available from 10_2_0_pre2
