### ISSUE TITLE
Unit test in SimG4Core/Geometry failing in ROOT IBs after integrating VecGeom

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#21887]
The following test:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_0_ROOT6_X_2018-01-17-2300/unitTestLogs/SimG4Core/Geometry
started failing after integrating the following:
https://github.com/cms-sw/cmsdist/pull/3664
on line https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Geometry/test/Cons_.cpp#L51
as the method GetCubicVolume is now putting one extra bit into the volume value of the g4 object
when we print the volume in hex:

```
  std::cout << std::hexfloat << g4v << std::endl;
  std::cout << std::hexfloat << ddv << std::endl;
  std::cout << std::hexfloat << ddsv << std::endl;

  CPPUNIT_ASSERT( g4v == ddv );
  CPPUNIT_ASSERT( g4v == ddsv );
```

Before (using the IB before https://github.com/cms-sw/cmsdist/pull/3664
, CMSSW_10_0_ROOT6_X_2018-01-11-2300):

0x1.579c982414188p+12
0x1.579c982414188p+12
0x1.579c982414188p+12

After:

0x1.579c982414189p+12
0x1.579c982414188p+12
0x1.579c982414188p+12

@civanch @bsunanda

**Comment by smuzaffar** [comment]
assign simulation

**Comment by civanch** [comment]
Gabriele Cosmo confirm that the codes in native and VecGeom are not identical for Cons. Because the computations of weights between native and VecGeom are not identical, some precision lost for the last bit is possible. Me may ignore this problem or we should change unit test adding some tolerance in comparison will be allowed. Making PR is not difficult but I am not 100% sure we have to do it promptly.

**Comment by mrodozov** [comment]
I've alternated the test to accept comparisons with precision 1e-12, to clean the error and still have the test. I hope this tolerance is reasonable, the PR is in the link above

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
This looks solved in CMSSW_10_1_X_2018-01-25-2300. I assume this issue can be closed.
