### ISSUE TITLE
Build error in Calibration/EcalAlCaRecoProducers since CMSSW_10_0_X_2018-01-23-2300

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21955]
A build error in the package Calibration/EcalAlCaRecoProducers is appearing since CMSSW_10_0_X_2018-01-23-2300

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_0_X_2018-01-23-2300/Calibration/EcalAlCaRecoProducers

It looks like to be triggered by patch releases, while it is not present in full builds, and cannot be trivially reproduced (by me) in a normal work area.

The affected package has been recently modified by #21808 , but the file that is searched for is present in EventFilter/ESDigiToRaw and untouched since 5 years. And this modification anyway happened in CMSSW_10_0_X_2018-01-17-1100 well before the problem appeared (@smuzaffar we had other patch releases before the failure appeared).

The problem may cause troubles to patch releases and needs to be fixed asap.

**Comment by smuzaffar** [comment]
@Dr15Jones , @fabiocos 
OK , I understand the issue now. We have added a feature in pkgtools/cmsBuild to make use of existing installation (e.g. /cvmfs/cms-ib.cern.ch/week0 ) area instead of downloading rpms from cmsrep. This is done by creating symlinks in build area. This saves a lot of downloading from cmsrep and 5 to 7 mins of installation time.

So for patch release we end up having 
/build/area/arch/cms/cmssw/CMSSW_FULL_RELEASE/src -> /cvmfs/cms-ib.cern.ch/week0/arch/CMSSW_FULL_RELEASE/src

The code here https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/src/FileInPath.cc#L394 removed symlinks and put and actual path which it points to i.e. /cvmfs/cms-ib.cern.ch/week0/arch/CMSSW_FULL_RELEASE/src

Although it does actually find the file under /cvmfs/cms-ib.cern.ch/week0/arch/CMSSW_FULL_RELEASE/src but then logic here https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/src/FileInPath.cc#L459 could not match /cvmfs/cms-ib.cern.ch/week0/arch/CMSSW_FULL_RELEASE/src to any of the known oaths (local area, release area or data area).

First, I think we should look why Calibration/EcalAlCaRecoProducers search for file during the build process and try to avoid it. 

The pkgtools features save us a lot resources so I would like to keep it. We can add cmssw to the black list ( https://github.com/cms-sw/pkgtools/blob/V00-32-XX/black_list_reference_packages.txt ) so that pkgtools always install it.

**Comment by smuzaffar** [comment]
I see that here https://github.com/cms-sw/cmssw/blob/master/Calibration/EcalAlCaRecoProducers/plugins/SelectedElectronFEDListProducer.cc#L631 
```
desc.add<edm::FileInPath>("ESLookupTable",edm::FileInPath("EventFilter/ESDigiToRaw/data/ES_lookup_table.dat"));
```
which is call during edmWriteConfig and it is going to create edm::FileInPath and search for the file. Can this be changed to desc.add<std::string> and create edm::FileInPath at runtime?

**Comment by fabiocos** [comment]
@smuzaffar see #21958 it should circumvent the problem

assign alca

**Comment by Dr15Jones** [comment]
@wddgit could we add a class static to `FileInPath` which would default to `true` but if set to `false` would cause all `FileInPath`s to not look for their files? Then the executable which creates the _cfi files would be the only place where we set that class static to `false`.

**Comment by wddgit** [comment]
OK. I will work on this now. I am assuming you want this before the other things I am working on.

**Comment by Dr15Jones** [comment]
@wddgit yes, this seems to be a priority.

**Comment by wddgit** [comment]
PRs #21966 and #21967 should resolve this issue and implement the solution Chris suggested with FileInPath.

**Comment by fabiocos** [comment]
@wddgit thank you, I have merged both of them.
@Dr15Jones this should close the issue, I will close my PR as this workaround should not be needed any more
