### ISSUE TITLE
Jet Flavour Clustering on packed PUPPI jets

### ISSUE THREAD

**Issue by ahinzmann** [cms-sw/cmssw#22115]
JetFlavourClustering works fine on any CHS or PUPPI jet collection, except for the case of packed PUPPI jets as in MiniAOD, where the constituents point to the PF packed candidates without PUPPI weight applied.
It gives a warning about non-matching pT, but in principle the code could also deal with it directly
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/JetMCAlgos/plugins/JetFlavourClustering.cc

@rappoccio @ferencek Can we somehow detect packed PUPPI input automatically and then also pick up the weight from another branch? Or Modify the warning message and allow the user to configure it with the PUPPI weight branch and rerun?

@rappoccio Also jet flavour clustering may also run into the issue of the subjets stored as the initial two daughter (like this PR tries to address: https://github.com/cms-sw/cmssw/pull/22094/files#diff-a4f2de9d69c8a4bb1b273b6d5af7cc95R94)

**Comment by slava77** [comment]
assign reconstruction,analysis

**Comment by ferencek** [comment]
@ahinzmann, re-running jet flavor on slimmed jets regardless of their type is not a supported workflow. This is simply because the packed candidates are stored in MiniAOD with reduced precision compared to AOD (from which slimmed jets are derived and later compressed) so by re-clustering packed candidates there is no guarantee you will get the exact same jets (and without the Puppi weight applied, the discrepancies only get worse). The solution is to use updateJetCollection, which does not touch the flavor info and just copies it, or to re-cluster jets from scratch using MiniAOD as input.

**Comment by rappoccio** [comment]
@ferencek I'm confused... if we want to recluster from scratch using MiniAOD as input, we need to do that on the packed candidates. Can you clarify?

**Comment by ferencek** [comment]
@rappoccio, reclustering from scratch is fine. Problems appear if you take slimmed jets already stored in MiniAOD, collect their constituents and then recluster those collected constituents. Because of some loss in precision in the components of the constituent 4-vectos incurred during the AOD->MiniAOD compression, the clustering history can change a bit leading to jets that are somewhat different from those already stored in MiniAOD. This all comes down to the fact that MiniAOD is not a self-reproducing data-tier (in a way, MiniAOD is to AOD what .mp3 is to .wav).

**Comment by rappoccio** [comment]
So we cannot recluster from MiniAOD. That’s what I was asking.

This is probably not so great a solution in the long term. We cannot go back to AOD every time we recluster the jets in the future, since MINIAOD is going to be more widely distributed.

**Comment by ferencek** [comment]
Well, we can cluster jets from scratch using packed candidates stored in MiniAOD. There is just no guarantee those will exactly match what one gets in AOD. I guess this was the price we agreed to pay for reduced event size when MiniAOD was introduced.

**Comment by ahinzmann** [comment]
ok, then it turns out the only use-case is when backporting the flavor-recluster to 80X to rerun the lastest flavor definition on MiniAOD if one wants to avoid reclustering to keep the correct momentum, but is ok with loosing some precision for the flavour definition. This happens in computations of the 2016 legacy JEC.

**Comment by ferencek** [comment]
@ahinzmann, isn't 2016 legacy re-reco planned to be done in 94X where presumably everything that is needed is already implemented. Why is there need to backport to 80X or run jet flavor on top of MiniAOD?
