### ISSUE TITLE
Make "cmsrel" setup the nvidia drivers if they are not present

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#22475]
On a system with an NVIDIA GPU and kernel drivers, CMSSW should use the libraries matching the kernel module's version, which likely means using the libraries available on the system.
This is the default behaviour for a new development area.

On a system without an NVIDIA GPU or the necessary kernel module, CMSSW can use the default libraries, included in the `nvidia-drivers` external package.
This can be done via `scram setup nvidia-drivers`.

One possibility to automate this would be for `cmsrel` (aka `scram project CMSSW`) to check for an NVIDIA GPU and kernel module, and guess the best approach accordingly.

For example, scram could automatically run a check such as
```bash
modprobe -q -R nvidia || scram setup nvidia-drivers
```

A simple script can be used to extract more information:
```bash
#! /bin/bash

NVIDIA_VERSION=

# first, check if the module is loaded and exported on /proc
if [ -f /proc/driver/nvidia/version ]; then
  NVIDIA_VERSION=`cat /proc/driver/nvidia/version | sed -ne's/.*Kernel Module *\([0-9.]\+\).*/\1/p'`
else 
# check if a kernel module is available, even if not currently loaded (e.g. for an OPTIMUS system)
# if there are multiple modules, pick the newest one
  NVIDIA_MODULE=`modprobe -q -R nvidia`
  if [ "$NVIDIA_MODULE" ]; then
    NVIDIA_VERSION=`modinfo "$NVIDIA_MODULE" | grep '^version:' | awk '{ print $2 }'`
  fi
fi

if [ "$NVIDIA_VERSION" ]; then
  echo "nvidia drivers version $NVIDIA_VERSION"
  if locate libcuda.so.$NVIDIA_VERSION | grep '^/\(opt\|usr\)'; then
    exit 0
  else
    echo "nvidia libraries not found"
    exit 2
  fi
else
  echo "nvidia drivers not found"
  exit 1
fi
```

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
thanks @fwyzard for suggestion. We can add some post hooks for cmsrel which can be run to automatically setup/remove tools based on system.

**Comment by smuzaffar** [comment]
@fwyzard , I am thinking of providing scram hooks for setting up/reconfiguring tools. We can have `CMSSW/config/SCRAM/hooks/tools/<toolname>` which scram can run at the time of `cmsrel`.

Should we make nvidia-drivers setup by default for cmssw releases/IBs (to avoid build errors like [a]) and only at the time of cmsrel we reconfigure it if GPU found on the system?

[a]
```
error: edmWriteConfigs caught an exception while loading a plugin library.
The executable will return success (0) so scram will continue,
but no cfi files will be written.
An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load /CMSSW_10_2_0_pre1/tmp/slc6_amd64_gcc630/src/HeterogeneousCore/CUDAServices/plugins/HeterogeneousCoreCUDAServicesPlugins/libHeterogeneousCoreCUDAServicesPlugins.so because libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by fwyzard** [comment]
I would not setup `nvidia-drivers` by default though, as it would break running directly with a release installed on a machine with a GPU without creating a developer area.

Apart from that, having generic hooks sounds like a good idea.
How / "when" do you plan to use them ?
  - at `cmsrel` time
  - at `cmsenv` time 
?

If they are used at `cmsrel` time, can we run them also when the release is installed ?

Thinking about it,  using them `cmsenv` time could be even more flexible: we could use a release installed on CVMFS directly, and `nvidia-drivers` would set its variables or not depending if there is a GPU present or not.

**Comment by smuzaffar** [comment]
We install releases on CVMFS (some shared filesystem) and then these can be used from a machine with or without GPU. So if we have to support shared installation which works for both then I guess we have to run such hooks at the time of cmsenv.  In this case I would not suggest that these hooks change the tool definitions (as mostly they can not write in cvmfs and can not change the externals/arch/lib/symlinks) but just adjust the runtime env so that extra PATH/LD_LIBRARY_PATH can be added.

**Comment by smuzaffar** [comment]
@fwyzard , In 10.2.X DEVEL IBs (CMSSW_10_2_DEVEL_X_2018-04-15-2300 and above) we now have hooks [a] to be called at cmsenv time (cmsenv is also called at `scram build` time). I have added a hook for nvidia-driver [b] which should add the local libcuda.so directory path is available otherwise it fallback to our cuda/drivers. I tested it on `vinavx2` and it properly adds `/usr/lib64/nvidia` in LD_LIBRARY_PATH. 

Can you please test this and let me know if this is good enough?

[a] https://github.com/cms-sw/cmssw-config/blob/master/SCRAM/hooks/runtime-hook
[b] https://github.com/cms-sw/cmssw-config/blob/master/SCRAM/hooks/runtime/00-nvidia-drivers

**Comment by fwyzard** [comment]
Coming back to this - I've tested on the few machines I regularly use, except for my laptop (I no longer have a working CentOS container on it, I will give it a try after reinstalling it), and everything works as intended.

Actually, I think you can simplify the check to
```bash
#!/bin/bash -e
CUDA_BASE=$(${SCRAM} tool tag cuda CUDA_BASE 2>&1 | grep -v 'SCRAM error' || true)
if [ ! "${CUDA_BASE}" ] || [ ! -d "${CUDA_BASE}/drivers" ] ; then exit 0; fi

# if there is an 'nvidia' kernel module assume that CUDA is properly setup
# otherwise add to the library path  the NVIDIA drivers bundled with the CUDA runtime
if ! modprobe -n -q nvidia; then
  echo "RUNTIME:path:append:LD_LIBRARY_PATH=${CUDA_BASE}/drivers"
fi
```

**Comment by smuzaffar** [comment]
+externals
