### ISSUE TITLE
Mark all EDFilters on reconstruction_step Path with cms.ignore

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#23377]
There are 4 EDFilters on the reconstruction_step Path: electronsWithPresel, mvaElectrons, pfNoPileUpCandidates and pfPileUpAllChargedParticles. When we run  `convertToUnscheduled` that function can not remove those EDFilters from the Path and put them on the appropriate Task because those modules are not marked with `cms.ignore()`. 

By using `cms.ignore()` we can increase the amount of allowed intra-event concurrency.

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by perrotta** [comment]
I went through the EDFilter's mentioned in this issue: electronsWithPresel, mvaElectrons, (let include also electronsCiCLoose which enters the HI reco sequence), pfNoPileUpCandidates and pfPileUpAllChargedParticles

It turns out that electronsWithPresel, electronsCiCLoose, pfNoPileUpCandidates and pfPileUpAllChargedParticles are "true" filters, which are however configured in the reco sequence in order to always pass (result of the ```filter()``` function could also be "false" in principle, but it is always "true" with the choosen configurations) -> they can be cms.ignore'd

On the other hand, mvaElectrons is a "ElectronIdMVABased" EDFilter which always returns true by construction [1], and produces mvaElectrons -> This could probably just be moved to become an EDProducer, instead of an EDFIlter 

Therefore, while I plan to respond to this issue by cms.ignore'ing the electronsWithPresel, electronsCiCLoose, pfNoPileUpCandidates and pfPileUpAllChargedParticles filters in the reco sequences, as suggested in the issue description, I would like to hear from the experts if they see any counterindication in making ElectronIdMVABased derive from EDProducer instead of EDFilter, and then modify its ```filter()``` method into a ```produce()``` one (and whatever else could be needed in addition)

@Dr15Jones @slava77 @Sam-Harper @jainshilpi @varuns23 

[1] https://cmssdt.cern.ch/lxr/source/RecoEgamma/ElectronIdentification/plugins/ElectronIdMVABased.cc#0156

**Comment by perrotta** [comment]
This issue is now addressed by #23623

**Comment by Dr15Jones** [comment]
Thanks!
