### ISSUE TITLE
LumiAlCaRecoProducers for negative or zero correctionScaleFactors 

### ISSUE THREAD

**Issue by gkrintir** [cms-sw/cmssw#23661]
Hello,

There are instances that correctionScaleFactors in 
https://github.com/cms-sw/cmssw/blob/master/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc#L162

have negative or zero values. In that case, we can take the avg. of the three preceding bunches as an estimate of the scale factor.

Also in 
https://github.com/cms-sw/cmssw/blob/master/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc#L201

we should consider adding the 0 case, i.e., the if statement should >=.

**Comment by gkrintir** [comment]
assign alca

@samhiggie @capalmer85 could you please have a look?

**Comment by fabiocos** [comment]
assign alca

**Comment by christopheralanwest** [comment]
@capalmer85 Could you either comment on or address this issue? The links in the introduction to this issue reference the line numbers of the code in the master branch and do not give the intended line number as it was when the issue was opened. The correct lines seem to be:
https://github.com/cms-sw/cmssw/blob/d0692d4ee55172ad5221ac549a85b33d4ae2c858/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc#L162
https://github.com/cms-sw/cmssw/blob/d0692d4ee55172ad5221ac549a85b33d4ae2c858/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc#L201

**Comment by tvami** [comment]
Hi @cerminar I see you've edited the `RawPCCProducer.cc` code. Would you be available to address the content of this issue as well? If not, who should we contact? Or is this not relevant anymore? Thanks!

**Comment by cerminar** [comment]
Hello @tvami, I would say that this code belongs to the LUMI POG, I would contact the L2 conveners.

**Comment by gkrintir** [comment]
Issue closed since the code was successfully tested during Run 2 w/o a significant impact
