### ISSUE TITLE
DIGI workflow should be converted to unscheduled

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#24180]
Tests I have done using the configuration for the 2017 DIGI workflow showed that converting to unschedule improved the event throughput of the job by 10%. Part of this may have been because there are EDProducers in the job which are producing data products no other modules want.

**Comment by davidlange6** [comment]
Cool - this is just a cmsdriver option to add to relvals

On 2 Aug 2018, at 21:08, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


Tests I have done using the configuration for the 2017 DIGI workflow showed that converting to unschedule improved the event throughput of the job by 10%. Part of this may have been because there are EDProducers in the job which are producing data products no other modules want.

**Comment by Dr15Jones** [comment]
@kpedro88 
>Did you check that all the output collections come out the same way?

The way the framework works, the output collections are guaranteed to be the same between scheduled and unscheduled.

**Comment by makortel** [comment]
Essentially resolved by https://github.com/cms-sw/cmssw/pull/29024.

**Comment by makortel** [comment]
@cmsbuild, please close

Unscheduled DIGI has been achieved long time ago.
