### ISSUE TITLE
DQMStore should not reset per Lumi histograms at post global begin lumi

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#24337]
The DQMStore will reset the per Lumi histograms here:
https://github.com/cms-sw/cmssw/blob/b2fa44d18d76335bf1d0470e5827e5657549a581/DQMServices/Core/src/DQMStore.cc#L1944

This is a problem, because some 'want to be' per Lumi histograms are filled in the modules 'beginLuminosityBlock' call. If these actually had `setLumiFlag()` called on them, the values that were just set would be reset.

The better place to do a reset would be either at `postGlobalEndLuminosityBlock` or `preGlobalBeginLuminosityBlock`.

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by Dr15Jones** [comment]
@knoepfel FYI

**Comment by schneiml** [comment]
`postGlobalBeginLumi` indeed sounds like the wrong place to do this, but as usually, there is probably a reason for that (it might not be a good one). 

The misunderstanding here might be that many per-lumi things are done in online, completely independent from the per-lumi flag (not sure about the history, maybe these things predate it?). On the other hand, the per-lumi flag is used only by a small number of modules, in part because it is fairly hard to access the per-llumi histograms [1].

So, changing this is something that we should consider in a potential `DQMStore` redesign, but it might break the few workflows that actually use per-lumi histograms. I don't remember the details well, but there is also another duplication of MEs in the `DQMStore` to keep the interface compatible with the legacy modules, which might be related.

[1] Afaik they are only in the `DQMIO` output file, but not the `DQM_*.root` file that goes to the GUI (and is frequently scraped by custom tools). The GUI for sure can't display per-lumi histograms. So to use the per-lumi flag, one has to build a harvesting module that turns it into a per-run ME (but then it is usually also possible and easier to build a per-run ME from the beginning, e.g. a `TProfile` with lumisection number on the x-axis), or a custom harvesting job reading `DQMIO` files, which few people bother to do.

**Comment by schneiml** [comment]
+1

This should be obsolete after #28622.
