### ISSUE TITLE
Failure of LHE workflows on SL7

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#24436]
In the slc7 builds of CMSSW_10_3_X, many LHE-related workflows are failing:
https://cms-sw.github.io/relvalLogDetail.html#slc7_amd64_gcc700;CMSSW_10_3_X_2018-08-31-2300
![LHE failing workflows](http://kjplanet.com/pr/lhe-fail.png)

```
LHE,ENDJOB
We have determined that this is real data (if not, rerun cmsDriver.py with --mc)
Step: LHE Spec: 
Loading lhe fragment from Configuration.Generator.DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff
Step: ENDJOB Spec: 
customising the process with customiseWithTimeMemorySummary from Validation/Performance/TimeMemorySummary
Starting /build/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 7200  cmsRun -j JobReport1.xml  DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff_py_LHE.py
%MSG-i ThreadStreamSetup:  (NoModuleName) 01-Sep-2018 10:21:53 CEST pre-events
setting # threads 4
setting # streams 4
%MSG
   ______________________________________     
         Running Generic Tarball/Gridpack     
   ______________________________________     
gridpack tarball path = /cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.4.2/dyellell01234j_5f_LO_MLM/v1/dyellell01234j_5f_LO_MLM_tarball.tar.xz
%MSG-MG5 number of events requested = 10
%MSG-MG5 random seed used for the run = 234567
%MSG-MG5 thread count requested = 4
%MSG-MG5 residual/optional arguments = false slc6_amd64_gcc481 CMSSW_7_1_28
%MSG-MG5 use_gridpack_env = false
%MSG-MG5 override scram_arch_version = slc6_amd64_gcc481
%MSG-MG5 override cmssw_version = CMSSW_7_1_28
%MSG-MG5 CMSSW version = CMSSW_7_1_28
ERROR: Unable to find release area for "CMSSW" version "CMSSW_7_1_28" for arch slc7_amd64_gcc700.
       Please make sure you have used the correct name/version.
       You can run "scram list CMSSW" to get the list of available versions.
----- Begin Fatal Exception 01-Sep-2018 10:22:01 CEST-----------------------
An exception of category 'ExternalLHEProducer' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module ExternalLHEProducer/'externalLHEProducer'
Exception Message:
Child failed with exit code 1.
----- End Fatal Exception -------------------------------------------------
```

I suppose this is not surprising, since `CMSSW_7_1_X` is only available on SL6. However, it should be addressed eventually.

**Comment by kpedro88** [comment]
assign generators

**Comment by qliphy** [comment]
Adding More experts from GEN: @Saptaparna @lorusso7 @lviliani @agrohsje @covarell @kdlong

We had discussions in GEN in July [https://docs.google.com/document/d/1PZ3TKp5joWVsm0GldwDI-Elr1ftN4G1Y1NfaZ3A1W5w]

What we have done in the summer to make the working flow smoothly,  are mainly for SL6+gcc700, by adding a 7_1_X environment  [e.g. https://github.com/cms-sw/cmssw/issues/23780]

Now for SL7,  indeed as @kpedro88  mentioned,  the current problem is due to CMSSW_7_1_X is not available.

In the July discussions, we had (1) short and (2) long-term plans for SL7, e.g.:

**(1)** 
process.externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
    args = cms.vstring(  'old gridpack',
        'false',
        'slc7_amd64_gcc530',
        'CMSSW_8_4_0'
    ),

**(2)**
modifications to run_generic_tarball_cvmfs : 
1) Run with use_gridpack_env as False
2) Read env for gridpack with the following priority
    a) From the fragment
    b) From a metadata file which will be added for future gridpacks
    c) From the gridpack name
    d) From the runcmsgrid.sh script
    e) If none exist it either fails or uses a default setup
3) Edit the env with slc6--> slc7 when necessary and setup env in run_generic_tarball_cvmfs.sh

**Comment by Saptaparna** [comment]
@qliphy Please let us know whether you would like us to pursue option 1 or 2. Option 1, I think would be faster to implement.

**Comment by qliphy** [comment]
@Saptaparna  Option 1 is easier and can start getting tested.  But let's hear others' comments or have discussion at GEN coordination meeting on 10 Sep.

**Comment by agrohsje** [comment]
@kdlong but ultimately we want/need to do both : update to a new cmssw version and modify the scripts according to (2) so that we can swithc between slc6 and slc7, no ?

**Comment by qliphy** [comment]
@fabiocos @kpedro88     GEN Group had some discussions at [last GEN Coordination meeting](https://docs.google.com/document/d/1sDdPxRx8h3w3odktZubtgJxXjLciV8--y_uF974LHGo/edit#heading=h.on4xolyn0lhd).        We can try to first make O(10) new gridpacks under sl7 for the workflow tests.   

Would you please remind us the time line and urgency to change to sl7 from sl6?  I think this will mainly affect Fall18 part2/3 MC productions,  possibly early next year, right?

**Comment by fabiocos** [comment]
@qliphy the post 10_3_X release should be able to get rid of sl6.

**Comment by fabiocos** [comment]
@qliphy @efeyazgan what is the current status of this move? I think we should hurry to get slc7 fully functional asap.

**Comment by fabiocos** [comment]
@qliphy but what is the plan for already existing gridpacks? To update the fragments? Or are you implying a large new production of gridpacks only for this move? 

@smuzaffar was suggesting also to consider the possible use of Singularity within the production script in case, to have an slc6 environment on slc7 machines. I think it depends on the required amount from your side to go to a stable situation.

In any case do you have a timeline to bring at least validation at a fully function level? Coul we set this as a milestone for one of the next 10_4_X pre-releases (with pre1 deadline being today)?

**Comment by smuzaffar** [comment]
@fabiocos , container might not work if we are already running with in a container :-)

**Comment by qliphy** [comment]
@fabiocos  We plan to do in parallel but need more discussions and task arrangement inside GEN.  

(1) It would be easy to just update the fragments and reuse old gridpacks, but for that we need an appropriate architecture under sl7 ( it is basically libgfortran.3 matters which is not in gcc700). However,  71X is not available at sl7 and in a previous test we found instead 8X can again make old gridpacks work under sl7.  If you can make sure there is a 7X or 8X environment at sl7, then that would save us a lot.  

(2) In the meantime, we are undergoing big changes on big changes on generator tools themselves,  including mg242->mg26x,  and in this case we need to produce large amounts of new gridpacks anyway. And we are thinking to take the chance to merge the two tasks (updating to mg26x and switch to sl7)

For (2) our time line is in ~3-4 weeks to merge to 26x and produce gridpacks for test (maybe under both sl6 and sl7);  For (1) we have done some tests before under sl6 with gcc700 (https://github.com/cms-sw/cmssw/issues/23780  https://github.com/cms-sw/cmssw/pull/24268), but we need more input from your side on availability of 7X or 8X under sl7.

And can you also confirm that probably from early 2019 with 10_4_X we are going to get rid of sl6?

**Comment by fabiocos** [comment]
@qliphy I am not sure about what you mean by " If you can make sure there is a 7X or 8X environment at sl7". The releases that have been produced and are in cvmfs for sl7 are there, nobody is going to trash them, and you can use them. If this is enough to solve your problems (libgfortran.so.3 is there as far as I can see) I invite you to do it asap.

Concerning the production of new gridpacks for sure this should go in sl7. But I would like to avoid waiting months to be able to see tests properly running. As asoon as you have new gridpacks they may be updated.

We will discuss at the O&C week the timescale for the move to sl7, but as far as I am concerned I would like to have it more within weeks than months for 10_4_X.

**Comment by qliphy** [comment]
@fabiocos   

>" If you can make sure there is a 7X or 8X environment at sl7". The releases that have been >produced and are in cvmfs for sl7 are there, nobody is going to trash them

You can check what Kevin mentioned on top "I suppose this is not surprising, since CMSSW_7_1_X is only available on SL6. However, it should be addressed eventually."

We did test months ago that at SL7 there is no CMSSW_7_1_X.  Of course we can check it again now.

**Comment by fabiocos** [comment]
10:22 lxplus061 508> scram list CMSSW_8_0_31_patch1

Listing installed projects available for platform >> slc7_amd64_gcc530 <<

--------------------------------------------------------------------------------
| Project Name  | Project Version          | Project Location                  |
--------------------------------------------------------------------------------

  CMSSW           CMSSW_8_0_31_patch1        
                                         --> /cvmfs/cms.cern.ch/slc7_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_31_patch1

**Comment by qliphy** [comment]
@fabiocos  Thanks a lot.  So we have a CMSSW_8_X as sl7.  We will have some quick test and let you know.

**Comment by qliphy** [comment]
@fabferro   We have done several tests.  
In short,  reset environment to 8X make it work;  changing to 26X gridpack  also works well.    

ssh qili@lxplus7.cern.ch
export SCRAM_ARCH=slc7_amd64_gcc700
cmsrel CMSSW_10_3_X_2018-10-26-1200
cd CMSSW_10_3_X_2018-10-26-1200/src
cmsenv
git cms-addpkg  Configuration/Generator
git cms-addpkg  Configuration/PyReleaseValidation
scram b -j4

(1) runTheMatrix.py -l 512
**girdpack**:  /cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.4.2/dyellell01234j_5f_LO_MLM/v1/dyellell01234j_5f_LO_MLM_tarball.tar.xz
**error**: Unable to find release area for "CMSSW" version "CMSSW_7_1_28" for arch slc7_amd64_gcc700.
**solution**:  change environment to CMSSW_8_0_31_patch1 in 
Configuration/Generator/python/DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff.py
**comment**:  CMSSW_8_4_0 is also there under sl7 and gcc700,  and it works as well.

(2) runTheMatrix.py -l 512
**update gridpack to the one made by 260** (under sl6) also works:
/eos/cms/store/user/qili/26x/DYJets_HT-incl_slc6_amd64_gcc481_CMSSW_7_1_30_tarball.tar.xz

It works Even there is an warning/error message: ERROR: Unable to find release area for "CMSSW" version "CMSSW_7_1_30" for arch slc7_amd64_gcc700.
**In this case, there is no need to set environment to redirect to 8X.** 

**comment**: 26X gridpack doesn't use SysCalc any more, that may be the reason why it works.

(3) runTheMatrix.py -l 551 works, as it has already been updated with 26X gridpack
https://github.com/cms-sw/cmssw/pull/24268

PS.  Previous problem is mainly due to syscalc:
./mgbasedir/SysCalc/sys_calc: symbol lookup error: ./mgbasedir/SysCalc/sys_calc: undefined symbol: _ZN6LHAPDF10initPDFSetEiRKSsi

**Comment by fabferro** [comment]
@qliphy I assume the previous comment wa addressed to @fabiocos . Cheers.

**Comment by qliphy** [comment]
@fabferro  Thanks for pointing out this.  Sorry for the disturbing.

**Comment by fabiocos** [comment]
@qliphy as far as I understand the move to madgraph 26X + sl7 is the plan for next future. For the time being, until the library of new gridpacks is ready, I think we should update the configuration to use the existing ones with the environment from 8YX. Unless you have already new gridpacks available for test workflows...

**Comment by covarell** [comment]
Hello, sorry for coming in the discussion so late, but just asking. 
Apart from release validation issues, where certainly some non-updated gridpacks are there; are we really interested in maintaining support for CMSSW7 and 8 gridpacks in SL7? Already in Fall17 MC production all gridpacks were re-made to comply with new PDF prescriptions, and so they are (at least) made in CMSSW 9, which is available in slc7.

**Comment by qliphy** [comment]
@covarell   Fall17 MG gridpacks were not made in CMSSW9.  You can check from the master branch of genproductions, e.g. : https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L49

I did a test with work flow 562 which exploits the 242 Fall17 gridpack, and it fails with the same reason under sl7.

**Comment by qliphy** [comment]
@fabiocos  "I think we should update the configuration to use the existing ones with the environment from 8YX"
Yes, we discussed within GEN and will make a PR shortly following your this suggestion.

**Comment by fabiocos** [comment]
@qliphy thanks, I think that as soon as you have the new gridpacks the validation should be moved to those. But I would prefer to avoid having a systematically non-functional set of tests, if they can be easily fixed already now.

**Comment by kpedro88** [comment]
@qliphy please sign this issue (the problem appears to be resolved)

**Comment by qliphy** [comment]
+1
