### ISSUE TITLE
EDFilters do not run in unScheduled mode although put in a path

### ISSUE THREAD

**Issue by tocheng** [cms-sw/cmssw#24461]
The issue raised when reproducing SiPixelCalZeroBias ALCARECO using Express data.
CMSSW release CMSSW_10_2_0 was use.

 To reproduce the ALCAREO, the following cmsDriver command is used
step3 --runUnscheduled -s ALCA:SiPixelCalZeroBias+PromptCalibProdSiPixel --nThreads 8 --data --era Run2_2018 --scenario pp --conditions 102X_dataRun2_Express_v1 --eventcontent ALCARECO --datatier ALCARECO --filein /store/express/Run2018C/ExpressPhysics/FEVT/Express-v1/000/319/579/00000/009E1EBD-5B86-E811-A875-A4BF0112F640.root -n -1
 
  The path contains two EDFilters and one EDProducer as
https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiPixelQuality/python/ALCARECOSiPixelCalZeroBias_cff.py#L30

  It turned out that if running in the scheduled mode,
   SiPixelDetectorStatus_siPixelStatusProducer_siPixelStatus_ALCA.obj.fNevents = 0
   SiPixelDetectorStatus_siPixelStatusProducer_siPixelStatus_ALCA.obj.fDetHits = 0
  indicating no pixel hit store in ALCARECO because of the DCS filter
 
  But if running in the unscheduled mode,
  SiPixelDetectorStatus_siPixelStatusProducer_siPixelStatus_ALCA.obj.fNevents = 1483
  SiPixelDetectorStatus_siPixelStatusProducer_siPixelStatus_ALCA.obj.fDetHits = 443068
  indicating neither of the EDFilters worked during production.

  This is unexpected as EDFilters should run so long as they are put in paths in unscheduled mode.

**Comment by Dr15Jones** [comment]
@tocheng this is expected behavior. When you use the `--runUnscheduled` in cmsDriver.py, the configuration has the call `convertToUnscheduled(process)` which removes all `EDProducer` from all Paths and will run those `EDProducers` whenever a module asks for the data. In your case, the `PoolOutputModule` asks for data from `siPixelStatusProducer` and therefore it will be run _unscheduled_.

One can mix running modules as _scheduled_ and _unscheduled_ by explicitly putting `EDProducers` that you want to run unscheduled into `edm.Tasks` rather than `edm.Sequences` and those `EDProducers` you want to run scheduled (i.e. with filtering) must just be on `edm::Sequences`.

**Comment by Dr15Jones** [comment]
assign core

**Comment by tocheng** [comment]
@Dr15Jones Thanks a lot for the explanation! Should I close the issue or you will sign it?

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@tocheng please close this issue as well.
