### ISSUE TITLE
Crash in premixing workflows in 10_4_X

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25147]
Crashes are reported form the validation of premixing for fastsim
https://hypernews.cern.ch/HyperNews/CMS/get/famos/701.html
within the simMuonCSCDigis module. They are reproducible in the most recent IBs (it crashes after some 180 events):

Begin processing the 182nd record. Run 1, Event 182, LumiSection 1 on stream 0 at 06-Nov-2018 22:05:26.737 CET
Begin processing the 183rd record. Run 1, Event 183, LumiSection 1 on stream 3 at 06-Nov-2018 22:05:28.655 CET
%MSG-e MissingProduct:  HybridClusterProducer:cleanedHybridSuperClusters  06-Nov-2018 22:05:31 CET Run: 1 Event: 183
could not get a handle on the EcalRecHitCollection!
%MSG
%MSG-e MissingProduct:  HybridClusterProducer:uncleanedHybridSuperClusters  06-Nov-2018 22:05:31 CET Run: 1 Event: 183
could not get a handle on the EcalRecHitCollection!
%MSG
----- Begin Fatal Exception 06-Nov-2018 22:05:31 CET-----------------------
An exception of category 'CSCDigiProducer' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 183 stream: 3
   [1] Running path 'datamixing_step'
   [2] Calling method for module CSCDigiProducer/'simMuonCSCDigis'
Exception Message:
Invalid DetUnit:  E:1 S:1 R:1 C:9 L:5
Perhaps your signal or pileup dataset are not compatible with the current release?
----- End Fatal Exception -------------------------------------------------

**Comment by fabiocos** [comment]
assign fastsim

@makortel the muon input was touched in #24827

**Comment by makortel** [comment]
I'll take a look.

**Comment by ssekmen** [comment]
Thank you @makortel .

**Comment by makortel** [comment]
And the bug is here on line 178
https://github.com/cms-sw/cmssw/blob/0c1b7739706ac9f8a66aa4e92af5e4fd0109441d/SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py#L177-L181

Here is a fix
https://github.com/cms-sw/cmssw/pull/25149

Note that to test the fix the configuration pointed in the HN message, it has to be applied on the `PSet.py` file by
```python
process.mixData.workers.csc.labelSig = "mix:MuonSimHitsMuonCSCHits"
```
(because the configuration change in #25149 does not propagate to the pickled configuration file).

I wonder though why it didn't get caught in PR/IB tests. Are signal-event muons with CSC hits rare-enough to not get tested with 10 events?
