### ISSUE TITLE
Problem with conditions, crash in test wf 1010.0

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25157]
After the merge of #25131 a reproducible crash appears in the IB for wf 1010.0:

----- Begin Fatal Exception 08-Nov-2018 03:05:45 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 299149
   [1] Calling method for module ECALpedestalPCLworker/'ALCARECOEcalPedestals'
Exception Message:
No "EcalPedestalsRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

This is due to the update of the GT from 
globaltag = cms.string('103X_dataRun2_relval_v6'),
to
globaltag = cms.string('103X_dataRun2_relval_v7'),

**Comment by fabiocos** [comment]
assign alca

@lpernie something appears to be incorrect in your latest PR we were discussing yesterday evening,
a problem with ECAL pedestals

**Comment by lpernie** [comment]
@fabiocos I will check today

**Comment by fabiocos** [comment]
@lpernie we need to have this fixed before closing 10_4_0_pre2, so I hope it can be managed quickly

**Comment by lpernie** [comment]
The problem is that the ECAL pedestal to be consumed by the Queue need to be RUN-based, while the new TAG is LS-based.

The most trivial fix would be to do not change the ECAL pedestal at all and use the one from Express since this Queue is not used in any MC production (need to check with ECAL if this would be acceptable).
Alternatively we can see if any modification to the consumption of the Tag can be done, or if the TAG can be translated in to RUN-based.

**Comment by Dr15Jones** [comment]
The `ECALpedestalPCLworker` is a DQMEDAnalyzer module which reads the conditions in the `bookHistograms` method. The DQM code calls `bookHistograms` at begin Run time, which is not something that can change.

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/Calibration/EcalCalibAlgos/src/ECALpedestalPCLworker.cc#L152

**Comment by fabiocos** [comment]
#25164 addresses this issue
