### ISSUE TITLE
L1T unpacker for HI pointing to incorrect input FEDRawDataCollection

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25177]
While performing checks on express for integration of latest additions I noticed lots of messages like:

%MSG-e L1T:  L1TRawToDigi:caloStage2Digis 09-Nov-2018 16:40:47 CET  Run: 326398 Event: 28488968
Cannot unpack: no FEDRawDataCollection found
%MSG-e L1T:  L1TRawToDigi:gtStage2Digis 09-Nov-2018 16:40:47 CET  Run: 326398 Event: 28488968
Cannot unpack: no FEDRawDataCollection found

**Comment by fabiocos** [comment]
assign l1

**Comment by fabiocos** [comment]
@icali @mandrenguyen to keep track of the issue that I have told you directly
@rekovic this is the problem I have noticed

**Comment by mguilbau** [comment]
I have been facing a similar issue running the L1Ntuple framework on the new data. The reason was that the custumization:

--customise=FWCore/ParameterSet/MassReplace.massReplaceInputTag

Does not replace 'rawDataCollector' by 'rawDataRepacker' for all the L1T module. I am wondering if it is a similar issue here. Bellow the list of collection I had to fix by hand:

process.simTwinMuxDigis.RPC_Source = cms.InputTag('rpcTwinMuxRawToDigi')
process.tcdsRawToDigi.InputLabel = cms.InputTag('rawDataRepacker')
process.onlineMetaDataRawToDigi.InputLabel = cms.InputTag('rawDataRepacker')
process.caloStage2Digis.InputLabel = cms.InputTag('rawDataRepacker')
process.caloStage1Digis.InputLabel = cms.InputTag('rawDataRepacker')
process.gmtStage2Digis.InputLabel = cms.InputTag('rawDataRepacker')
process.gtStage2Digis.InputLabel = cms.InputTag('rawDataRepacker')

**Comment by fabiocos** [comment]
#25193 looks to fix the issue
