### ISSUE TITLE
Memory problem in CSCTriggerPrimitivesProducer

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#25200]
The CMSSW_10_4_ASAN_X_2018-11-09-2300 release shows a 'read after delete' problem in CSCTriggerPrimitivesProducer. However, I think that it is a misclassification and instead it is proably a memory out of bounds problem.

**Comment by Dr15Jones** [comment]
The problem happens here
https://github.com/cms-sw/cmssw/blob/52e9fa5ee041ab5792d6a3861312bbb4981c2a1d/L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboard.h#L297
where `mymap` is a `std::vector`
https://github.com/cms-sw/cmssw/blob/52e9fa5ee041ab5792d6a3861312bbb4981c2a1d/L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboardLUT.h#L45
So I'm guessing the value of `clct.getKeyStrip()` is way outside of the size of the `std::vector`.

**Comment by Dr15Jones** [comment]
assign l1

**Comment by kpedro88** [comment]
@dildick can you take a look

**Comment by dildick** [comment]
@kpedro88 @Dr15Jones I'll look into it this week.

**Comment by dildick** [comment]
My colleague Tao ((@tahuang1991) may have a solution. https://github.com/tahuang1991/cmssw/commit/20194b66f73c0ab6661b88c89652f529a4c7308c. It seems the problem may be due to the fact that in recent pull requests we undid the decoupling of ME1a and ME1b in the CSC local trigger. In the Trigger & DAQ systems ME1a is seen as an extension of ME1b (and this will not change in the future). The ME1a half-strip numbering starts where ME1b ends. Thus a correction needs to be made when looking up the corresponding GEM pad number for half-strips in ME1a. The fix has yet to be tested though.

**Comment by Dr15Jones** [comment]
Ping

**Comment by tahuang1991** [comment]
In previous Sven's thread,  https://github.com/tahuang1991/cmssw/commit/20194b66f73c0ab6661b88c89652f529a4c7308c
this commit should already be integrated into our pull request and it solves the problem.

**Comment by Dr15Jones** [comment]
We are waiting for the l2s for l1 to sign off on the issue.

**Comment by tahuang1991** [comment]
I will look at this one during the weekend. 
Tao

**Comment by tahuang1991** [comment]
I found another bug in L1Trigger/CSCTriggerPrimitives/src/CSCUpgradeMotherboard.cc and after fixing  it, I repeated the test by running "running runTheMatrix.py  -l 21634.0" and confirmed that the problem was solved.  either Sven or I will make a pull request to cmssw today later.

**Comment by tahuang1991** [comment]
see here:
https://github.com/cms-sw/cmssw/pull/25467

**Comment by thomreis** [comment]
+1
