### ISSUE TITLE
Do MET uncertainties have a bug when they scale and shift down electrons?

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#25751]
During the review of PR #25699 it was noticed that when adding extra electrons which are supposedly not considered by the PF, the MET uncertainties were instead somehow affected, see e.g.
![image](https://user-images.githubusercontent.com/4069749/51628836-5d992480-1f46-11e9-9aec-4f2db56f2b2a.png)

The relevant part of the discussion starts here: https://github.com/cms-sw/cmssw/pull/25699#issuecomment-456166898

@Sam-Harper do you have a clearer idea in which part of the code the bug is located?
@eioannou can you please have a look from the MET side?

**Comment by perrotta** [comment]
assign reconstruction

**Comment by eioannou** [comment]
> During the review of PR #25699 it was noticed that when adding extra electrons which are supposedly not considered by the PF, the MET uncertainties were instead somehow affected, see e.g.
> ![image](https://user-images.githubusercontent.com/4069749/51628836-5d992480-1f46-11e9-9aec-4f2db56f2b2a.png)
> 
> The relevant part of the discussion starts here: [#25699 (comment)](https://github.com/cms-sw/cmssw/pull/25699#issuecomment-456166898)
> 
> @Sam-Harper do you have a clearer idea in which part of the code the bug is located?
> @eioannou can you please have a look from the MET side?

@perrotta : I wiil have a look at it.

**Comment by Sam-Harper** [comment]
The bug is simple and trivial for jetMET to fix. The MET uses as input particle flow electrons. However the met uncertainties are computed by scaling up and down all electrons, including electrons which are not used in the MET calculation. 

GsfElectron::passingPflowPreselection()==true should be enforced in the selector. Unless I miss understand what this is doing.

**Comment by Sam-Harper** [comment]
Also not a super huge deal of course but still technically a bug I believe

**Comment by eioannou** [comment]
I confirm that there is a bug which is related to the computation of the met uncertainties. They are computed by scalling up and down all electrons. A possible solution is to edit the two files below in order to scale up and down only PF electrons.
https://github.com/cms-sw/cmssw/blob/17b8235c793832707138ee5eeb04a427de5fda02/PhysicsTools/PatUtils/plugins/ShiftedParticleProducer.cc#L41-L57
https://github.com/cms-sw/cmssw/blob/17b8235c793832707138ee5eeb04a427de5fda02/PhysicsTools/PatUtils/plugins/ShiftedParticleMETcorrInputProducer.cc#L25-L30

The met uncertainties calculations should be computed by PF leptons and not by all leptons. I will edit these two files by making proper changes in order to compute the met uncertainties by using the PF leptons.

**Comment by perrotta** [comment]
Thank you @eioannou !
Please notify here when a PR with your fix will become available

**Comment by perrotta** [comment]
@eioannou : do you have an ETA for submitting the fix?

**Comment by eioannou** [comment]
I have fixed it and I have already had a branch in which met uncertainties are calculated by using PF objects but I didn't make a PR yet, because I am not sure if the PF objects are enough to fix the discrepancy on uncertainties. I mean, I could not manage to confirm that  if the met uncertainties were being calculated by using PF objects, they would not be affected when the new electrons were added.
What I want to do first is, I want to apply the met uncertainties which are calculated by using PF objects without the branch of new electrons added and then applying the branch of new electrons to be sure that the met uncertainties will not be affected by adding new electrons. Is there any way to do that or should I go ahead and make the PR?

**Comment by perrotta** [comment]
Thank you for your answer.
I must admit it is not fully clear to me what you intend... Perhaps, with a PR at hand it can be easier to understand.
I think the rationale is: use to calculate the MET uncertainties the very same objects already used to calculate MET.

**Comment by eioannou** [comment]
Actually, I would like to see if the uncertainties were being calculated by PF objects only, they would not be affected by new electrons.
I will make a PR and we can fix any issue later.

**Comment by eioannou** [comment]
The PR  which fixes the bug in the calculation of MET uncertainties is  #26302.

**Comment by perrotta** [comment]
+1
- Fixed with #26302
