### ISSUE TITLE
Update of JetCrystalsAssociation class

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#25965]
Moving GCC version to minor versions in gcc7 and gcc8 leads to an issue described here:
https://github.com/cms-sw/cmsdist/pull/4616 for which changes in the class JetCrystalsAssociation are required (afaiu make the class not inherit from std::pair). Updating gcc7 from 7.3.1 to 7.4.0 is needed to update Tensorflow  to more recent version :
https://github.com/cms-sw/cmsdist/pull/4703
which doesn't work with 7.3.1 because of:
https://github.com/tensorflow/tensorflow/issues/25323
Both external PRs are now awaiting update on the issue

**Comment by davidlange6** [comment]
hi-
@mrodozov  and I just looked a bit at this class..

it would appear to be produced by one producer
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/RecoBTau/JetCrystalsAssociator/src/JetCrystalsAssociator.cc

which is changed only due to migrations since 2007 It seems to lack the consumes migration - unless we are mistaken this dataformat could not have been stored in any data/mc produced in 3-4 years.

Sounds like something that could be just deleted?

**Comment by smuzaffar** [comment]
In https://github.com/cms-sw/cmssw/pull/25971  this class was removed.
