### ISSUE TITLE
Introduce ProducesCollector to collect produces() registrations from helper objects

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#26576]
We have `ConsumesCollector` to collect registration calls for the consumption of Event and EventSetup data from helper classes of an EDModule. We also have `ESConsumesCollector` to collect EventSetup data consumption registration calls in ESProducers.

But to register Event data production information in helper classes we still pass around `this` pointer of the EDProducer/EDFilter (most notably in mixing modules MixingModules, possibly elsewhere as well). It would be cleaner to introduce a `ProducesCollector` helper class whose object would be passed to the helper objects to collect the product registrations, and make the `produces()` function `protected` in the base class (`ProducerBase`).

**Comment by Dr15Jones** [comment]
assign core

**Comment by wddgit** [comment]
FYI. Just an update on the status of this. I have the Core part of this
implemented along with unit tests and it is all working fine.
(See branch wddgit:producesCollector)

After running cms-checkdeps -a and then scram b -k, I can see 
225 compilation errors where I need to migrate code to use
the new producesCollector. Many are multiple calls to produces in the
same file, which makes it easier. I am starting down that list now...

**Comment by wddgit** [comment]
@Dr15Jones @makortel 

I just wanted to verify something before moving forward with this. I briefly discussed this with Chris last week. In my current working area I have the following constructors for the new ProducesCollector. Note that this is different than ConsumesCollector because it allows copying. ConsumesCollector only allows moving:
```
    ProducesCollector() = delete;
    ProducesCollector(ProducesCollector const& other) : helper_(get_underlying(other.helper_)) {}
    ProducesCollector(ProducesCollector&&) = default;
    ProducesCollector& operator=(ProducesCollector const& other) {
      helper_ = get_underlying(other.helper_);
      return *this;
    }
    ProducesCollector& operator=(ProducesCollector&&) = default;
```
It is easy to change now, but it would be good to know now because this affects how I migrate the code that will use ProducesCollector. It will involve significant rework if we decide to change this after I migrate everything.

**Comment by wddgit** [comment]
PR #28154 implements ProducesCollector. If merged, this issue can be closed.

**Comment by Dr15Jones** [comment]
+1
