### ISSUE TITLE
Failure in wf 136.7801 (and others) after integration of PR #26814

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#27219]
After the integration of #26814 in CMSSW_11_0_X_2019-06-16-2300 there are a few failures in some IB test workflows (136.7801, 136.7803, 1040.0) all with the same problem:

```
----- Begin Fatal Exception 17-Jun-2019 10:20:24 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297227 lumi: 1 event: 48150 stream: 3
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module PhotonIDValueMapProducer/'photonIDValueMapProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Photon
Looking for module label: slimmedPhotons
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

The problem happens in the DQM sequence when the photonIdValueMapProducer is invoked

**Comment by fabiocos** [comment]
assign reconstruction,dqm

@guitargeek please have a look at this

**Comment by fabiocos** [comment]
The problem is reproducible, and adding #26814 on top of CMSSW_11_0_X_2019-06-16-0000 is enough to see it

**Comment by guitargeek** [comment]
Ok no big deal I hope, there was a usage of the `photonIDValueMapProducer` which was not tested in the bot tests and that requires the gedPhotons collection instead of the slimmedPhotons, which I made the new default instead of auto-detecting the right collection:

https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Trigger/python/HLTEGTnPMonitor_cfi.py#L992

I will just fix it in the same way as the `egmPhotonIDs` were treated two likes below: cloning the object and then resetting the input collection. Or do I even need to clone it? I will go the safe way and just clone it for my fixup PR.

**Comment by guitargeek** [comment]
Hi @fabiocos, I proposed a bugfix: https://github.com/cms-sw/cmssw/pull/27221.

**Comment by fabiocos** [comment]
Problem fixed
