### ISSUE TITLE
GetterOfProducts and required products

### ISSUE THREAD

**Issue by schneiml** [cms-sw/cmssw#27424]
Dear framework experts,

the new DQM prototype uses `GetterOfProducts` as suggested by @wddgit and this fundamentally seems to work fine. However, now I have a number of questions on how dependencies are handled.

First the idea of how things should work: The DQM source modules (100's) are `EDProducers` producing products of type `MonitorElementCollection` (all products will be of that type) with label `DQMGenerationReco`. The harvesting modules (10's) are also `EDProducers` and produce `DQMGenerationHarvesting` products. They will
- by default consume all `DQMGenerationReco` products.
- In specific cases consume specific `DQMGenerationHarvesting` products.
Later, an output module should consume all of these.

The current implementation [1] implements this.

Now, a problem is when a module explicitly specifies a dependency [2], but the producer of the specific product is not configured. `GetterOfProducts` does not complain, but the module will not work.

I tried to add `consumes<...>` calls for each of the tags, but I can't get edm to produce an error message. In general, I would like to see an error message (ideally from edm side) when the `GetterOfProducts` would not get any products, because in that case we can't do anything the process is clearly misconfigured. I thought adding a `consumes` for each of the tags in `inputtags` should do, but it seems not [3].

Additionally, I am confused about how to achieve unscheduled execution. The source and harvesting modules run even when I remove the `EndPath` `process.e`, that should pull in the others by dependencies. The manual [4] is not that clear either:

> In release 9_1_0 and later one configures an EDProducer or EDFilter to run unscheduled by also putting it in a Task and associating the Task to a Path, EndPath, Sequence, or Schedule.

I think this is what I do in [5]. But also

> If a module is both on a Path or EndPath and also on a Task, then the module is run on the Path or EndPath and not run unscheduled. The fact that it is on a Task is ignored in this case. 

Does this apply to my case? If yes, how can I get a purely dependency-driven execution?

[1] https://github.com/cms-sw/cmssw/blob/95f34b6a87d6444e57425fbc41d66bd11757b55a/DQMServices/Core/interface/DQMEDHarvester.h#L65-L73

[2] https://github.com/cms-sw/cmssw/blob/95f34b6a87d6444e57425fbc41d66bd11757b55a/DQMServices/Demo/test/rundemo_cfg.py#L45-L48

[3] 
```
mkdir /dev/shm/$USER
cd /dev/shm/$USER
cmsrel CMSSW_11_0_0_pre1
cd CMSSW_11_0_0_pre1/src/
cmsenv
git cms-merge-topic schneiml:dqm-new-dqmstore-on-CMSSW_11_0_0_pre1-from-andrius
git checkout 340f53fa73f9546d8d449fea16598094730e7074
cd DataFormats/
scram b -j10
cd ../DQMServices/Demo/
scram b -j10
cmsRun test/rundemo_cfg.py 
```
[4] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideUnscheduledExecution

[5] https://github.com/cms-sw/cmssw/blob/95f34b6a87d6444e57425fbc41d66bd11757b55a/DQMServices/Demo/test/rundemo_cfg.py#L54

**Comment by Dr15Jones** [comment]
Assign core

**Comment by Dr15Jones** [comment]
@wddgit could you look into these questions?

**Comment by wddgit** [comment]
@Dr15Jones   OK. I will take a look this morning.

**Comment by schneiml** [comment]
@wddgit oops, [3] did not work originally. Fixed.

**Comment by wddgit** [comment]
I am not sure I answered your question. But take a look at what is below and if something is still unclear please ask again and I will look at it some more and try again. And if there is some bug in the Framework behavior we really want to know about it so we can fix it. Hope this helps.

First of all, neither consumes nor GetterOfProducts will complain if a product is not there. This is by design.

GetterOfProducts is only going to select products which some EDProducer declares it produces and products which match the selection criteria. Another important thing to realize is that GetterOfProducts will automatically call consumes for all the products  it selects. For those products, you do not need to explicitly call consumes because GetterOfProducts will call consumes for you and internally saves the tokens.

If a product you expected is not produced and you called consumes, then you later call getByToken and then later dereference the handle, you will not get an exception until you dereference the handle. Even getByToken does not throw.

I never thought about this use case before. I cannot think of a way to make the Framework throw in this case. How would the Framework know how many matches there ought to be? If you really want to do this, here is one possible solution, but I am not sure if this fits your use case. If you knew in advance how many tokens you think you should have found inside GetterOfProducts, then you could call the following member function of GetterOfProducts from your module and check the size of the returned vector. Or just check that it is not empty. But you must call this after all the EDProducers have been constructed, possibly at beginJob. The size of this vector will change as EDProducers are constructed that match the selection criteria and you do not know the order of module construction. One question I would have is this, are there valid cases where you could have zero matches? If there are, then throwing an exception might not be the correct thing.

std::vector<edm::EDGetTokenT<T>> const& tokens() const { return *tokens_; }

One thing I will note. If you add the following to your Tracer configuration you will get a dump of information around begin job time that might be useful to help to understand what is going on.

dumpPathsAndConsumes = cms.untracked.bool(True)

About your other question about unscheduled mode:

I tried to reproduce your unscheduled issues and did not see what you were seeing. Running exactly what was there I see harv3 running because it is on a Path. I comment out that path and nothing runs at all. Both seem OK behaviors. The Path including the Tasks is commented out so the modules on the Tasks do not run. But if I add that path back in I see harv3, harv2, harv1, ana1, and ana2 all trying to run (see below for the Tracer output). It seg faults later at the end luminosity block transition, but still it looks like the unscheduled system is running as expected.  This may not be related, but I will add one comment about something that sometimes confuses people. If the output module runs, then anything configured to produce a product that will be written by the output module will run unscheduled because the output module gets the product. Although in your case the output module is commented out so maybe that is not relevant.

++++++++ finished: prefetching before processing event for module: stream = 0 label = 'harv2' id = 8
++++++++ starting: processing event for module: stream = 0 label = 'harv2' id = 8
++++++++ finished: processing event for module: stream = 0 label = 'harv2' id = 8
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'harv1' id = 7
++++++++ starting: processing event for module: stream = 0 label = 'harv1' id = 7
++++++++ finished: processing event for module: stream = 0 label = 'harv1' id = 7
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'ana2' id = 6
++++++++ starting: processing event for module: stream = 0 label = 'ana2' id = 6
++++++++ finished: processing event for module: stream = 0 label = 'ana2' id = 6
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'ana1' id = 5
++++++++ starting: processing event for module: stream = 0 label = 'ana1' id = 5
++++++++ finished: processing event for module: stream = 0 label = 'ana1' id = 5
++++++++ finished: prefetching before processing event for module: stream = 0 label = 'harv3' id = 4
++++++++ starting: processing event for module: stream = 0 label = 'harv3' id = 4
++++++++ finished: processing event for module: stream = 0 label = 'harv3' id = 4

**Comment by wddgit** [comment]
Sigh. I am not thinking clearly today. We are discussing run and luminosity products. Unscheduled behavior only applies to events. begin/end run/lumi methods are always called.

**Comment by schneiml** [comment]
> We are discussing run and luminosity products. Unscheduled behavior only applies to events. begin/end run/lumi methods are always called.

Ah. That answers one big part of the question.

> If a product you expected is not produced and you called consumes, then you later call getByToken and then later dereference the handle, you will not get an exception until you dereference the handle. Even getByToken does not throw.

Ok, this is well possible. I somehow thought the framework produced these messages already at the scheduling stage, but it is a longe time that I actually saw one of them.

> Or just check that it is not empty.

Ok, I'll probably do that. 

> dumpPathsAndConsumes = cms.untracked.bool(True)

I'll give that a try. Actually my confusion was mostly because I expected the run/lumi transitions not to be called when unscheduled and not needed, and could not see that behaviour. So then there where two things that I was not sure at all about, which is not the best situation to understand something...

Closing since this issue was only the questions and I think they were answered sufficiently.
