### ISSUE TITLE
Sim Application and Sensitive Detector Classes Event Setup Access

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#27466]
* Sim Application accesses EventSetup from  OscarMTMasterThread:
https://cmssdt.cern.ch/lxr/source/SimG4Core/Application/src/OscarMTMasterThread.cc#0137
    * DDCompactView record is percolated to the SD classes

* Some SD classes need more: HGCalDDDConstants, etc.
They become an ```Observer<const BeginOfJob*>``` and access EventSetup as follows:
```
XYZSD::update(const BeginOfJob* job) {
  const edm::EventSetup* es = (*job)(); 
  … 
}
```

Note: The discussion has been triggered by https://github.com/cms-sw/cmssw/pull/27352

**Comment by kpedro88** [comment]
assign simulation

**Comment by civanch** [comment]
@ianna , master thread should not acces SD at all... We need address interactions between DD and SIM and remove one by one old problems.

**Comment by Dr15Jones** [comment]
During the Core meeting, the framework group recommends passing the ConsumesCollector to the various SD during the OscarProducer's constructor. This will allow the SD's to call 'esConsumes' for the data they will get from the EventSetup. Then during the begin Run transition it is safe for the EventSetup to be handed to the SD's directly by the OscarProducer. The framework group recommends NOT using the Observer system to pass the EventSetup since the Observer system was intended to mediate communcation between Geant and CMSSW, not CMSSW to CMSSW.

**Comment by civanch** [comment]
@Dr15Jones , thanks, it seems natural, if we use ConsumesCollector, because SD produce hits.

**Comment by civanch** [comment]
+1
