### ISSUE TITLE
RelMon: warning if some jobs fail

### ISSUE THREAD

**Issue by jan-kaspar** [cms-sw/cmssw#27801]
For example here
https://cmsweb.cern.ch/dqm/relval/plotfairy/overlay?obj=archive%2F319450%2FSingleMuon%2FCMSSW_11_0_0_pre4%2D106X_dataRun2_v17_RelVal_2018C%2Dv1%2FDQMIO%2FCTPPS%2Fcommon%2Fevents%20per%20BX;obj=archive%2F319450%2FSingleMuon%2FCMSSW_11_0_0_pre4%2D106X_dataRun2_v17_gcc8_RelVal_2018C%2Dv1%2FDQMIO%2FCTPPS%2Fcommon%2Fevents%20per%20BX;w=600;h=600;ref=ratiooverlay
we see different number of events processed in test/reference runs. According to Chayanit Asawatangtrakuldee it is due to jobs failing in one of the processes.

Would it be possible that the RelMon page shows a clear warning that incomplete comparison is shown? Otherwise it is misleading and thus potentially dangerous.

Thanks in advance!

**Comment by kpedro88** [comment]
assign dqm

**Comment by jfernan2** [comment]
@jan-kaspar IMHO, I don't see an easy way to asses this: stats in histograms are different almost always due to the nature of the tests. On the other hand, the number of processed events is also usually not exactly the same and this information is not always saved in DQM files, sometimes only the number of processed LSs. sometimes only in some subdetector folders. 

Perhaps the actual RelMon experts know how to better attack this problem, in the meantime I would always take into account stats when performing checks, the chi2 tests in the DQM subsystem/folder are a good indicator of the number of processed entries: more than 1/3 of failures indicate number of processed events are not the same, e.g. http://cms-service-reldqm.web.cern.ch/cms-service-reldqm/ReleaseMonitoring/CMSSW_11_0_0_pre2vsCMSSW_10_6_0/DataReport/SingleMuon2018B-v1_106X_dataRun2_v10_RelVal_2018B_317435/62c0cdb45e.html

**Comment by jfernan2** [comment]
I believe this issue can be closed unless @jan-kaspar has further comments

**Comment by jan-kaspar** [comment]
Again, my apologies for the very late reply.

I am confused. For the relatively short time I am in the "matrix test" bussiness, it seems to me that the definition of the input data (dataset, run, LSs, etc.) is stable. Thus I'd expect identical input for different RelVal campaigns (otherwise it complicates the interpretation, as you also point out). It could be that I am naive...

In PPS, we have periods with no changes in the code and conditions and thus we would expect zero changes in the results. Consequently, it would be great if we could get a short answer from the RelVal system, e.g. "PPS -> 0 differences". Detailed investigation in every campaign, I am afraid, is beyond our manpower possibilities.

**Comment by jan-kaspar** [comment]
I guess that we all have more important things to do at this moment - I close the issue.
