### ISSUE TITLE
Fix unit test in DD4hep

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#28476]
We updated dd4hep here: 
https://github.com/cms-sw/cmsdist/pull/5376
in order to pick the latest changes but the tests are failing due to the same error 
in all the unit tests 
`Fatal in <TGeoMixture::AddElement>: Cannot add element having Z=13 to mixture materials:Aluminium`
One can see all the tests that are failing here: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-35b5f0/3619/unitTests.log

Recent issue was opened on that matter and changes made by the DD4hep quoting the 
aluminium material:

https://github.com/AIDASoft/DD4hep/issues/595 

Looks like cmssw changes are required

@cvuosalo @smuzaffar

**Comment by cvuosalo** [comment]
@mrodozov: Can you submit a PR to fix this issue?

**Comment by mrodozov** [comment]
Well if I knew anything about DD4Hep I would've done it already

**Comment by cvuosalo** [comment]
Might this error be an "aluminum" vs. "aluminium" conflict in spelling?

**Comment by cvuosalo** [comment]
@civanch Might you know what this error might mean?

 [a] Fatal Root Error: @SUB=TGeoMixture::AddElement
Cannot add element having Z=13 to mixture materials:Aluminium

It happens in SimG4Core DD4hep unit tests.

**Comment by civanch** [comment]
@cvuosalo , it is my main concern for DD4hep: they should not use TGeo at all. It is known, that TGeo cannot provide a normal material model, in any case, we have to use work around. Concerning this concrete bug : the error message is meaningless and you may be right, that somewhere there is misspell of element name - in unit test itself or in xml material description. I cannot look before will be back to the office Monday.

**Comment by civanch** [comment]
@ianna , @cvuosalo , I have studied this problem more and can conclude that problem of Aluminium happens only because it is the first material inside materials.xml. If you look below you may see the same problem with other materials. So, TGeoMixture::AddElement failing for all materials. "Aluminium" name is fine even with slightly wrong spelling which is historical.

There is another problem: DetectorDescription/DDCMS/data/cms-geometry-2021.xml includes two lines:

    <Include ref='Geometry/CMSCommonData/data/beampipe/2026/v1/beampipe.xml'/>
    <Include ref='Geometry/CMSCommonData/data/cmsBeam/2026/v1/cmsBeam.xml'/>

here beampipe of 2026 is used, which cannot be correct. We need creating 2021/v1/beampipe.xml and cmsBeam.xml

Inside 2026/v1/beampipe.xml there are typo:

  <Constant name="BeampipeThickness1" value="0.8*mm"/>
  <Constant name="BeampipeThickness2" value="1.0*mm"/>
  <Constant name="BeampipeThickness3" value="1.5*mm"/>
  <Constant name="BeampipeThickness4" value="2.0*mm"/>
  <Constant name="BeampipeThickness4" value="2.5*mm"/>

last two constants have the same name, this should be fixed, however, these BeampipeThicknessX constants never used below. There are two possibilities: use them or remove.

**Comment by mrodozov** [comment]
I don't know what exactly DD4Hep team changed but tests are passing with the latest 4 commits. 
It's in commits 7532b5928bba270023c1fac6f8333e4b132a456b to 982b65499b76600ede1e0e6f79c40fb832967c35 although the changes are mostly cosmetic. 
@civanch I'll suggest lets have an issue about the 2026 / 2021 files separately.

**Comment by cvuosalo** [comment]
@mrodozov Please re-open this issue because the unit test is still failing.

**Comment by cvuosalo** [comment]
@ianna @civanch I have found two problems. When the materials file `[1]` is processed, the check for comparing the atomic weight with the ROOT version of the material is buggy and always fails, which causes an attempt to create materials that already exist. I can fix this test in the code so it only fails if the atomic weights are truly different.
The second problem is that iodine in `[1]` is given the atomic weight of indium (right next to it), so the program tries to add a new version of iodine with the wrong atomic weight. This problem raises the question of why we have elements in this file `[1]`, which just seems to provide the opportunity for typos to create bugs. Aren't all the elements already in ROOT?

`[1]: Geometry/CMSCommonData/data/materials/2021/v1/materials.xml`

**Comment by cvuosalo** [comment]
@ianna @civanch My proposed fixes don't actually address the problem that ROOT raises an error when a program tries to redefine an elementary material. Do we ever need to redefine an elementary material? If so, how can we make ROOT allow it?

**Comment by cvuosalo** [comment]
This problem was fixed by #28671.
