### ISSUE TITLE
[PY3] Unit test CondCore/SiStripPlugins

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#28837]
@mmusich @ggovi 
A unit test of CondCore/SiStripPlugins is crashing in Python3 since CMSSW_11_1_PY3_X_2020-01-28-2300 because of #28761 .

```
===== Test "testSiStripPayloadInspector" ====
Could not find platform independent libraries &lt;prefix&gt;
Could not find platform dependent libraries &lt;exec_prefix&gt;
Consider setting $PYTHONHOME to &lt;prefix&gt;[:&lt;exec_prefix&gt;]
ImportError: No module named site

---&gt; test testSiStripPayloadInspector had ERRORS
 
^^^^ End Test testSiStripPayloadInspector ^^^^
```

The problems is related to `boost::python` used in the 
`CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp`

I tried to remove boost::python (see #28836) and the test is ok also in python3.
The problem arises from the method `PlotBase::setInputParamValues(const boost::python::dict& values)` that was integrated in CMSSW with #28648.

@davidlange6 is it allowed to use boost::python? Is there a way to make it compatible to both python 2  and 3?

**Comment by silviodonato** [comment]
assign db

**Comment by silviodonato** [comment]
assign core

**Comment by mmusich** [comment]
@silviodonato 

> The problems is related to boost::python

as far as I can see the problem is not due to `boost::python` in itself but rather to the `Py_Initialize()`, which is necessary to  in order to avoid a segfault with the `boos::python::dict`.
Some search around in cmssw brought me to the solution at https://github.com/cms-sw/cmssw/pull/28842 , but I am definitely not an expert so if someone with better python-fu can cross-check I would be glad.

**Comment by davidlange6** [comment]
naively we should not set PYTHONHOME by hand. Seems a missing dependency in the Buildfile?

**Comment by mmusich** [comment]
as far as I can see @smuzaffar did the same here: https://github.com/cms-sw/cmssw/commit/aff1edc45d41edf60db24e1b945a017d6c385c29 ...
