### ISSUE TITLE
Converted modules in GeneratorInterface/GenFilters to be thread friendly.

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28898]
The filter modules in GeneratorInterface/GenFilters need to be converted from legacy modules to thread-friendly ones in order for the GEN step to be CPU efficient.

**Comment by Dr15Jones** [comment]
assign gen

**Comment by Dr15Jones** [comment]
An example of such a conversion can be found in #28897

**Comment by wddgit** [comment]
I am starting to work on these. I see 71 modules defined
using the DEFINE_FWK_MODULE macro. At this point,
I am planning to convert all of them (except Chris did
one already).  If anyone knows, it would be nice to have
a shorter list of the ones that are actually used or a list
of ones that are known to be obsolete. That would save
me some time. Expect to start seeing PRs on these soon.

**Comment by wddgit** [comment]
FYI. This list might be useful for someone to do some cleanup some day. These classes are defined in .h and .cc files, but never declared in DEFINE_FWK_MODULE macros so they cannot possibly used for anything.

BdecayFilter
HZZ4lFilter
HighETPhotonsFilter
JetFlavourCutFilter
PythiaFilterEMJet
PythiaFilterGammaJetIsoPi0
PythiaFilterZgamma

**Comment by fabiocos** [comment]
@wddgit a few months ago I moved everything from ```interface``` and ```src``` into a ```plugins``` directory, as agreed with @smuzaffar , but did just a minimal update to preserve the functionality. The list that you mention above sounds to me a s a bug, would not be better to just have each module defined in the end of the ```*.cc``` file? BTW, there is no need to have separate headers I would say, but I wonder whether it is worthwhile to spend time on this, or better just ensure that new filters are setup in an appropriate way.

**Comment by wddgit** [comment]
I checked in release 10_6_2 with LXR. This release does not include your changes moving the modules to the plugins directory. Even there, the 7 modules listed above are not declared in a DEFINE_FWK_MODULE macro. This is not new and your (@fabiocos 's) change didn't introduce it. I did not trace back how far it goes, but suspect that these modules have not been usable for a very long time and conclude they are not really needed for anything. So I would still recommend we skip them in the current migration I am doing. It does not seem worth my time.

And there is another issue. I am finding some modules that have not gone through the consumes conversion and are still using getByLabel without calling consumes. These modules have also been broken for at least 3 years. So my recommendation would be to skip those also. I don't have a complete list of those yet, but I will post the list here when I've gone through them all.

Possibly we should delete them entirely? I leave that decision to someone else.

I am also not sure what tests exist for these filters. I'm trying to avoid complex algorithmic changes where it would be easy to introduce bugs... But so far I have not been writing new tests.

First PR #28946 was submitted yesterday. More coming soon.

**Comment by wddgit** [comment]
If people want, I can move the content of the .h files to the .cc files and delete the .h files. I can also move the DEFINE_FWK_MODULE macro calls from SealModule.cc to the module specific .cc files. I can do this as part of the migration as I work through these and just put it in the same PRs. 

@makortel  Do you want me to do that cleanup also?

Any objections from the generators conveners?

**Comment by makortel** [comment]
@wddgit 

> Do you want me to do that cleanup also?

It would be nice, but only if it does not add too much work. Thanks!

**Comment by wddgit** [comment]
@Dr15Jones Some of these filters use FORTRAN functions which use SAVE'd variables (like static function variables if I remember correctly from ancient times when I last wrote some FORTRAN). So I assume these filters must become "one" type modules. Is that good enough or do we really need them to be "global" modules. In particular, PythiaMomDauFilter uses PYTHIA6's PYCOMP FUNCTION. I am not sure if there others like this or not.

**Comment by Dr15Jones** [comment]
The FORTRAN based filters should be `one::` modules using shared resources. Some of those probably already have shared resources defined.

**Comment by wddgit** [comment]
A somewhat unusual case. In the filter method of PythiaFilterGammaJet
(not endJob as it indicates in the string). It's a counter of events passing
the filter compared to a configurable constant.

```
  if (theNumberOfSelected >= maxnumberofeventsinrun) {
    throw cms::Exception("endJob") << "we have reached the maximum number of events ";
  }
```

My first inclination is that I should delete this counter and the code directly
related to it. It does not seem to me to be a very good way of controlling
the number of events. Am I missing something... Other than this the module
could easily be a "global". With this, it would need to be a "one" type module.
Unless there are objections I will just delete it here and other places I see
something similar.

**Comment by wddgit** [comment]
I will also skip these 6 filters. They do a double delete on the GenEvent
and crash if you try to run them. Three of them I was already skipping
and they are also in the list above of modules not being built. But the
last 3 are being built in current releases. They were broken by a
commit in 2010 as far as I can see. I'll just make the assumption nothing
needs these.

BdecayFilter
HZZ4lFilter
JetFlavourCutFilter
JetFlavourFilter
MCDecayingPionKaonFilter
MCDijetResonance

**Comment by wddgit** [comment]
Possibly I am done with this and this issue can be closed, unless someone requests me to do something more and Matti wants me to spend more time on this. Some comments follow.

The modules I migrated are handled in 3 PRs:
#29048 
#28991 
#28946 
I will take care of these PRs until they get approved and merged.

I counted 76 modules in the GenFilters package

- 16 modules had already been migrated
- 31 modules I migrated in the PRs listed above
- 7 modules have not been built in years, no DEFINE_FWK_MODULE macro
- 3 modules have a double delete bug since about 2010
- 19 modules have been broken for 3 years because they do not call consumes

Unless I get further requests or direction from somebody, I will just leave the modules that have been broken for years in their current state. It does not seem worth my time to fix them.

If requested, I could delete some or all of those files.

If requested and Matti wants me to spend time on it, I could migrate and fix all of the 29 modules I am skipping (several days work). Or I could take care of some small fraction of them that are identified as important.

In the PRs, I just relied on existing tests. I did not write any new ones. I am a little concerned, because either I do not know where the tests are or there are none. Possibly someone should write some tests for these filters or at least the ones deemed important...

For the record, here is a list of the modules that I found to be broken for years:

No DEFINE_FWK_MODULE macro:

BdecayFilter
HZZ4lFilter
HighETPhotonsFilter
JetFlavourCutFilter
PythiaFilterEMJet
PythiaFilterGammaJetIsoPi0
PythiaFilterZgamma

Double delete (note this overlaps with the 
preceeding list, actually more than just 3)

BdecayFilter
HZZ4lFilter
JetFlavourCutFilter
JetFlavourFilter
MCDecayingPionKaonFilter
MCDijetResonance

No consumes calls for products read from the Event:
JGJFilter
UEDMultiLeptonFilter
GenLeadTrackFilter
PhotonEnrichmentFilter
LQGenFilter
RecoDiMuon
MCLongLivedParticles
MCParticlePairFilter
CosmicGenFilterLowE
BHFilter
doubleEMEnrichingFilter
ComphepSingletopFilter
STFilter
XtoFFbarFilter
TwoVBGenFilter
TotalKinematicsFilter
LHEDYdecayFilter
Zto2lFilter
HeavyQuarkFromMPIFilter

**Comment by agrohsje** [comment]
Hi @qliphy, I would be in favor of deleting the broken filters. If somebody needs them, we can always reactivate them. What do you think?  
All PR's are now GEN signed.

**Comment by qliphy** [comment]
@agrohsje   I am fine with deleting the broken filters.

**Comment by agrohsje** [comment]
@wddgit: Would you still be available to remove the broken filters as you suggested?

**Comment by wddgit** [comment]
Yes. I am happy to delete things like that. I'll start looking at that now.

**Comment by wddgit** [comment]
I have the PR deleting the filters prepared. I will rebase it and submit it after the last PR I submitted is approved again and gets merged, because I know this new PR will conflict with that one.

As  I prepared the PR deleting the filters, I found one mistake in my list of broken modules above. I should have counted MCParticlePairFilter as already migrated. It is not broken.

**Comment by wddgit** [comment]
PR #29060 just submitted. It deletes the obsolete filter modules.

I think this issue can be closed now. After that PR is merged there will not be any more legacy modules is GenFilters.

**Comment by wddgit** [comment]
Let's close this. All the PRs are merged now.

**Comment by wddgit** [comment]
Is there anything else I need to do related to this issue to close it out? (If I understand correctly how gitHub works, technically to close this we need a generator signature, +1 on the first line). All the PRs are merged. The legacy modules have all been either converted or deleted.

**Comment by agrohsje** [comment]
+1
