### ISSUE TITLE
Two MuonAlignment classes

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#28974]
It seems that we have two classes named `MuonAlignment`
https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Alignment/interface/MuonAlignment.h
https://github.com/cms-sw/cmssw/blob/master/Alignment/MuonAlignment/interface/MuonAlignment.h

These introduce a high risk of violating the One Definition Rule (if their libraries get loaded into the same program), and therefore one of them needs to be renamed.

**Comment by makortel** [comment]
assign alca, dqm

**Comment by makortel** [comment]
The "DQM MuonAlignment" needs some other work as well https://github.com/cms-sw/cmssw/issues/28975.

**Comment by christopheralanwest** [comment]
I suggest that the class in `DQMOffline/Alignment/interface/MuonAlignment.h` should be renamed since it performs monitoring of the muon alignment whereas the class in `Alignment/MuonAlignment/interface/MuonAlignment.h` actually performs the muon alignment.

**Comment by jfernan2** [comment]
Hi @christopheralanwest , since I was the author of this ancient class, which, to my knowledge it is not being used at present, we would like to completely delete it in order to avoid trouble.
This means also to remove this line:
https://cmssdt.cern.ch/lxr/source/DQMOffline/Configuration/python/AlCaRecoDQM_cff.py#0010
PLease let us know if this is fine with AlCa

**Comment by jfernan2** [comment]
The PR is there https://github.com/cms-sw/cmssw/pull/29027 
Signed by DQM, about to be merged.
Thanks

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
Addressed in https://github.com/cms-sw/cmssw/pull/29027
