### ISSUE TITLE
DD4hep - Tracker Overlaps on Reference & Migrated 2021 Scenario

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#29075]
Tracker DD is showing 53 overlaps at 1e-6 precision (0 at 1.5e-6): 

![OldDD_53Overlaps_1e-6](https://user-images.githubusercontent.com/16821717/75704087-b0cfc180-5c86-11ea-8446-11731be4b2b3.png)

Tracker DD4hep is showing 77 overlaps 1e-6 precision (3 at 1.5e-6):

![DD4Hep_77Overlaps_1e-6_](https://user-images.githubusercontent.com/16821717/75704538-8a5e5600-5c87-11ea-8f8f-e4ec0a020d92.png)

### How to reproduce:
* Dump Geometry:
```
cmsRun $CMSSW_RELEASE_BASE/src/Fireworks/Geometry/python/dumpSimGeometry_cfg.py tag=2021
cmsRun DetectorDescription/DDCMS/test/python/testTracker2021Geometry.py 

```
* Fireworks overlaps config file

```
./cmsShow -c overlaps.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=CMS
./cmsShow -c overlaps.fwc --sim-geom-file cmsSimGeom-2021.root --tgeo-name=cmsGeo
```

**Comment by vargasa** [comment]
FYI: @cvuosalo @ianna

**Comment by makortel** [comment]
assign geometry

**Comment by ghugo83** [comment]
Hi @vargasa ,

The 53 overlaps at 1e-6 precision observed in the Phase I Tracker are due to clashes between TEC petals and optical connectors.

They come from poor meshing with Fireworks + possibly, additionally, from the roundings inherent to rotation matrices.
With Fireworks, 53 overlaps appear with gGeoManager->SetNmeshPoints(1000) (default). But changing the meshing to 100 000, the number of observed overlaps is already reduced to 29.
0 overlap is detected with G4.

To avoid polluting the overlaps space with this, I suggest reducing of an infinitesimal amount the optical connector width.
https://github.com/cms-sw/cmssw/compare/master...ghugo83:from-CMSSW_11_1_0_pre2?expand=1 
This solves all overlaps observed by Fireworks (even at default meshing).

In general, it is good practice to avoid having volumes 'sharp' at the same boundary in the XML description, since with default meshing / rounding errors, they can be seen / become overlaps. 
Directly using an epsilon in the XML description in this kind of situations should solve a lots of headaches, at no cost for the geo and Material Budget.

**Comment by ghugo83** [comment]
Just did a PR at https://github.com/cms-sw/cmssw/pull/29366 , let's close this once and for all ;p

**Comment by vargasa** [comment]
Hello @ghugo83, Thanks a lot for looking into this. By any chance did you check if this is the same reason for overlaps when running on DD4Hep algorithms? (as the issue was originally opened to keep track of DD4hep overlaps I'd prefer to keep it open until those are fixed too) Thanks a lot again @ghugo83

**Comment by vargasa** [comment]
@ghugo83, nevermind. I saw your commits on the PR. Please feel free to close it once it's merged. Thanks a lot!

**Comment by ghugo83** [comment]
@vargasa Yes absolutely, it also solves the overlaps seen when running on DD4Hep algorithms.
Yes I looked at this because @civanch requested me to solve the overlaps in run 3 Tracker and then I saw this issue passing by.
In PR at #29366 there are few more comments.
Ok I ll close the issue when PR is merged.
