### ISSUE TITLE
Implementing fallback for reading conditions from file

### ISSUE THREAD

**Issue by hernand** [cms-sw/cmssw#29558]
As discussed in the O&C meeting on April 22nd in this contribution: https://indico.cern.ch/event/911363/contributions/3833977/attachments/2024913/3386980/20200422_Using_BSC_Update.pdf
we are finding the way in the CMS WMS to exploit supercomputing resources where the compute nodes don't have network connectivity. 
One of the issues is finding a way to read conditions data without access to the Frontier system. The idea is to dump the required conditions data into a sqlite file that can be read by the application. In order not to modify the pset configuration (which would change the provenance since the connect parameter is a tracked one), it was suggested to implement a fallback mechanism in the access to conditions data falling back to reading them from a file when the read through Frontier fails.

**Comment by makortel** [comment]
assign core, db

**Comment by makortel** [comment]
Towards an implementation, the idea would be to add additional parameter to `PoolDBESSource` in addition to the current `connect`, e.g. `connectFallback`, as a tracked `string`. Whether to use the `connect` or `connectFallback` would be decided at the very first use of the connection: if `connect` works, use that for all access for the whole job, otherwise use `connectFallback` for the whole job (and treat both `connect` and `connectFallback` not working in the same way as `connect` failures are treated currently).

@ggovi What do you think?

**Comment by makortel** [comment]
@ggovi Do you have any thoughts? @wddgit is starting to look into implementing the fallback mechanism.

**Comment by makortel** [comment]
@ggovi's presentation in the Core Software meeting today (slide 10)
https://indico.cern.ch/event/927304/contributions/3898824/attachments/2052350/3443738/CMS_DBSoftware_Planning_2020.pdf
mentions a possibility to set up Frontier to read the conditions data from a file.

@hernand Would such an arrangement be feasible in your case? (to explore options if nothing more)

**Comment by ggovi** [comment]
@makortel 
sorry I've missed this item. I'll have a look tomorrow!

**Comment by hernand** [comment]
> @ggovi's presentation in the Core Software meeting today (slide 10)
> https://indico.cern.ch/event/927304/contributions/3898824/attachments/2052350/3443738/CMS_DBSoftware_Planning_2020.pdf
> mentions a possibility to set up Frontier to read the conditions data from a file.
> 
> @hernand Would such an arrangement be feasible in your case? (to explore options if nothing more)

Thanks for the pointer. I see not much information in the slides but it looks the idea is to store payloads in files and access them via Frontier. Our problem is that worker nodes don't have access to Internet and need to read conditions data from local files, so we still need a mechanism to copy the conditions data files to the worker nodes and have a mechanism in CMSSW to read them without changing the pset (not to change the provenance hash). So, we still need a fallback mechanism in CMSSW to read conditions from a local file if the access via Frontier fails.

**Comment by ggovi** [comment]
@makortel We could investigate with the Frontier expert about the feasibility to set up the fallback within frontier. This - I guess - would solve the issue of the distribution of the sqlite files involved.
However, the fallback mechanism in PoolDBESSource looks to me a good idea anyhow. I can also try to implement it if required.

**Comment by makortel** [comment]
@hernand Do I interpret correctly that setting up a Frontier instance inside the BSC would not work? (taking a look again your slides, slide 4 saying "No network connectivity in compute nodes!" sort-of confirms that, and thus the fallback-to-file within cmsRun indeed sounds like the best option)

**Comment by hernand** [comment]
> @makortel We could investigate with the Frontier expert about the feasibility to set up the fallback within frontier. This - I guess - would solve the issue of the distribution of the sqlite files involved.
> However, the fallback mechanism in PoolDBESSource looks to me a good idea anyhow. I can also try to implement it if required.

> @hernand Do I interpret correctly that setting up a Frontier instance inside the BSC would not work? (taking a look again your slides, slide 4 saying "No network connectivity in compute nodes!" sort-of confirms that, and thus the fallback-to-file within cmsRun indeed sounds like the best option)

Not only the best option, I would say the only option currently. 
The network setup at BSC is quite restrictive, worker nodes do not have connectivity to Internet, so no way to talk to an external Frontier server, but even worse, nodes are not allowed to talk to internal services either, so currently there is no possibility to install any edge service like a Frontier instance.

**Comment by makortel** [comment]
@hernand Thanks for the clarification!

**Comment by wddgit** [comment]
I am planning to start looking at this fallback parameter issue tomorrow (related to reading conditions from a file). If there is any new information that would help me, please let me know. For example, if someone else is already working on it or if there are already ideas on exactly what criteria I should use to decide whether to fallback, or anything else is already known that would guide me to the correct solution, please let me know. I don't know much about this yet nor do I yet have any ideas about the exact details of the implementation.

**Comment by hernand** [comment]
Thanks for looking into this. From my side there is nothing new. Regarding the fallback, I guess some naming convention for the filepath/filename should be established. It could be as simple as looking for a file named conditions.sql in the CWD, but I guess there should be an option to be able to specify filepath/filename. Modifiying an existing pset is not an option for our use case (that would modify the provenance hash) so maybe through an env variable?

**Comment by makortel** [comment]
The file name should be taken from configuration as tracked `string` (as outlined in https://github.com/cms-sw/cmssw/issues/29558#issuecomment-619053907). I think the value to be used in production is outside of the scope of implementing the feature (as far as `core` is concerned), and is something to be agreed when defining the configurations of the campaigns. I'd much prefer to avoid any further reliance on environment variables (using FileInPath internally to allow the standard non-event-file search paths would be fine).

**Comment by hernand** [comment]
ok, if the tracked string for the filepath/filename is set by production up front, it should be fine. In any case, I think it would be convenient to set a default value in case the parameter is not specified  (e.g. my suggestion ./conditions.sql). This would allow using the fallback mechanism before the fallback parameter is added to the config file of the production campaigns.

**Comment by wddgit** [comment]
In CondDBESSource, it is possible to override the global tag or add additional entries in the tag collection using a vector<ParameterSet> in the configuration. The parameter name of this vector is "toGet". Each entry in the vector overrides for a particular record and label. And those overrides also allow overriding the connection string for that record and label. If the fallback connection string is being used, should the fallback connection string also be used for those records where the connection string comes from "toGet"?

Possibly this never happens, but code in CondDBESSource.cc seems to allow overriding the connection string with a tag from the global tag of the form "tagname@[connectValue]". Does this ever happen? If the fallback connection string is begin used, should these also get overriden by the fallback?

**Comment by wddgit** [comment]
I have a very rough draft for this here:

https://github.com/wddgit/cmssw/commit/983cfd2d468dbdda9febd3e127f11b18e7ac4d63

The code is not really that hard. The difficulty lies in deciding exactly what behavior we want. Any comments would be appreciated. This is not tested yet (might still have dumb bugs in it). Does anyone have a recipe for a test where I could test the fallback behavior? Or does someone want to volunteer to do this test for me because you are interested and setup to do the test easily? This version defaults to not having any fallback. Do we want a default fallback connection string? If yes, EXACTLY what should the default fallback connection string be? Probably a default connection string would need to include a protocol. CondDBESSource does not have a fillDescriptions function yet. Should I implement one? Should I convert the coral exception type to a cms::Exception at a lower level? Is catching the exception the correct way to detect that we need to try the fallback? My previous comment also has a question in it. I will continue on this tomorrow. Any answers to these questions would be appreciated.

**Comment by makortel** [comment]
Thanks @wddgit for the good questions. Given that the `toGet.connect` is tracked (despite of [SWGuideFrontierConditions](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions#Customization_of_Global_Tags) claiming "the connect string is untracked") I _think_ some kind of override mechanism is needed for those connection settings. Then thinking out loud

If GlobalTag is customized such a way, I'd guess having only a single fallback option for all connections could be problematic (if the GT is customized in production or RelVal, it is probably for good reason, and exporting the GT and the customized tags to a single sqlite file could be problematic). That would suggest to have an optional `toGet.connectFallback`.

> Possibly this never happens, but code in CondDBESSource.cc seems to allow overriding the connection string with a tag from the global tag of the form "tagname@[connectValue]"

@ggovi Can you comment if passing connection string via the tag name is a supported feature, or an implementation detail? If it is a supported feature, my earlier argument would suggest that it should have an ability to have a fallback as well.

On the other hand, if we would know that any production use will never use both `toGet` and fallback, we _might_ get away without any of that.

**Comment by makortel** [comment]
> Does anyone have a recipe for a test where I could test the fallback behavior? Or does someone want to volunteer to do this test for me because you are interested and setup to do the test easily? 

@ggovi @hernand Would either of you be able to help with testing?

> This version defaults to not having any fallback. Do we want a default fallback connection string? If yes, EXACTLY what should the default fallback connection string be? Probably a default connection string would need to include a protocol. 

I would start without a default fallback. I can not think of any sensible default value for the fallback connection string.

> CondDBESSource does not have a fillDescriptions function yet. Should I implement one? 

I would leave the `fillDescriptions()` for a separate exercise.

> Should I convert the coral exception type to a cms::Exception at a lower level? Is catching the exception the correct way to detect that we need to try the fallback? 

@ggovi Could you comment?

**Comment by wddgit** [comment]
A few thoughts. These are not particularly connected to each other.

1. ```toGet.connectFallback``` This would be useful if data related to a "toGet" is available in a separate sqlite file for that particular tag and and that data is not in the sqlite file being used for the data with tags from the global tag. It is not going to help if the "toGet" tag data is in a database that requires network access. I do not know if that situation ever occurs. It's easy enough to implement this if it is useful, but I wouldn't want to complicate things by adding code that will never be used.

2. Note that I could slightly simplify the PR if I assume that in every case where we want to use the fallback, there will be a call to createSession while getting the tags related to the global tag. Then later the calls to createReadOnlySession could assume the decision whether or not to use the fallback was already made. I wouldn't need to replicate that try-catch logic in a second place. It appears in the second place only to support cases where there are no tags from the global tag in the tag collection and all the tags come from the "toGet" configuration parameter sets.

3. Another alternative is to throw an exception if both parameters exist (the "toGet" parameter and the "connectFallback" parameter). Or if they are both exist and are not empty.

**Comment by wddgit** [comment]
I tested the draft code using runTheMatrix, all limited tests pass. I'm pretty sure all will run exactly the same as now if I don't set the fallback parameter.

I also tried putting in a bad connection string. It threw a std::exception instead of the exception types I had expected (cms::Exception or coral::ConnectionServiceException). Although maybe this is not the right way to test for the case of no network access. Or maybe I should just be catching std::exception, both of the types I expected also inherit from that.

**Comment by hernand** [comment]
Thanks for making progress on this!
A couple of comments:

- I think there is still some value in having a default fallback string (e.g. sqlite_file:conditions.sql)

- I can try to test the fallback mechanism at the HPC machine in Barcelona where nodes do not have network connectivity. We have recently got an allocation of 250k hours that I requested for testing CMS workflows.  I have been using for my tests a singularity image including CMSSW_10_6_12, using the global tag 106X_mc2017_realistic_v6 dumped into a file  (800 MB!) running:  conddb copy 106X_mc2017_realistic_v6 --destdb /tmp/conditions_106X_mc2017_realistic_v6.db  

If I can get the new code into a docker image (Shahzad built the docker image with CMSSW_10_6_12 for my tests), I could easily test the new code under real conditions. 

Thanks

**Comment by wddgit** [comment]
For testing purposes, I created a branch in my personal git hub account with a 10_6_12 back port of the proposed changes:

https://github.com/wddgit/cmssw/tree/connectionFallback10612

My first question. Am I catching the right type of exception? Currently cms::Exception and coral::ConnectionServiceException. Should I switch to std::exception? Or some other type? Or detect connection failures in some other way?

@ggovi Do you agree with adding a default value "sqlite_file:conditions.sql"? This will make CondDBESSource try the fallback even if the parameter is not set. The advantage of no default is that nothing will change in the behavior of an executable until the parameter is actually added. I have no opinion which way is better. Either way is good with me.

**Comment by makortel** [comment]
> Do you agree with adding a default value "sqlite_file:conditions.sql"? This will make CondDBESSource try the fallback even if the parameter is not set. The advantage of no default is that nothing will change in the behavior of an executable until the parameter is actually added. I have no opinion which way is better. Either way is good with me

@ggovi What do you think about David's question above?

**Comment by makortel** [comment]
> Do you agree with adding a default value "sqlite_file:conditions.sql"? This will make CondDBESSource try the fallback even if the parameter is not set. The advantage of no default is that nothing will change in the behavior of an executable until the parameter is actually added. I have no opinion which way is better. Either way is good with me

@ggovi What do you think about David's question above?

**Comment by ggovi** [comment]
Apologize for the late feedback. I'm actually a bit confused. Basically, here we are aiming to serve the use case where no connectivity is available. Fine, in this case the ENTIRE condition set identified by a GT must be self-contained in the local file.  What id the advantage of the fallback mechanism? The usage of single, unchanged configuration file? Does this mean that the file is shipped everywhere in any case?

Concerning the toGet. This is something different. It allows to overwrite individual pairs Record/Tag, with a specific Tag name, and a specific source DB. It is used in the private validation of new condition set, by the experts. In general, for production workflow, this should be not allowed. It is currently under AlCa tasks the search of these invalid cases and their clean up.

On the default value sqlite_file:conditions.sql. Our naming convention is rather "conditions.db". However, it does not look obviously useful to me. No fallback should be attempted if not explicitly instructed. 

Please let me know if you think we should have a short discussion session on zoom...

**Comment by makortel** [comment]
@ggovi Thanks for your comments.

> What id the advantage of the fallback mechanism? The usage of single, unchanged configuration file?

Correct. Framework uses the hash of the configuration (essentially from all tracked parameters) to differentiate data. Therefore, in order to combine data processed on a site using the fallback mechanism with data processed on other sites using Frontier into a single dataset, a single configuration file is needed everywhere.

> Does this mean that the file is shipped everywhere in any case?

I'd argue for "no", the file should be made available only on sites that "intentionally" have no access to Frontier.

> However, it does not look obviously useful to me. No fallback should be attempted if not explicitly instructed.

The idea would be that (at least) workflows to be run at sites without an access to Frontier would have `connect` set to the default Frontier access, and `connectFallback` set to some file name. Then
* A site with a connection to Frontier would not have the fallback file. Normally all DB access goes to Frontier. In case of errors during data processing (after first connection succeeding) the errors would be reported as today. If the first connection fails, the fallback file would be attempted, but because it does not exist, an error would be reported (that should contain also the original error from Frontier)
* A site without a connection to Frontier has the fallback file. The first connection to Frontier fails, after which the fallback file is attempted, which succeeds.

Possible risks include at least
* The fallback file contains incorrect information. From the event provenance we'd at least know if a fallback was possible or not, and cross-referencing that to on which site an event was processed we'd know if fallback was really used or not. To debug beyond that we'd need more details from the site.
* A file with the same name as in the fallback file exists for other reasons, first connection to Frontier fails for some reason, the file gets accidentally used. (I believe risk should be tiny in production)

**Comment by wddgit** [comment]
In addition to Matti's comments, I add the following.

Thanks for the information about toGet. I will revise the code to
not use the fallback for those cases . That should simplify the
PR.

Not having a default fallback sounds safer to me. If there is no
default, then PoolDBESSource will behave exactly as it currently
behaves. If the PR that I am preparing creates a problem, then
we can go back to the previous behavior by changing only
configurations.

The main remaining question is this. What kind of exception should
we be trying to catch? coral::ConnectionServiceException or
std::exception or cms::Exception or catch(...) or something else?
And I am presuming the exception gets emitted from createSession.
This seems the only reasonable place and an exception throw seems
the only reasonable symptom of a problem, but it would be nice to verify
that with a test in a realistic environment.

**Comment by makortel** [comment]
One option to consider would be to use the site local config to allow the fallback to be used (from @Dr15Jones).

**Comment by wddgit** [comment]
I gave this another try. The new draft code is in this one commit:

https://github.com/cms-sw/cmssw/commit/e7ce1eb56a6fb3a471b767b27fb5d8ea9c803740

I have not tested this yet. It is simpler and reflects most of the comments above.

- It does not use the fallback for toGet items which specify their own connect string.
- Nothing changes in the case where there is no global tag (fallback is not tried).
- If and only if there is a global tag and a fallback string and the primary string fails, then it tries to connect with the fallback string. If it succeeds, then it replaces the primary "connect" string in all cases.
- If the fallback also fails, then it prints an exception with the content of both exception messages.
- It catches std::exception.
- If there is no fallback string, things will behave exactly as before.

This is not tested. It would really be helpful if someone could try it in an environment where it will actually be used. In particular, one thing I am concerned about is whether std::exception is the best type of exception to be catching. I do not have access to these sites or know how to use them.

This does not use local site config. @makortel Do you want me to spend time trying to figure ought how to handle that? Or was that just something for discussion at this point?

**Comment by makortel** [comment]
@wddgit Thanks!

> Do you want me to spend time trying to figure ought how to handle that? Or was that just something for discussion at this point?

At this time no, that was just something for discussion.

**Comment by wddgit** [comment]
OK, good. I will wait until I do anything more on this. By the way, I meant "figure out" not "figure ought".  Not sure how my brain made that typo...

**Comment by ggovi** [comment]
It could be maybe a late feedback for how the things have been evolving in this thread... But what if instead of a fallback ( that sounds like an auto-recovering feature in an error occurrence ) we have a site-specific function that returns ( a boolean ) the availability of the frontier service? In this case, with no change at all in the C++ code, the python driver could select the different connection string, and use the sqlite local file... Looks to me simpler. Am I missing something?

**Comment by makortel** [comment]
> In this case, with no change at all in the C++ code, the python driver could select the different connection string, and use the sqlite local file... Looks to me simpler. Am I missing something?

That would lead the configuration hash to change.

**Comment by ggovi** [comment]
@makortel I'm not sure. The content of the parameters would be unchanged. Or better, of course the first time we introduce this function there will be an hash change ( which I guess must be handled when fixes are required ) - then the hash would remain stable

**Comment by makortel** [comment]
@ggovi Then I didn't understand what exactly you meant with

> we have a site-specific function that returns ( a boolean ) the availability of the frontier service? In this case, with no change at all in the C++ code, the python driver could select the different connection string, and use the sqlite local file...

I thought it would mean that a function in python would change the content of `process.GlobalTag.connect` depending on the availability of Frontier. Did you mean that? If not, could you give more details?

**Comment by wddgit** [comment]
You could have two configuration parameters, say "connect" and "connectLocal". Then choose between them based on the site specific functionality instead of looking for an exception when the session is created. When the new parameter is first introduced it would be a hash change, but only then.

**Comment by wddgit** [comment]
One question I have. Does the SiteLocalConfigService require network connectivity? I know nothing about it. I've never been in that code before.

**Comment by ggovi** [comment]
I think @wddgit  got the point. The two connection strings would be both in the configuration, only the choice is delegated upon the site specific functionality - that btw i'm not sure it already exists, but it could be probably introduced.

**Comment by makortel** [comment]
> Does the SiteLocalConfigService require network connectivity?

It does not, it simply reads an XML file (provided by the site).

**Comment by makortel** [comment]
@ggovi Could you confirm my suspicion that essentially a single file can support only one Global Tag, and information of two (or more) GTs need to be split into separate files?

**Comment by makortel** [comment]
> Could you confirm my suspicion that essentially a single file can support only one Global Tag, and information of two (or more) GTs need to be split into separate files?

On further thinking I think I was wrong, so could you @ggovi confirm if a file can support many Global Tags?

**Comment by wddgit** [comment]
I looked at the code for SiteLocalConfigService. It looks easy to add a new field in that service and use it in CondDBESSource. I don't know how to change a site-local-config.xml file at a particular site. Probably someone else would need to do that. Let me know if you want me to go ahead with coding that. If anyone has any preferences for names to use for the configuration parameter or site local config parameter, please let me know.

**Comment by makortel** [comment]
Thanks @wddgit for taking a look.

> Let me know if you want me to go ahead with coding that. If anyone has any preferences for names to use for the configuration parameter or site local config parameter, please let me know.

Let's hold off until we have agreed on the exact details to be done.

> I don't know how to change a site-local-config.xml file at a particular site. Probably someone else would need to do that.

Correct, adding the necessary piece to `site-local-config.xml` would be up to he admin of the corresponding site.

**Comment by makortel** [comment]
I asked from @stlammel if he would see any problems with adding such a field in to site local config, and he did not see any problem. He also gave further suggestion (which was actually motivated my question https://github.com/cms-sw/cmssw/issues/29558#issuecomment-687252956)

> If we envision other DB access in the future, i would not call it connectFallback but <file-connect> (or similar)
and handle the "connect" entries in <calib-data> as ordered list. This would make it more general and allow
also the other direction, file first---frontier second. Just a thought.

I think controlling the behavior fully in site local config would be an interesting option. It would certainly require that many GlobalTags can be stored in a single file.

A further concern I have is that there would be no trace in the event provenance would not have any information if the conditions were read from a file or via Frontier. Admittedly a `connectFallback` would do only marginally better, by showing a possibility for a fallback in the provenance but not if Frontier or the fallback was used. And in principle the sites could already point the Frontier URLs and caches to whatever, so would allowing the access to be redirected into a file be that much different? (it is a bit more error prone because of someone having to explicitly dump GlobalTag(s) to the file).

**Comment by hernand** [comment]
Thanks guys for keeping working on this. I agree that the option of using the site local config file to specify DB access urls (Frontier or local file) looks better than falling back to file access on exception.  Not sure if a single file containing many global tags is feasible. Who can know? For my tests I dumped a single global tag into a file and its size was about 1 GB. Maybe it would be better to have a single file per global, but that would required defining a naming convention for the file names. It should be  based on the global tag names. The site local config url would  specify the directory where conditions data files are located (similar to the Frontier url) and the connect string would be built by the framework using the specified directory and adding the global tag name according to the global tag specified in the pset config and the file naming convention.

**Comment by ggovi** [comment]
Single or multiple files to support more GTs depends on the file size. We need to make an export to measure it. If this turns to be the limiting factor, we should go for a new export solution where payloads are dumped on individual files. But this requires some additional ( probably affordable ) development.

**Comment by makortel** [comment]
Based on the comments, how about
* extend the `<site><calib-data>` element of the `site-local-config.xml` to allow to contain either a `<frontier-connect>` or a `<local-connect>` element
  * since we are not looking for actual fallback (on the contrary), I would not allow for fallback here (for now, at least)
* for `<frontier-connect>` element nothing changes
* the `<local-connect>` element would in some way contain a path to directory with the files for the GlobalTags
   * files would have the GlobalTag in their name, maybe simply `<GlobalTag>.db`, e.g. `112X_mc2017_realistic_v2.db`
      * file not found would be an error
   * in this case the `process.GlobalTag.connect` would be ignored

?

Just to think out loud, the `<local-connect>` could be something along
```xml
<site>
 <calib-data>

  <local-connect path="/path/to/dir"/>

  <!-- or -->
  <local-connect>
   <directory path="/path/to/dir"/>
  </local-connect>
 
  <!-- or allowing fallback directories -->
  <local-connect>
   <directory path="/path/to/dir"/>
   <directory path="/path/to/another/dir"/>
  </local-connect>

 </calib-data>
</site>
```

I also wonder the purpose of `<catalog>` element under `<calib-data>`. I don't see it being used (at least by `SiteLocalConfigService`).

**Comment by wddgit** [comment]
Here is my proposal. I could easily implement code for this behavior, but I am not sure if this is exactly the behavior that is needed. Please let me know. I am happy to change it. I think this is following what was discussed above.

Add to the SiteLocalConfigService the ability to read the following from the xml file.

```
...
<site name="SOMESITENAME">
   ...
   <calib-data>
     ...
     <local-connect>
       <connectString prefix="anything"/>
     </local-connect>
...
```

Also give the service the ability to override the prefix from the service configuration for testing purposes

Add a configuration parameter "localConnectSuffix" to CondDBESSource and also have CondDBESSource use the SiteLocalConfigService.

If the prefix from SiteLocalConfig does not exist or is empty, then we do exactly what was done before. There is no change in the behavior of existing processes.

If the prefix from SiteLocalConfig exists and is not empty, then

1. We throw if the global tag from the configuration does not exist or is empty
2. We throw if the localConnectSuffix from the configuration does not exist or is empty 
3. We concatenate the prefix, the global tag, and the localConnectSuffix. This new string is used in place of the connect string in the configuration.

I used the names "prefix" and "localConnectSuffix" to give flexibility. Anything can be in those strings. I would prefer
```
<directory path="/path/to/dir"/>
```
if we are sure that it will always be a path to a directory. Are we sure of that? If something else might be in that string then it would be better to have a more general name. From the discussion, it seems the global tag needs to be in the final connection string.

Let me know if there are comments. Should I go ahead and implement this?

**Comment by makortel** [comment]
> I used the names "prefix" and "localConnectSuffix" to give flexibility ... if we are sure that it will always be a path to a directory. Are we sure of that?

This is a good point that in principle the local connection string could be made allowed to point to anything the `PoolDBESSource.connect` accepts by providing hooks for prefix and suffix around the GlobalTag name. That would be more general than fixating to files in a dictionary without much additional work.

> Also give the service the ability to override the prefix from the service configuration for testing purposes

It is possible to override the whole XML file for testing purposes, would that be sufficient?

> Add a configuration parameter "localConnectSuffix" to CondDBESSource

What would be the benefit for specifying a suffix in the configuration? I can see it being useful to be specified in the site local config so that the site could have control of that as well.

> From the discussion, it seems the global tag needs to be in the final connection string.

For the local connection, yes, that seems to be the way to go.

**Comment by wddgit** [comment]
Any other comments before I implement this and submit a PR? @ggovi @hernand 

Putting the suffix in the site local configuration sounds good to me. So we go with this:
```
...
<site name="SOMESITENAME">
   ...
   <calib-data>
     ...
     <local-connect>
       <connectString prefix="anything1"/>
       <connectString suffix="anything2"/>
     </local-connect>
...
```
Then we make the connect string by concatenating "prefix" + "global tag" + "suffix".

It is true you can already override the whole XML for testing purposes.  Many of the other individual values available from the service also allow overriding individual values without a full XML file for testing. For example,

https://cmssdt.cern.ch/lxr/source/FWCore/Services/src/SiteLocalConfigService.cc#0446

I don't feel strongly about it, but it seems like it would be a little more convenient than making up an entire XML file to run a test.

**Comment by makortel** [comment]
I would combine the `prefix` and `suffix` attributes into a single element along
```xml
<local-connect>
  <connectString prefix="anything1" suffix="anything2"/>
</local-connect>
```
I think it would be clearer this way that they both are applied on the same connection, and the syntax could be easily extended to multiple fallback connections if such behavior will ever be really needed.

> It is true you can already override the whole XML for testing purposes. Many of the other individual values available from the service also allow overriding individual values without a full XML file for testing.

Right. I would be fine with adding similar parameters in `SiteLocalConfigService` for test overrides. But I would not add such override parameters to `CondDBESSource` (maybe I misunderstood earlier).

**Comment by wddgit** [comment]
A single element sounds better. I agree. 

I agree about the parameter also.

**Comment by hernand** [comment]
What is the purpose of the suffix parameter? I understand that the prefix specifies the local location of the conditions files and the connect string will be built concatenating the prefix with the specific conditions file name, which must be related through a naming convention with the global tag, but I fail to see the role of the suffix

**Comment by wddgit** [comment]
What is the naming convention? If you are 100% positive that the part of the connection string after the global tag is nothing or always the same, then the suffix is not needed. The proposed solution would give flexibility for it to be different at different sites or time periods. And we would also need to know what the suffix is now.

**Comment by hernand** [comment]
There is no naming convention yet, we have to establish one. I guess the simplest would probably be <GlobalTag>.db 
There should probably be a parameter in the pset to specify/override the conditions file name anyway.
Concerning the suffix, not sure if it is useful. The flexibility that it could introduce I guess could also be achieved by changing the prefix.

**Comment by wddgit** [comment]
We could hardcode ".db". I was just assuming that in the future it will be easier to make a change to the site local config XML file than to make a change in the software repository through the pull request process and wait for a new release. What if 2 years from now we stop using sqlite files where ".db" is reasonable and start using some other database type where the convention is that the file name ends with something different? I don't have strong feelings on this either way. @ggovi @makortel What do you think?

Independent of this, there is already a way to change the connect string of CondDBESSource in its configuration and also the site local config service would have a way to override the prefix and suffix in its configuration. But that is a different subject. What we are trying to develop is a way to select a local connection without affecting the configuration hash, because changing the hash has consequences we need to avoid.

**Comment by makortel** [comment]
> We could hardcode ".db". I was just assuming that in the future it will be easier to make a change to the site local config XML file than to make a change in the software repository through the pull request process and wait for a new release. What if 2 years from now we stop using sqlite files where ".db" is reasonable and start using some other database type where the convention is that the file name ends with something different? I don't have strong feelings on this either way. @ggovi @makortel What do you think?

I'd slightly prefer a general suffix in the XML. In the end it is arbitrary for CMSSW. I could also imagine a site using the GlobalTag as a directory name, and having a file there (that would be the same for all GTs).

**Comment by wddgit** [comment]
I am going to press forward and implement this today. I will include the suffix. It is easy to include it and the flexibility it adds might be useful. I will submit a PR as soon as it is ready. Let me know if there are objections and you want me to stop or do something different than discussed above...

**Comment by wddgit** [comment]
PR #31544 implements the solution we discussed here. We can close this now.

**Comment by tvami** [comment]
+db

 * https://github.com/cms-sw/cmssw/pull/31544 took care of this

**Comment by tvami** [comment]
@makortel can you please sign this for `core` so the issue can be closed?

**Comment by makortel** [comment]
+core
