### ISSUE TITLE
switch on bad HCAL PF recovery by default (pf_badHcalMitigation)

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#30426]
pf_badHcalMitigation is used in 2018 data processing, added manually https://twiki.cern.ch/twiki/bin/view/CMS/PdmVDataReprocessingUL2018

At least via 2018, it was also validated to be OK for physics.
There was some discussion (and tentative agreement?) to use badHcalMitigation by default.

I propose to enable this globally and swap pf_badHcalMitigation with pf_badHcalMitigationOff.
However, there may be reasons for a more targeted update (e.g. not touch the default Run1) for some strong good reasons.

@hatakeyamak @bendavid 
it would be nice for the PF group to prepare this update (if agreed to be done).

**Comment by slava77** [comment]
assign reconstruction

**Comment by hatakeyamak** [comment]
Thx. Plan to introduce pf_badHcalMitigationOff as soon as we get a chance.

**Comment by slava77** [comment]
> Thx. Plan to introduce pf_badHcalMitigationOff as soon as we get a chance.

@hatakeyamak @bendavid 
please clarify on the status of this

**Comment by laurenhay** [comment]
@slava77
This issue was discussed today and we wanted to see if it would be preferred for this change to be implemented everywhere by default, or from 2018 onward as is done [here](https://github.com/cms-sw/cmssw/blob/e81e9caaa68e4a9c17e05c8af81d8238832d9657/RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHE_cfi.py) for the HBHE modifier.

**Comment by hatakeyamak** [comment]
@slava77 perhaps this is ready to be closed?

**Comment by slava77** [comment]
+reconstruction

**Comment by slava77** [comment]
> @slava77 perhaps this is ready to be closed?

I agree
