### ISSUE TITLE
Exception in workflow 27834.0. HGCalTriggerGeometry: Wafer is not mapped to any trigger module

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#30538]
In workflow `27834.0_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D59_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D59+RecoFullGlobal_2026D59+HARVESTFullGlobal_2026D59`,
we get the following exception since CMSSW_11_2_X_2020-07-03-1200 (see https://github.com/cms-sw/cmssw/pull/30442)
```
----- Begin Fatal Exception 04-Jul-2020 04:36:58 CEST-----------------------
An exception of category 'BadGeometry' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 3
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Prefetching for module HGCalBackendLayer1Producer/'hgcalBackEndLayer1Producer'
   [4] Prefetching for module HGCalConcentratorProducer/'hgcalConcentratorProducer'
   [5] Calling method for module HGCalVFEProducer/'hgcalVFEProducer'
Exception Message:
 EE:HSil= 0:1 type= 2 z= -1 layer= 13 wafer(u,v:x,y)= (0,-9:-9,-18) triggerCell(u,v:x,y)= (1,2:-7,-8)HGCalTriggerGeometry: Wafer (0,-9) is not mapped to any trigger module. The module mapping should be modified. 
----- End Fatal Exception -------------------------------------------------
```
@bsunanda @jbsauvan

**Comment by silviodonato** [comment]
assign geometry

**Comment by silviodonato** [comment]
assign upgrade

**Comment by jbsauvan** [comment]
Originally this exception was put in place because the different HGCAL geometries were completely different between each other and trigger modules and links mappings for one geometry couldn't be used for the other geometries. 

But now that things converge, this exception could be removed. We have mappings for the V11 geometry which can be used at first order for >V11 geometries. So instead of throwing an exception, we could implicitly assume that wafers which are not included in the mappings are disconnected for the trigger.
This would prevent all these HGCAL trigger issues happening each time a tiny change in the geometry is put in place.

If ok for everybody I could PR this change Today.

**Comment by kpedro88** [comment]
@jbsauvan that would certainly make development easier, if it won't cause problems for the trigger. We may want to continue to emit a warning (rather than an exception) to keep track of cases where the map could still be updated.

**Comment by bsunanda** [comment]
I think it is more appropriate to issue warnings rather than exception. HGCal geometry is still on development path. Throwing exception slows down the development process.

**Comment by jbsauvan** [comment]
I have made the change in #30541
