### ISSUE TITLE
TFormula::ReInitializeEvalMethod error in IBs

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#31097]
Two workflows (28234.0 step2 and 23434.999 step3, DIGI in both cases) failed in CMSSW_11_2_X_2020-08-07-1100 with
```
----- Begin Fatal Exception 07-Aug-2020 15:56:43 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 2
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Prefetching for module FastjetJetProducer/'ak4PFL1Calo'
   [4] Prefetching for module L1TPFCandMultiMerger/'l1pfCandidates'
   [5] Prefetching for module L1TPFProducer/'l1pfProducerBarrel'
   [6] Calling method for module L1TkMuonProducer/'L1TkMuons'
   Additional Info:
      [a] Fatal Root Error: @SUB=TFormula::ReInitializeEvalMethod
Formula is NOT properly initialized - try calling again TFormula::PrepareEvalMethod

----- End Fatal Exception -------------------------------------------------
```
Full logs
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-08-07-1100/pyRelValMatrixLogs/run/28234.0_TTbar_14TeV+2026D60+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step2_TTbar_14TeV+2026D60+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-08-07-1100/pyRelValMatrixLogs/run/23434.999_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step3_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU.log#/

**Comment by makortel** [comment]
I'm not able to reproduce locally (28234.0) on either single or with 4 threads. Maybe a threading problem related to use of TFormula somewhere?

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
The `L1TkMuonProducer` opens bunch of `TFile`'s, e.g.
https://github.com/cms-sw/cmssw/blob/c21aee5ddc74bc22d8fc50b09db71a9e8cb690bc/L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc#L256-L259
that read `TF1` objects from the file
https://github.com/cms-sw/cmssw/blob/c21aee5ddc74bc22d8fc50b09db71a9e8cb690bc/L1Trigger/L1TTrackMatch/src/L1TkMuMantra.cc#L40-L42
and passed on
https://github.com/cms-sw/cmssw/blob/c21aee5ddc74bc22d8fc50b09db71a9e8cb690bc/L1Trigger/L1TTrackMatch/src/L1TkMuMantra.cc#L53-L55
where they are cloned
https://github.com/cms-sw/cmssw/blob/c21aee5ddc74bc22d8fc50b09db71a9e8cb690bc/L1Trigger/L1TTrackMatch/src/MuMatchWindow.cc#L24-L28
before being evaluated in
https://github.com/cms-sw/cmssw/blob/c21aee5ddc74bc22d8fc50b09db71a9e8cb690bc/L1Trigger/L1TTrackMatch/interface/MuMatchWindow.h#L33-L35

Notably the `L1TkMuonProducer` is a global 
https://github.com/cms-sw/cmssw/blob/c21aee5ddc74bc22d8fc50b09db71a9e8cb690bc/L1Trigger/L1TTrackMatch/plugins/L1TkMuonProducer.cc#L45

so these cloned `TF1` objects are potentially called concurrently (not sure if that itself is a problem or not).

**Comment by makortel** [comment]
assign l1, upgrade

**Comment by makortel** [comment]
At the very least the functions in `L1TkMuMantra` and `L1TkMuCorrDynamicWindows` that are called from `L1TkMuonProducer` should be made `const`. Currently they are not, and `L1TkMuonProducer` holds the objects by (unique) pointer, so we are not able to catch any potential calls to non-`const` non-thread safe functions.

Alternatively `L1TkMuonProducer` could be changed to `edm::stream`.

**Comment by makortel** [comment]
This problem had occurred also in
* CMSSW_11_2_X_2020-08-04-1100 in 28234.0 step2
* CMSSW_11_2_X_2020-08-05-1100 in 23434.999 step3

**Comment by makortel** [comment]
I suspect it started with #30970 in CMSSW_11_2_X_2020-08-03-1100 that changed `L1TkMuonProducer` from legacy to `edm::global`. (@kpedro88)

**Comment by kpedro88** [comment]
@makortel indeed, probably changing to `edm::stream` is the simplest solution, as long as the memory usage stays under control. I'll test this now.

**Comment by kpedro88** [comment]
From 10 events of step2 in 28234.0 on 4 threads, I get:
global: MemoryCheck: event : VSIZE 7348.32 0 RSS 4458.36 0
stream: MemoryCheck: event : VSIZE 7860.31 0 RSS 4387.64 0

This looks acceptable, so I'll submit the PR.

**Comment by kpedro88** [comment]
see #31098 and backport #31099

**Comment by dan131riley** [comment]
A TFormula read from a file is lazily recompiled on the first evaluation, and the lazy recompilation isn't sufficiently thread safe for a function that is evaluated in parallel on multiple threads.  The advice to "try calling again TFormula::PrepareEvalMethod" isn't terribly useful since that method is private.  I suppose we could trigger compilation via a gratuitous evaluation in the constructor, but that's ugly.  (The message is just a warning, but by default we elevate warnings to exceptions.)

https://github.com/root-project/root/blob/084292ab638923f9260d3a9f813227ada0728565/hist/hist/src/TFormula.cxx#L3442-L3466

-dan (reading TFormula for the other issue)

**Comment by dan131riley** [comment]
Nope, looks like I’m wrong, the caller always has the gROOT mutex.   Fooled by recursive mutexes again...

**Comment by kpedro88** [comment]
Thanks for the info. It looks like changing to a stream producer has resolved the problem.

If the functions used are simple enough, it might be worth changing to the CMSSW stateless FormulaEvaluator (as a future development item). @rekovic

**Comment by dan131riley** [comment]
Ok this time for sure, there is a race condition here:

https://github.com/root-project/root/blob/084292ab638923f9260d3a9f813227ada0728565/hist/hist/src/TFormula.cxx#L3347

fLazyInitialization can be cleared by one thread while another is waiting on the mutex, and there’s no recheck on acquiring the mutex.  Also need to make the flags atomic for a safe recheck.  Probably worth making a bug report, and auditing the rest for missing atomic issues on architectures with weaker ordering guarantees than amd64.

Making it a stream producer should fix it, since then the threads aren’t sharing a single instance.

Sorry about spamming.

**Comment by kpedro88** [comment]
+upgrade

**Comment by makortel** [comment]
+1
