### ISSUE TITLE
Unit test failure FWCore/Services TestFWCoreServicesDriver - ARM IB

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#31236]
There is a repetative unite test failure in:
TestFWCoreServicesDriver
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_aarch64_gcc820/CMSSW_11_2_X_2020-08-24-2300/unitTestLogs/FWCore/Services#/87-87
with exception:

```
dropped waiting message count 0
Running script: /build/cmsbld/jenkins_c/workspace/ib-run-qa/CMSSW_11_2_X_2020-08-24-2300/src/FWCore/Services/test/test_resource.sh
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 25-Aug-2020 05:32:32.046 CEST
----- Begin Fatal Exception 25-Aug-2020 05:32:32 CEST-----------------------
An exception of category 'ExceededResourceVSize' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
Exception Message:
Exceeded maximum allowed VSize of 1 GB (VSize is 1.27294)
----- End Fatal Exception -------------------------------------------------
```

the first hit when I started checking out what is it was this one:
https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel
suggesting we might need to adjust docker/singularity TaskMax differently

**Comment by Dr15Jones** [comment]
That unit test is testing the Service that aborts if the job takes too much memory. In this case, it is supposed to succeed since it was guessed that 1GB of VSize would be sufficient to run that simple job. For ARM, that is not the case (which is kind of sad). We can get the test to work by moving the max size to be 1.5 for the test. [Although it still would be nice to find out why ARM is requiring so much more virtual memory]

**Comment by makortel** [comment]
assign core

**Comment by mrodozov** [comment]
I suggest I close this and keep #31306
