### ISSUE TITLE
[DD4hep][Simulation] Ecal EE Sim Hits appear in two out of four quarters

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31637]
`cmsRun $CMSSW_RELEASE_BASE/src/SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
`
produces a non-empty file, but the EE (in pink) simhits appear only in two out of four quarters. Are the EB Sim Hits missing? 

Tested with todays IB and #31573
<img width="1454" alt="Screenshot 2020-10-01 at 07 49 31" src="https://user-images.githubusercontent.com/1390682/94774882-0441f380-03bf-11eb-8a42-7ee2d1cd0558.png">

**Comment by makortel** [comment]
assign geometry, simulation

**Comment by cvuosalo** [comment]
@bsunanda @rchatter Could you please look at this issue?

**Comment by rchatter** [comment]
Hi Carl,
Thanks for point us to it. Will look into it and get back.

Rajdeep

**Comment by cvuosalo** [comment]
Watch out! Re-compiled version of code with debugging for `SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py` crashes. There is probably a buggy debug statement somewhere in `SimG4CMS/Calo/src/CaloHitID.cc`. I haven't found the bad statement yet. I am trying to trace the EE hits to see why half are missing.

**Comment by rchatter** [comment]
I run without debugging for now. It seems the ES in DD4HEP is almost entirely missing hits but for a couple of strips for Z+ 
I could modify this ZMM Sim to do what I wanted. Running on vanilla e/G particle guns. Will report what I find.

**Comment by rchatter** [comment]
Hi,

I confirmed with a high stats e- particle gun simulation. The observation remains the same of the EE, the same 2 quadrants as report earlier are missing. The new observation is the ES- is missing all hits. In ES+ only 2 strips have hits, everything else is missing. The ES+ hits that are present [in cartesian x,y co-ordinates] is attached. The cause is being checked if its related to the numbering scheme.

Thanks,
Rajdeep
![ES_Plus](https://user-images.githubusercontent.com/6048708/96499651-fc52d200-124d-11eb-843a-499490218afa.png)

**Comment by ianna** [comment]
progress on this issue is discussed here https://github.com/AIDASoft/DD4hep/issues/534

**Comment by ianna** [comment]
+1
