### ISSUE TITLE
[Geometry][MTD][RECO] GeometricTimingDetExtra should be removed

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31822]
@fabiocos - Please, consider removing `GeometricTimingDetExtra` if it is not used. Given that `GeometricTimingDetExtra` is a copy of a legacy `GeometricDetExtra` an assumption is that it may follow the same path. The latter is addressed here https://github.com/cms-sw/cmssw/pull/31729

**Comment by makortel** [comment]
assign geometry

**Comment by fabiocos** [comment]
@ianna @makortel ```GeometricTimingDetExtra``` has gone since a while with #30276 , as you may see in the repository.
The only remnant is ```PGeometricTimingDetExtra``` in the records area which I think might go without any problem, could @christopheralanwest please confirm? If yes, I may just prepare a PR removing all the code related to this, not much as can be seen in https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_2_X_2020-10-18-2300&_filestring=&_string=PGeometricTimingDetExtra

**Comment by christopheralanwest** [comment]
There are no payloads with record type `PGeometricTimingDetExtra` in the DB: https://cms-conddb.cern.ch/cmsDbBrowser/search/Prod/PGeometricTimingDetExtra

so I think this removal should not cause any issues.

**Comment by ianna** [comment]
+1

Done in https://github.com/cms-sw/cmssw/pull/31875
Thanks @fabiocos !
