### ISSUE TITLE
GPU test does not seem to run in the bot

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#31878]
In the PR https://github.com/cms-sw/cmssw/pull/31704 I tried to run a basic unit test on the GPU using "please test". However,  despite saying "enable gpu" and the test running with "ENABLE_BOT_TESTS = GPU", the test [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bad05c/10144/unitTests.log) shows that CUDA was not properly initialized.

I had the same error locally before updating the nvidia driver to the latest 455 version - possibly it's the same problem on the test infrastructure, but I was not able to check.

```
===== Test "test_calo_rechit" ====
Failed to initialise the CUDA runtime, the test will be skipped.
```

cc heterogeneous @fwyzard

**Comment by jpata** [comment]
assign core

**Comment by smuzaffar** [comment]
for GPU enabled tested, bot runs two tests
- Normal PR validation tests
- GPU based tests
For #31704 bot ran the normal tests but due to a typo in bot did not start the GPU based test. Anyway, this is fixed and there is pending job in jenkins for GPU tests https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/ . Whenever we get hold to a HTCondor GPU resources then the test will start

**Comment by jpata** [comment]
Thanks @smuzaffar for the clarification. So in principle the procedure we followed in #31704 should work to also successfully run the CUDA-based tests that run when doing `scram b runtests`?

**Comment by smuzaffar** [comment]
bot currently only running GPU based relvals for PRs, In future I will also enable running of unit tests too

**Comment by makortel** [comment]
Can this issue be closed?

**Comment by jpata** [comment]
yes, seems so, thanks.
