### ISSUE TITLE
How to migrate OscarMTProducer to EventSetup consumes?

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32011]
@bsunanda brought up a question that how a code implementing `SimProducer` or `SimWatcher` that uses `BeginOfJob` signal should be migrated to declare EventSetup product consumption (https://github.com/cms-sw/cmssw/issues/31061).

The difficulty is that `BeginOfJob` signal delivers `edm::EventSetup`
https://github.com/cms-sw/cmssw/blob/59d2873fdd664e57dfe67fc113ed826a08198e14/SimG4Core/Notification/interface/BeginOfJob.h#L8-L15
and that the `esConsumes()` call [has to declare the transition where the EventSetup product is consumed (e.g. event or beginRun)](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module)

The `BeginOfJob` signal is emitted at `RunManagerMTWorker::initializeG4()`
https://github.com/cms-sw/cmssw/blob/59d2873fdd664e57dfe67fc113ed826a08198e14/SimG4Core/Application/src/RunManagerMTWorker.cc#L351-L353
which can be called at beginRun transition from
https://github.com/cms-sw/cmssw/blob/59d2873fdd664e57dfe67fc113ed826a08198e14/SimG4Core/Application/plugins/OscarMTProducer.cc#L169-L173
and at event transition from
https://github.com/cms-sw/cmssw/blob/59d2873fdd664e57dfe67fc113ed826a08198e14/SimG4Core/Application/src/RunManagerMTWorker.cc#L477-L483

Therefore, at present, the code listening `BeginOfJob` signals does not know whether the call would come from beginRun transition or from event transition, and can not declare the consumption for proper transition in the `OscarMTProducer` constructor.

How should the `OscarMTProducer` infrastructure be evolved to accommodate the EventSetup product consumption declarations?

**Comment by makortel** [comment]
assign core, simulation

**Comment by makortel** [comment]
Note that before https://github.com/cms-sw/cmssw/pull/31022 there was no ambiguity, all calls came at event transition.

**Comment by makortel** [comment]
On a related note, can `OscarProducer` be removed now (to avoid migrating all that to EventSetup consumes)?

**Comment by civanch** [comment]
@makortel , in Geant4 10.7 a new feature will be available allowing to choose type of threading. I would reconsider how Geant4 is instantiated and initialized after migration to 10.7. At that moment OscarProducer may be dropped, because multi-threading method (or its absence) can be defined in one producer.

Concerning initialization of Geant4: may be #31022 make what we want not in the best way and can be revised. However, with this modification we really move most part of initialization out of the event loop, what was the goal. In ordinary runs with few threads it is working fine but in the HPC run there were warnings, which we discussed some time ago indicating that a small part of initialization is made in the first event of a thread. Probably, there is better solution and this place may be improved.

Concerning SimWatchers: in my understanding, this approach is useful for temporary study what happens at the event loop without breaking mainstream simulation production. Because of that, SimWatchers were created at different time and after use were not supported anymore. Once I tried to clean up these codes but it is time consuming and seems not very useful, because in the old code author did not assume existence of multi threading, very often it is full of histograms and n-tuples. We indeed should provide SimWatcher functionality but fixing old watchers seems to be not the best place to put efforts, at least, now.

**Comment by bsunanda** [comment]
I do not agree with what Vladimir says about SimWatchers or SimProducers. They are really useful to validate simulation when any new detector is introduced. SimWatcher/SimProducer class was created by Chris Jones from the beginning of CMSSW. It is still heavily used in material budget studies.
________________________________

**Comment by makortel** [comment]
@civanch From the timeline you presented in the O&C week (10.7 release in Dec 2020, integration in CMSSW by March 2021) postponing the `esConsumes()` to 10.7 sounds feasible. Is there already any documentation about the possible choices of threading types?

About SimWatchers and SimProducers, unfortunately they all need to be migrated to `esConsumes()` (or left into a non-functional state in which case it would be clearer to just remove them), because the framework will eventually (and rather sooner than later) require all EventSetup accesses to be declared in the EDModule constructor (just like all consumed ED product need to be declared).

**Comment by makortel** [comment]
Just to record here what I understood from @civanch in the simulation meeting today. Apparently Geant4 10.7 does not bring substantial reduction in the use of thread-local storage, and therefore to leading order the EventSetup consumes needs to be implemented in the current initialization structure.

**Comment by makortel** [comment]
I had a thought that maybe we could just read all the ESProducts at the beginRun time and store pointers to them in member data (not my favorite pattern, but in principle should work and the code pretty much already assumes EventSetup changes at most Run boundaries).

That would require moving the `SimActivityRegistry` and the `SimWatcher`s and `SimProducer`s out from the thread-local storage
https://github.com/cms-sw/cmssw/blob/9f1ac7769abc67682da1ec99b0b13c3b83a57d2f/SimG4Core/Application/src/RunManagerMTWorker.cc#L117-L126
into per-EDM-stream storage as `RunManagerMTWorker` member data (which would also enable natural way to pass `ConsumesCollector` to the constructors of `SimWatcher`s and `SimProducer`s9.

But then I read the  user action registration functio that connects these to Geant4
https://github.com/cms-sw/cmssw/blob/9f1ac7769abc67682da1ec99b0b13c3b83a57d2f/SimG4Core/Application/src/RunManagerMTWorker.cc#L380-L404
In a naive approach that function would connect per-stream objects to per-thread objects in Geant4 (`eventManager`), which would not work properly.

I believe it could still be made to work with additional layer of indirection. Perhaps we could even use the `RunAction` etc directly by changing the signal members
https://github.com/cms-sw/cmssw/blob/9f1ac7769abc67682da1ec99b0b13c3b83a57d2f/SimG4Core/Application/interface/RunAction.h#L23-L24
to be pointers, and instead of using `connect()`
https://github.com/cms-sw/cmssw/blob/9f1ac7769abc67682da1ec99b0b13c3b83a57d2f/SimG4Core/Application/src/RunManagerMTWorker.cc#L406-L409
to connect the signals, set the pointers along
```cpp
runAction->m_beginOfRunSignal = &m_registry->beginOfRunSignal_;
runAction->m_endOfRunSignal = &m_registry->endOfRunSignal_;
```
and re-set all these pointers at the beginning of `produce()`.

**Comment by makortel** [comment]
Addressed in https://github.com/cms-sw/cmssw/pull/34031

**Comment by makortel** [comment]
+core
