### ISSUE TITLE
update mkedprod and co with newer fillDescriptions

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#32282]
Currently, mkedprod & co generate a skeleton which uses `descriptions.addDefault(desc);` and thus does not generate the cfi files. 

We had some confusion on the PR https://github.com/cms-sw/cmssw/pull/32222/files/b91d4a5dba8db0c252d8093a7c7c9cc84716138f#r530326611 that the template does not allow auto-generation of the cfi, which I understand is the current suggestion.

Perhaps it's a good occasion to update the template to use `addWithDefaultLabel` to make sure that people start with a good baseline for their new modules?

**Comment by jpata** [comment]
@fwyzard asked me to mention `edmPythonConfigToCppValidation` (I'm not familiar with that tool)

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
> edmPythonConfigToCppValidation

The case of `edmPythonConfigToCppValidation` looks a bit different than the skeletons because it generates code with `add()`, which results a generated `cfi` fragment. The script takes the label for `descriptions.add()` from the module label in the input `cfi` configuration file. If that label does not correspond the automatic one, the generated code would lead to generation of different `cfi` fragment than the original input that would not be a drop-in replacement of the original input. Detecting if the label corresponds the automatic one would also require implementing the logic in python.

Written that, I could add an option for the script to use `addWithDefaultLabel()` instead of `add()` so a user could decide, or generate it anyway in comments (which could be easier for a user to discover than command line arguments)

**Comment by makortel** [comment]
Addressed in https://github.com/cms-sw/cmssw/pull/32287 with the "generate it anyway in comments" approach for `edmPythonConfigToCppValidation`.
