### ISSUE TITLE
Fake differences in wf 11642.911

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32283]
Many PR tests are reporting fake differences in the new DD4HEP wf 11642.911.

See
https://github.com/cms-sw/cmssw/pull/32278#issuecomment-733696764
https://github.com/cms-sw/cmssw/pull/32263#issuecomment-733688052
https://github.com/cms-sw/cmssw/pull/32279#issuecomment-733689619
https://github.com/cms-sw/cmssw/pull/32276#issuecomment-733653227
https://github.com/cms-sw/cmssw/pull/32093#issuecomment-733667578
https://github.com/cms-sw/cmssw/pull/32272#issuecomment-733527632
https://github.com/cms-sw/cmssw/pull/32273#issuecomment-733532076
https://github.com/cms-sw/cmssw/pull/32270#issuecomment-733525691

For instance in https://github.com/cms-sw/cmssw/pull/32258
we ran two times the same PR (commit 71e9ea9cd53937f356d6ee852926a801d063f760) in the same release (`CMSSW_11_2_X_2020-11-24-1100`). The result was different

> Reco comparison results: 2325 differences found in the comparisons

and then

> Reco comparison results: 7 differences found in the comparisons

**Comment by silviodonato** [comment]
assign geometry

**Comment by silviodonato** [comment]
The PR #32096 added both `11642.911` and `11624.911` in the short matrix. If we continue to see these fake difference, I would remove `11642.911` from the short matrix (ie. DD4HEP remains in the short matrix with `11624.911`;  `11642.911` will be only in the extended matrix)

**Comment by bsunanda** [comment]
@silviodonato Any difference in dd4hep workflow should be ignored as of now. Once dd4hep workflows are studied in detail differences in those workflows should be taken seriously.

**Comment by civanch** [comment]
@silviodonato , @bsunanda , we can expect, that after some time differences in these WFs will be meaningful but it is not the case now. Even more differences indicate, that PR is working. 
Because the difference is should happens only in PRs, which relevant to geometry, I would think we may work in these circumstances for some time.

**Comment by mmusich** [comment]
same thing observed in https://github.com/cms-sw/cmssw/pull/32280#issuecomment-733799058 and that has nothing to do with Geometry.

**Comment by cvuosalo** [comment]
Why is workflow 11642.911 creating differences but 11624.911 does not? They seem to be basically the same, 11624 is ttbar and 11642 is zmm, but otherwise they both perform gen-sim. They should always use the same random seed to give the same events, unless the geometry is changed in the PR. I don't understand why 11642 is generating new events every time it is run in a PR test even when the geometry does not change.

**Comment by makortel** [comment]
I suspect we're witnessing a memory problem of some kind (in addition to the threading problem, or perhaps the problem is the same and threading just makes it worse).

**Comment by cvuosalo** [comment]
@makortel I thought the PR tests run single-threaded.

**Comment by makortel** [comment]
They are, but memory problems can nevertheless show up as random failures or differences.

**Comment by silviodonato** [comment]
Workflow removed (#32288). We will try again once #32249 is solved
