### ISSUE TITLE
Towards CMSSW_11_2_0 - No Phase-2 electrons in endcap in miniAOD 

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32475]
Part of #32465

From https://hypernews.cern.ch/HyperNews/CMS/get/relval/15280/13.html

> Release: 11_2_0_PRE10_PHASE2
In category: RECONSTRUCTION
In subcategory: FULLSIM
validation for: ELECTRON
Has Changed: From status: NOT YET DONE
             To status: OK
By: AXEL NEWTON BUCHOT PERRAGUIN
Comment: The 11_2_0_pre10_PHASE2 (red) plots are compared to 11_2_0_pre9_PHASE2 (blue) [0].

> Summary: Perfect agreement in RECO and PU25 but problem identified in miniAOD.

> Comments: Perfect agreement between both versions [0] with and withou pile-up.

> MiniAOD [1]: Endcaps are not taken into account in the miniAOD [1]. The problem has been there since the beginning. The MiniAOD are not made from the HGCAL electron collection but from the standard one. As a result, they do not contain the endcap electrons [2] (miniAOD in blue).
Links: [0] https://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Releases/index.php?action=/11_2_0_pre10_PHASE2_DQM_std/FullvsFull_CMSSW_11_2_0_pre9
[1] https://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Releases/index.php?action=/11_2_0_pre10_PHASE2_DQM_std/FullvsFull_CMSSW_11_2_0_pre10
[2] https://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Releases/11_2_0_pre10_PHASE2_DQM_std/FullvsFull_CMSSW_11_2_0_pre10/RECO-miniAOD_ZEE_14/gifs/h_ele_PoPtrueVsEta_pfx.gif

Red: RECO, Blue: MiniAOD
![image](https://user-images.githubusercontent.com/6177433/102094619-d0edfd00-3e22-11eb-8003-6124852eec7f.png)

**Comment by silviodonato** [comment]
assign xpog

**Comment by mariadalfonso** [comment]
@rovere

**Comment by chayanit** [comment]
@silviodonato can you also assign PdmV in this opened issue? thanks :)

**Comment by silviodonato** [comment]
assign pdmv

**Comment by qliphy** [comment]
assign upgrade

**Comment by hatakeyamak** [comment]
Not really PF issues, but @bendavid @hatakeyamak should probably keep eyes on this.

**Comment by SohamBhattacharya** [comment]
@silviodonato Probably I missed this, but can you please let me know what are the collections from MINIAOD you're using to compare?

**Comment by silviodonato** [comment]
@gouskos looked on this recently. It seems that `patElectrons_slimmedElectronsFromMultiCl__RECO` is filled properly in MiniAOD (eg. see `/eos/cms/store/relval/CMSSW_11_2_0_pre10/RelValZEE_14/MINIAODSIM/PU25ns_112X_mcRun4_realistic_v4_2026D49PU200-v1/00000/1834eb8f-0045-4083-ba9c-01dfb6ee395f.root`).
The point is that only `patElectrons_slimmedElectrons__RECO` are used to fill the plot.
I don't know if @cms-sw/upgrade-l2 and EGM POG (@cms-sw/reconstruction-l2) wants to merge `patElectrons_slimmedElectronsFromMultiCl__RECO` in `patElectrons_slimmedElectrons__RECO` or keep them separated.

**Comment by kpedro88** [comment]
I think this is related to #32766 (and might become superfluous once that is merged)

**Comment by SohamBhattacharya** [comment]
@silviodonato @kpedro88 The `slimmedElectrons` collection is not fed by the endcap (HGCal) electrons. There's this collection called `slimmedElectronsFromMultiCl` which is built from the HGCal electrons (`ecalDrivenGsfElectronsFromMultiCl`).
As for #32766, I'm likely missing something, but it's not entirely clear to me from the files changed by this PR how the HGCal electrons (`ecalDrivenGsfElectronsFromMultiCl`) will be plugged into the `slimmedElectrons` collection.

**Comment by kpedro88** [comment]
@SohamBhattacharya right now, all of the `FromMultiCl` collections constitute a "parallel universe" of HGCal reconstruction, starting from `particleFlowClusterHGCalFromMultiCl`. #32766 makes TICL the default reconstruction for HGCal. Once this is complete, the `FromMultiCl` collections will be redundant: the "real" reconstruction will be used everywhere.

**Comment by SohamBhattacharya** [comment]
> @SohamBhattacharya right now, all of the `FromMultiCl` collections constitute a "parallel universe" of HGCal reconstruction, starting from `particleFlowClusterHGCalFromMultiCl`. #32766 makes TICL the default reconstruction for HGCal. Once this is complete, the `FromMultiCl` collections will be redundant: the "real" reconstruction will be used everywhere.

I see, thank you.

**Comment by hatakeyamak** [comment]
@SohamBhattacharya @kpedro88 @rovere @felicepantaleo 
This is slightly deviating from the original github issue topic, but since this was also discussed during #32766 I looked into what we can possibly do to clean up at least some of `FromMultiCl` processes.

As @kpedro88 indicated, starting from `particleFlowClusterHGCal`, it looks to me, there are `non-FromMultiCl` and `FromMultiCl` parallel sequences, where the former uses `mix:MergedCaloTruth` and the latter uses `ticlMultiClustersFromTrackstersMerge/ticlTrackstersMerge`. Is this intended (in other words, do egamma still uses the `non-FromMultiCl` one starting from `mix:MergedCaloTruth`)? or do we now focus on the latter? If the latter is the case, I think a certain `FromMultiCl` can be cleaned up. I think it's difficult to get rid of all `FromMultiCl` completely, because for barrel electrons & photons, we use the PFEGamma path, which doesn't work for hgcal electrons & photons at a moment, and for electrons there are additional complications (use of different gsElectron collections etc).

https://github.com/hatakeyamak/cmssw/pull/new/CleanupFromMultiCl
is my trial branch. This works only if we remove dqm/validation sequences, so in order to make this as a real PR, additional work is necessary, but I thought this could be still helpful to show what I am talking about.

With this, at the RECO level, I think we can get rid of
```
vector<reco::Photon>                  "photonsFromMultiCl"        ""                "RECO"
```
and can use
```
vector<reco::Photon>                  "photons"                   ""                "RECO" 
```
even for HGCAL photons. For electron related, I think many `FromMultiCl` can be cleaned up, but for cleaning up,
```
vector<reco::GsfElectron>             "ecalDrivenGsfElectronsFromMultiCl"   ""                "RECO"
vector<reco::GsfElectronCore>         "ecalDrivenGsfElectronCoresFromMultiCl"   ""                "RECO"
```
we will need to validate that `pfTrackElec` works for HGCAL electrons, and `GsfElectronProducer` will need some adjustments, so I kept them for now.

For theMINIAOD level, we use
```
vector<reco::Photon>                  "gedPhotons"                ""                "RECO" 
vector<reco::GsfElectron>             "gedGsfElectrons"           ""                "RECO"
```
for barrel photons and electrons, while we still need to use
```
vector<reco::Photon>                  "photons"                   ""                "RECO" 
vector<reco::GsfElectron>             "ecalDrivenGsfElectronsFromMultiCl"   ""                "RECO"
```
for hgcal electrons/photons, so keeping two collections separate seem reasonable to me, if it's fine for POG/PAG-level studies.

Is my summary above reasonably correct and is the partial cleanup of `FromMultlCi` a good idea? I thought it would help facilitating the integration of the hgcal region reconstruction more consistently, but I wanted to see your feedback.

**Comment by rovere** [comment]
Ciao,
I commented on this topic in July during the HLT Upgrade workshop: [slides in back-up](https://indico.cern.ch/event/919645/contributions/3912778/attachments/2061557/3458379/20200622_HLTUpgrade_MR.pdf)

Now that we did make the transition of out `SimAssisted` to `TICL-only`, we could start trimming all the bits and pieces that are not necessary any longer. Thanks a lot, @hatakeyamak for looking into this. Maybe the plots in the backup slides linked above could help to do this trimming.

**Comment by hatakeyamak** [comment]
Thank you @rovere for your feedback and also for a pointer to the slides. So, I think this proposed cleanup is on the right track. I had some exchange with EGM conveners also about this, and I believe they are on the board, but I also want to make sure @SohamBhattacharya is on the same page. I will be happy to help moving this forward, but I will need some help from EGM for making necessary changes for validation code etc.

**Comment by SohamBhattacharya** [comment]
Thank you very much for looking into this, @hatakeyamak.
Starting from `particleFlowClusterHGCal`, we're using `ticlMultiClustersFromTrackstersMerge/ticlTrackstersMerge` for the HGCal e/gamma studies, and not `mix:MergedCaloTruth` anymore.
You mentioned cleaning up the `FromMultiCl` collection for photons and use 
```
vector<reco::Photon>                  "photons"                   ""                "RECO" 
```
for both barrel and HGCal for RECO -- so is this a merged collection? If so, it's not entirely clear to me how we will still have separate collections at MINIAOD -- isn't the MINIAOD `FromMultiCl` collection built from the corresponding RECO `FromMultiCl` collection?
As for the `pfTrackElec`, [1] needs to be turned on -- we'll check if the ambiguity resolution works with that (I had experienced some crashes with that quite a while back, but have to check again).

[1] https://cmssdt.cern.ch/lxr/source/RecoEgamma/EgammaElectronProducers/python/gsfElectrons_cfi.py#0033

**Comment by SohamBhattacharya** [comment]
@hatakeyamak 
Thank you for the clarification. Yes, for photons we can move `photonsFromMultiCl` to the following and remove the `photonsFromMultiCl` collection.
```
vector<reco::Photon>                  "photons"                   ""                "RECO"
```
As for the name, since we're having separate collections for EB and HGCal, I think `HGC` as a suffix is a good option, but I'm open to other opinions/suggestions.

Regarding the electrons, I will get back with some tests with `pfTrackElec`.

**Comment by hatakeyamak** [comment]
@SohamBhattacharya thank you. I think "HGC" suffix is a good one.

**Comment by SohamBhattacharya** [comment]
@hatakeyamak 
Just to confirm, then at the RECO level, the following collections will contain both the EB and HGCal electrons/photons (after the electron `pfTrackElec` issue is solved)?
```
vector<reco::Photon>                  "photons"                   ""                "RECO" 
vector<reco::GsfElectron>             "ecalDrivenGsfElectrons"   ""                "RECO"    
```
If so, can you please point me to where exactly the EB objects will be combined with the `ticlMultiClustersFromTrackstersMerge/ticlTrackstersMerge`-based HGCal objects? It seems to me this will require some more C++ coding, but I might be missing something.

**Comment by hatakeyamak** [comment]
For electrons, I think this happens because of
https://cmssdt.cern.ch/lxr/source/cfipython/RecoEgamma/EgammaElectronProducers/ecalDrivenElectronSeeds_cfi.py#0038
https://cmssdt.cern.ch/lxr/source/RecoEgamma/EgammaElectronProducers/python/ecalDrivenElectronSeeds_cff.py#0019
https://cmssdt.cern.ch/lxr/source/RecoEgamma/EgammaElectronProducers/plugins/ElectronSeedProducer.cc#0251
where both barrel and endcap SC is fed in.

For photons, I think this happens because of:
https://cmssdt.cern.ch/lxr/source/RecoEgamma/EgammaPhotonProducers/python/photonCore_cfi.py
where both barrel and endcap SC is fed in.

BTW: as a side note, it could be worthwhile to note that, even now,
```
vector<reco::Photon>                  "photonsFromMultiCl"                   ""                "RECO" 
vector<reco::GsfElectron>             "ecalDrivenGsfElectronsFromMultiCl"   ""                "RECO"
```
include photon and electron candidates in the barrel region. The barrel ones are vetoed when MINIAOD collections are made:
https://cmssdt.cern.ch/lxr/source/RecoEgamma/EgammaTools/python/slimmedEgammaFromMultiCl_cff.py#0044

**Comment by SohamBhattacharya** [comment]
@hatakeyamak Thanks a lot for the detailed clarification -- it's clear to me now.

**Comment by srimanob** [comment]
@SohamBhattacharya @cms-sw/xpog-l2 

Do you have DQM to monitor endcap electron?
Is everything OK from your side, and this ticket can be closed? Or we should keep it open for some reasons?

Thanks.

**Comment by SohamBhattacharya** [comment]
Hi @srimanob ,
Following the comment [1] with @hatakeyamak, some cleanup of the `FromMultiCl` collections can be done in RECO -- the photon collection can be cleaned now, but the electron collection requires a few checks that we're looking into.
However, as far as MINIAOD is concerned, we came to the conclusion that it's okay for now to have separate collections for barrel and endcap, for the ease of the ongoing POG studies, as the endcap electrons/photons are not ready to be integrated with PFlow yet.
So to summarize, with the cleanup mentioned above, we plan to change the names of the MINIAOD endcap electron/photon collections, but they'll still be separate from the barrel collections (which is currently used in these DQM plots). For monitoring the endcap e/gamma in MINIAOD, one has to add the endcap collections (presently called `slimmedElectronsFromMultiCl` and `slimmedPhotonsFromMultiCl`) to the DQM code.
May be others can comment if this approach is alright.

[1] https://github.com/cms-sw/cmssw/issues/32475#issuecomment-801167501

**Comment by hatakeyamak** [comment]
@SohamBhattacharya @srimanob 
Perhaps I can make a few suggestions.

For the main topic of electron RECO vs MINIAOD slimmed set validation, you probably want to make two separate sets of comparisons

[A] (standard set for barrel that goes through PFEGamma path)
```
RECO: gedGsfElectrons
MINIAOD: slimmedElectrons
```

[B] (the set used for hgcal, though the RECO one may contain electrons in barrel as well, but not the same from PFEGamma path)
```
RECO: ecalDrivenGsfElectronsFromMultiCl 
MINIAOD: slimmedElectronsFromMultiCl
```

In order to accomplish this, I think the egamma validation responsible may tune
[1] https://cmssdt.cern.ch/lxr/source/Validation/RecoEgamma/python/ElectronMcSignalValidator_gedGsfElectrons_cfi.py
[2] https://cmssdt.cern.ch/lxr/source/Validation/RecoEgamma/python/ElectronMcSignalValidatorMiniAOD_cfi.py

For phase 2, clone the module for the 2nd set that includes the electrons in the hgcal region, change the `InputTag` and `OutputFolderName`, run both the original module (aimed for barrel set) and cloned module (aimed for endcap set). Then, probably egamma validation responsibles need to also adjust some script to make plots for e.g. https://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Releases/index.php?action=/11_2_0_pre10_PHASE2_DQM_std/FullvsFull_CMSSW_11_2_0_pre9
so that, for phase 2, two sets of validation plots will be made?

By the way,
[3] https://cmssdt.cern.ch/lxr/source/Validation/RecoEgamma/python/ElectronMcSignalValidator_cfi.py
This looks almost the same as [1], but is it used? If not, should be removed to avoid confusions?

When the validation improvements above for monitoring endcap is addressed, this issue can be closed?

And, @SohamBhattacharya how is the electron path cleaning for phase2 coming along in the meantime?

**Comment by SohamBhattacharya** [comment]
@hatakeyamak Apologies for the late response.
Your suggestion seems reasonable to me, but I'll let @silviodonato and other validators comment.

As for the cleaning, we have been running some checks -- should have some update on this next week.

**Comment by silviodonato** [comment]
@SohamBhattacharya https://github.com/cms-sw/cmssw/issues/32475#issuecomment-821852809 looks ok to me.

Let me just update the plot to `CMSSW_11_3_0_pre5`, just to show that the issue is still there (as expected, obviously)
https://github.com/cms-sw/cmssw/issues/32475#issuecomment-821852809
![image](https://user-images.githubusercontent.com/6177433/116050974-62466900-a678-11eb-9992-94e6e6555e2a.png)

**Comment by hatakeyamak** [comment]
@SohamBhattacharya @jainshilpi who are the egamma validators who should try to address this specific validation plotting issues for phase2?

**Comment by SohamBhattacharya** [comment]
Hi @beaudett , @archiron , and Axel Perraguin (I did not find his git handle, so if anyone knows that, please feel free to tag him).
After some discussion in this thread we have decided to keep the barrel and endcap (HGCal) electron collections separate for now in MINIAOD. @hatakeyamak has provided some suggestions [1] regarding how the HGCal collection can be added to the MINIAOD validation setup. Can you please take a look at that?


[1] https://github.com/cms-sw/cmssw/issues/32475#issuecomment-821852809

**Comment by SohamBhattacharya** [comment]
Hi @beaudett , thank you for pointing us to https://github.com/cms-sw/cmssw/pull/33421.
@silviodonato , can this issue be closed in light of this PR?

**Comment by archiron** [comment]
+1
