### ISSUE TITLE
NANO stored branches not same for all files in a job/run

### ISSUE THREAD

**Issue by andrzejnovak** [cms-sw/cmssw#32731]
NanoAOD can produce files in one Run/job where not all trigger branches are the same. For example,. the files
```
"root://xrootd-cms.infn.it///store/data/Run2016B/JetHT/NANOAOD/02Apr2020_ver2-v1/240000/CE30FF6E-90C0-4F49-ADEC-74FDAC1619A3.root",
"root://xrootd-cms.infn.it///store/data/Run2016B/JetHT/NANOAOD/02Apr2020_ver2-v1/20000/35EFFD7C-AEED-3943-B3FF-BF83704FB239.root",
```
differ by 6 branches. 

```
'L1_ETT15_BptxAND',
'L1_ETT40',
'L1_ETT60',
'HLT_Ele27_WPTight_Gsf_L1JetTauSeeded',
'HLT_Ele45_WPLoose_Gsf_L1JetTauSeeded',
'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_L1JetTauSeeded'
```

This is considerably annoying in further processing, where these need to be special cased.

**Comment by makortel** [comment]
assign xpog

**Comment by mariadalfonso** [comment]
@andrzejnovak

NanoAOD will automatically create and fill only the branches corresponding to triggers that are found in the input file.
When it finds a new trigger looping through the events, either in production or when hadding files with haddnano, it will create the new branch and back-fill it with zeros for the events found until that point, where that trigger was not present.
Merging different files should be done with haddnano that will take care of the missing HLT branches, instead of using the plain hadd.

With the cms-sw/cmssw#36277 the haddnano, already used by many,  is widely distributed by the cms-sw.

**Comment by mariadalfonso** [comment]
+xpog
