### ISSUE TITLE
GEM Phase2 premixing does not work with g4SimHitsMuonME0Hits

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#33013]
As seen in
https://github.com/cms-sw/cmssw/pull/33007#issuecomment-787071765
premixing with D76 does not work because g4SimHitsMuonME0Hits is missing.

Lookin in the premixing file, we currently have
`PCrossingFrame<PSimHit>               "mix"                       "g4SimHitsMuonGEMHits"   "DIGI" `
produced with (*) only.

Should the following parameters disable for now?
```
labelSig = cms.InputTag("mix", "g4SimHitsMuonME0Hits"),
pileInputTag = cms.InputTag("mix", "g4SimHitsMuonME0Hits"),
collectionDM = cms.string("g4SimHitsMuonME0Hits"),
```
in
https://github.com/cms-sw/cmssw/blob/master/SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py#L311-L313

(*)
To make premixing
`cmsDriver.py step2  --conditions auto:phase2_realistic_T21 --pileup_input das:/RelValMinBias_14TeV/CMSSW_11_3_0_pre3-113X_mcRun4_realistic_v3_2026D76noPU-v1/GEN-SIM -n 10 --era Phase2C11M9 --eventcontent PREMIX --procModifiers premix_stage1 --relval 100000,100 -s GEN,SIM,DIGI:pdigi_valid --pileup AVE_50_BX_25ns_m3p3 --datatier PREMIX --beamspot HLLHC14TeV --geometry Extended2026D76 --evt_type SingleNuE10_cfi --io PREMIX_2026D76PU_PremixHLBeamSpot14PU_PMXS1S2PR.io --python PREMIX_2026D76PU_PremixHLBeamSpot14PU_PMXS1S2PR.py --no_exec --fileout file:step2.root `

To mix with signal
`cmsDriver.py step3  --datamix PreMix --conditions auto:phase2_realistic_T21 --pileup_input file:step2.root -n 10 --era Phase2C11M9 --eventcontent FEVTDEBUGHLT --procModifiers premix_stage2 --filein file:step1.root -s DIGI:pdigi_valid,DATAMIX,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --datatier GEN-SIM-DIGI-RAW --geometry Extended2026D76 --io DigiTriggerPU_PMXS1S2PR_2026D76PU.io --python DigiTriggerPU_PMXS1S2PR_2026D76PU.py --no_exec --fileout file:step3.root`

**Comment by srimanob** [comment]
Assign upgrade

**Comment by srimanob** [comment]
Could you please have a look @dildick @watson-ij ?
Thanks very much.

**Comment by srimanob** [comment]
I currently disable ME0 using phase2_GE0 following https://github.com/cms-sw/cmssw/pull/31309,
https://github.com/cms-sw/cmssw/pull/33007/commits/6d300817df79bbaa1a1ba08c6908015043b0e4a1

**Comment by dildick** [comment]
Hi @srimanob ! I've been out of the loop on the GE0 integration lately. Just to clarify, you wanted to confirm that the changes you propose would work for GE0? To me it seems fine. The latest test of WF 34634.0 in #33007 ran fine. Perhaps @watson-ij can comment?

Just searching for `g4SimHitsMuonME0Hits` on git, there is also a mention here: https://github.com/cms-sw/cmssw/blob/CMSSW_11_3_X/SimGeneral/TrackingAnalysis/python/TrackingParticleSelection_cfi.py#L70-L72. Should we make an exception for phase2_muon geometries with GE0 instead of ME0?

**Comment by srimanob** [comment]
Thanks @dildick 
Actually, the workflow, we currently have an issue, is 34834.999 (premixing). What I did is to disable of ME0/GE0 in stage2 as I understand that it is not ready yet.

Regarding the TrackingAnalysis, it seems you are right. Could you please confirm @watson-ij ? Thanks,

**Comment by watson-ij** [comment]
@srimanob for the GE0 geometries, the ME0 is built in the GEM system, meaning that the hits should be in GEM containers (with the other GEM detectors), and the ME0 containers won't exist. So, it is correct to disable them, not because it doesn't work, but because its integrated into GEM. The phase2_GE0 flag is used for switching between ME0 (with ME0 containers) and GE0 (without ME0 containers), so the commit should be the correct thing to do. Similarly for the tracking analysis, I think @dildick is correct there also.

**Comment by srimanob** [comment]
Thanks, @watson-ij for confirmation.

**Comment by srimanob** [comment]
Note that, I've implement the fix to the tracking analysis to the PR. I think we can close this ticket.

**Comment by srimanob** [comment]
+1
