### ISSUE TITLE
Vector passed by value

### ISSUE THREAD

**Issue by dpiparo** [cms-sw/cmssw#33419]
Here we pass a std::vector by value when the const reference would be the best way to go: https://github.com/cms-sw/cmssw/blob/master/CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h#L72

**Comment by dan131riley** [comment]
Looks ok to me.  It gets used here: https://github.com/cms-sw/cmssw/blob/02d443bd49e0f29381709421b4a812496f9b8d1a/CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc#L485-L490

`convolve()` creates a local `vector<double>` and returns it:

https://github.com/cms-sw/cmssw/blob/02d443bd49e0f29381709421b4a812496f9b8d1a/CalibCalorimetry/HcalAlgos/interface/HcalPulseShapes.h#L60-L71

Return value optimization means that the return values from `convolve()` and `normalize()` have move semantics, not copy, so there's no memory allocation or copying of the vector data.  If it were passed by const reference there'd be more memory allocations since the arg currently gets modified and passed on.  If it were passed by non-const reference, it would have to be captured by reference all the way through the chain using reference lifetime extension, and in general I vastly prefer RVO over RLE--RLE is much more error-prone.
