### ISSUE TITLE
improve `scram b runtests`

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#33521]
When running `scram b runtests` on many packages, and/or with multiple jobs in parallel, it is sometimes hard to figure out exactly what output belongs to each test, and how to reproduce the failures.

This is a suggestion to improve `scram b runtests` in two ways:
  - before running each test, `scram` could create a shell script that runs the test, *e.g.* at `$CMSSW_BASE/unittest/$SCRAM_ARCH/Subsystem/Package/testName.sh`
  - while running each test, `scram` (or the newly created script) could redirect the output and error streams to *e.g.* `$CMSSW_BASE/unittest/$SCRAM_ARCH/Subsystem/Package/testName.log`

The first point makes it easier re-run individual tests, which is not always trivial for tests that require a specific environment, command line arguments, *etc.*

The latter point would make it easier to check the output of each test.

**Comment by fwyzard** [comment]
assign core

**Comment by smuzaffar** [comment]
@fwyzard , scram already create individual log file for each unit test as `tmp/$SCRAM_ARCH/src/<Package>/test/<TestName>/testing.log` and collection of all the unit tests results are also available in `logs/$SCRAM_ARCH/testing.log`. In order to re-run a single test, you can just run `scram b runtests_<TestName>`

**Comment by fwyzard** [comment]
Interesting !
Can you add it to `man scram` ?
