### ISSUE TITLE
understand long double behaviour on PPC

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmssw#33743]
PowerPC differs from x86_64 in the way long double are handled natively as it supports float128 (in hardware in PPC9)

at the moment the behavior is a bit weird to say the least (see #32141 )
for instance 
```
[cmsbuild@ibmminsky-1 vitest]$ c++  -O2 longdouble.cc -S -mlong-double-64
[cmsbuild@ibmminsky-1 vitest]$ grep sincos longdouble.s
	bl sincos
[cmsbuild@ibmminsky-1 vitest]$ c++ -std=c++11 -O2 longdouble.cc -S -mlong-double-64
[cmsbuild@ibmminsky-1 vitest]$ grep sincos longdouble.s
	bl sincosl
```

1) would be useful to build gcc 11.1 to understand if the behavior is more sane (and eventually subit bug reports to gcc if not)
2) understand if for our use cases is better ``` -mlong-double-64```,  ``` -mlong-double-128```  or even ```-mabi=ieeelongdouble```

independenly of all this we need to review the use of ```long double``` in the code (include the mandatory use of it in user defined literals``` and eventually take action to ensure that no long double arithmetic ever shows up in algorithms.

**Comment by makortel** [comment]
assign core

**Comment by mrodozov** [comment]
@VinInn I built gcc11 on PPC which can be used now on ibmminsky-1 sourcing from here
`source /scratch/mrodozov/gcc11/build_gcc11/slc7_ppc64le_gcc9/external/gcc/11.1.0/etc/profile.d/init.sh`

gcc11:

```
-bash-4.2$ source build_gcc11/slc7_ppc64le_gcc9/external/gcc/11.1.0/etc/profile.d/init.sh 
-bash-4.2$ c++  -O2 longdouble.cc -S -mlong-double-64
-bash-4.2$ grep sincos longdouble.s
	bl sincos
-bash-4.2$ c++ -std=c++11 -O2 longdouble.cc -S -mlong-double-64
-bash-4.2$ grep sincos longdouble.s
	bl sincos
```

gcc9:

```
source build_clhep_root_dd4_debug/slc7_ppc64le_gcc9/external/gcc/9.3.0/etc/profile.d/init.sh
-bash-4.2$ c++  -O2 longdouble.cc -S -mlong-double-64
-bash-4.2$ grep sincos longdouble.s
	bl sincos
-bash-4.2$ c++ -std=c++11 -O2 longdouble.cc -S -mlong-double-64
-bash-4.2$ grep sincos longdouble.s
	bl sincosl


```

**Comment by mrodozov** [comment]
with -mlong-double-128 it fails to compile:

```
-bash-4.2$ c++ -std=c++20 -O2 longdouble.cc -S -mlong-double-128
longdouble.cc:4:40: error: '(1.8e+2l / 3.14159265358979323846264338327948e+0l)' is not a constant expression
    4 | constexpr long double degPerRad = 180. / piRadians;  // Degrees per radian
      |                                   ~~~~~^~~~~~~~~~~
-bash-4.2$ c++ -std=c++11 -O2 longdouble.cc -S -mlong-double-128
longdouble.cc:4:40: error: '(1.8e+2l / 3.14159265358979323846264338327948e+0l)' is not a constant expression
    4 | constexpr long double degPerRad = 180. / piRadians;  // Degrees per radian
      |                                   ~~~~~^~~~~~~~~~~
-bash-4.2$ c++ -std=c++20 -O2 longdouble.cc -S -mabi=ieeelongdouble
cc1plus: warning: Using IEEE extended precision 'long double' [-Wpsabi]
-bash-4.2$ grep sincos longdouble.s
	bl sincos
```

**Comment by VinInn** [comment]
Ok. this is in line with what I "expected".
we could consider to compile EVERYTHING with -mabi=ieeelongdouble
it is an ABI change, so it needs "understanding".
Maybe we shall investigate with "experts" and those using or planning to use PPC (HPC?).
CINECA?  
what about OpenLab?
@tommasoboccali

**Comment by VinInn** [comment]
summary:
gcc11 seems to cure the weird behavior observed till gcc10.3. So no bug report to gcc!

**Comment by mrodozov** [comment]
>  we could consider to compile EVERYTHING with -mabi=ieeelongdouble

ok we can try it, but reading this suggests changing the ABI with this flag may need glibc adjustment and "other stuff"
https://www.talospace.com/2018/12/the-saga-of-power-isa-128-bit-long.html (it's a nice overview)

the externals we use with additional flag for long double on PPC are not that many:

```
./fmt.spec:    -DCMAKE_CXX_FLAGS="-mlong-double-64" \
./llvm-gcc-toolfile.spec:    <flags REM_CXXFLAGS="-mlong-double-64"/>
./compilation_flags.file:%define ppc64le_build_flags  -mlong-double-64 -mcpu=power8 -mtune=power8 --param=l1-cache-size=64 --param=l1-cache-line-size=128 --param=l2-cache-size=512
./geant4.spec:  -DCMAKE_CXX_FLAGS="-fPIC -mlong-double-64" \
./geant4.spec:  -DCMAKE_STATIC_LIBRARY_CXX_FLAGS="-fPIC -mlong-double-64" \
./geant4.spec:  -DCMAKE_STATIC_LIBRARY_C_FLAGS="-fPIC -mlong-double-64" \
./fftjet.spec:            CXXFLAGS="-O2 -mlong-double-64" \
-bash-4.2$ grep -r "ppc64le_build_flags"  .
./gcc-toolfile.spec:    COMPILER_CXXFLAGS="$COMPILER_CXXFLAGS -fsigned-char -fsigned-bitfields %{ppc64le_build_flags}"
./compilation_flags.file:%if "%{?ppc64le_build_flags:set}" != "set"
./compilation_flags.file:%define ppc64le_build_flags  -mlong-double-64 -mcpu=power8 -mtune=power8 --param=l1-cache-size=64 --param=l1-cache-line-size=128 --param=l2-cache-size=512
./mkfit.spec:BUILD_ARGS=VEC_GCC="%{ppc64le_build_flags}"
./fastjet.spec:    *_ppc64le_*) CXXFLAGS="${CXXFLAGS} %{ppc64le_build_flags}" ;;
./vecgeom.spec:  -DCMAKE_CXX_FLAGS="%{ppc64le_build_flags}" \
./OpenBLAS.spec:make FC=gfortran BINARY=64 NUM_THREADS=256 DYNAMIC_ARCH=0 CFLAGS="%{ppc64le_build_flags}"
```

It's only OpenBLAS and fmt that are not CERN related externals.
where's long double used in CMSSW I think we already know or we would've if there were more places than Geometry/DD4Hep.
In my experience OpenLab are mostly administering the Power8 machines we use.
I fail to find OpenLabs list of resources - they we expecting Power9 machines and this should be "somewhere" available for listing on the queue

**Comment by VinInn** [comment]
I suspected that changing ABI would led to havoc... Apparently is useless as well.
Maybe on PPC9 (if/when we ever would have the opportunity to run on one of those)

**Comment by VinInn** [comment]
My understanding  (and preference) is to forget about "long double" and eventually use float128 (with all  leading "_" required)

**Comment by mrodozov** [comment]
Reading this:
https://gcc.gnu.org/wiki/Ieee128PowerPC#Background
says clearly moving from the default to __float128 for ppc64le is desirable:

`PowerPC 64-bit Linux little endian server | It may be desirable to change the default to IEEE 754R 128-bit floating point`

from the GCC configure docs:
https://gcc.gnu.org/install/configure.html
`
The default long double format is to use IBM extended double. Until all of the libraries are converted to use IEEE 128-bit floating point, it is not recommended to use --with-long-double-format=ieee. `

and my suggestion will be to configure gcc on PPC exactly how it's not recommended and see what happens when it tries
to build externals. I think it will expect the externals use the __float128 type and if they don't it may try to use the 
-mabi=ieeelongdouble in which case there will be warnings in the logs.

Also, there is a bug with using `constexpr long double` in gcc:
https://stackoverflow.com/questions/48553127/error-with-long-doubles-on-powerpc-when-compiling-with-gcc
thats why the example doesn't compile, fortunately we don't have this anymore in cmssw

I also removed all the -mlong-double-64 flags from externals in https://github.com/cms-sw/cmsdist/pull/6933
because for those externals it's the exception and the proper type is the default 128 bit in size, all externals built, now I'm testing cmssw. The bug in gcc9 was for the -mlong-double-64 where sincosl was used and for the mlong-double-128 it's using sincos. 
We'll either use the default as in this PR or put the -mlong-double-64 flag everywhere also for cmssw. Seems to me the 128 bit type is "the proper one" from what I read on this docs

Another thing is glibc functions that use long double and needs to be built with __float128, currently we are using the glibc from the system and we may need to use a trick to substitute these:
from here:
https://gcc.gnu.org/wiki/Ieee128PowerPC

```
5.2 Glibc internal use of long double

Right now, glibc uses long double in some of the double math functions to provide more accuracy. Should glibc transition to explicitly use __float128 for these types, or possibly be compiled with -mabi=ieeelongdouble? 
```

I accidentally found this issue which links are an example of people having trouble with __float128 and CUDA
https://github.com/LLNL/blt/issues/341

involving tensorflow, mxnet and friends

this flag from the config docs: -mfloat128-hardware doesn't work on our PPC8 , so one might need to know from before what are the specs on the expected PPC9 machines.

for now thats it, 
let me know if I'm missing something on should we stick to the -mlong-double-64 flag or I can remove it in  cms-sw/cmsdist#6933

**Comment by VinInn** [comment]
To summarize my proposal:
1) remove flag ```-mlong-double-64```
2) either
2a) change ```constexpr double operator"" _pi(long double x) { return x * piRadians; }```
tp ```constexpr double operator"" _pi(long double x) { return double(x) * M_PI; }
or
2b) remove ```_pi```  and use *std::pi() or equivalent;

**Comment by smuzaffar** [comment]
+core
- `-mlong-double-64` has been removed
- https://github.com/cms-sw/cmssw/pull/33892 takes care of the PI using literals issue
