### ISSUE TITLE
L1Trigger/L1TMuon package not rebuilt in #33727 tests

### ISSUE THREAD

**Issue by dildick** [cms-sw/cmssw#33781]
PR #33727 is continuing to fail integration tests. The code does not appear to be compiling properly. Upon closer inspection, it seems that the L1Trigger/L1TMuon package not rebuilt. See also this comment by Jia Fu: https://github.com/cms-sw/cmssw/pull/33727#issuecomment-843224391.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I see `L1Trigger/L1TMuon` declares dependence on `DataFormats/L1TMuon`
https://github.com/cms-sw/cmssw/blob/3092d812cd79e9b6cafb82435618b4464b5cdd5c/L1Trigger/L1TMuon/BuildFile.xml#L8
that further depends on `DataFormats/CSCDigi`
https://github.com/cms-sw/cmssw/blob/3092d812cd79e9b6cafb82435618b4464b5cdd5c/DataFormats/L1TMuon/BuildFile.xml#L4
so the recompilation should be triggered.

We'd really need @smuzaffar but he is mostly away until the end of the week.

One thing I noticed in the BuildFile of `L1Trigger/L1TMuon` was that it exports `DataFormats/L1TMuon`
https://github.com/cms-sw/cmssw/blob/3092d812cd79e9b6cafb82435618b4464b5cdd5c/L1Trigger/L1TMuon/BuildFile.xml#L1-L6
It could be unrelated, but I can't avoid wondering if that would play some role in the problem?

**Comment by makortel** [comment]
`L1Trigger/L1TMuon` should declare a direct dependence on `DataFormats/CSCDigi` because it has files in `src` that `#include` headers from `DataFormats/CSCDigi`, e.g.
https://github.com/cms-sw/cmssw/blob/3092d812cd79e9b6cafb82435618b4464b5cdd5c/L1Trigger/L1TMuon/src/MuonTriggerPrimitive.cc#L6

**Comment by dildick** [comment]
Ok. What about the export section? What does that do in the BuildFile?

**Comment by makortel** [comment]
> What about the export section? What does that do in the BuildFile?

Honestly I don't know (I have some guesses but prefer to not spell them out). @smuzaffar?

**Comment by makortel** [comment]
I tried to reproduce with
```
cmsrel CMSSW_12_0_X_2021-05-16-0000
cd CMSSW_12_0_X_2021-05-16-0000/src
cmsenv
git cms-addpkg DataFormats/CSCDigi
# edit DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h
git cms-addpkg -A -a
```
and that does check out `L1Trigger/L1TMuon`.

**Comment by davidlange6** [comment]
its not possible to conclude from the scram b printout what was not checked out. checkdeps does not primarily rely on buildfile information in any case. It is looking at dependencies in libraries. @makortel has done the right test. now what happens if git cms-addpkg... is replaced with git cms-merge-topic 33727 and scram b?

**Comment by makortel** [comment]
```
cmsrel CMSSW_12_0_X_2021-05-16-0000
cd CMSSW_12_0_X_2021-05-16-0000/src
cmsenv
git cms-merge-topic 33783
```
reproduces the problem, i.e. `L1Trigger/L1TMuon` is not checked out.

**Comment by davidlange6** [comment]
which instead should have happened given this include:

```/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-05-16-0000/src/L1Trigger/L1TMuon/src/MuonTriggerPrimitive.cc:#include "DataFormats/CSCDigi/interface/CSCCorrelatedLCTDigi.h"```

I can look at it more tomorrow.

**Comment by makortel** [comment]
Thanks David!

**Comment by smuzaffar** [comment]
@makortel , @davidlange6 I am looking in to it now. I think there is bug in git-cms-checkdeps.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/33783 should fix this issue

**Comment by smuzaffar** [comment]
> > What about the export section? What does that do in the BuildFile?
> 
> Honestly I don't know (I have some guesses but prefer to not spell them out). @smuzaffar?

please see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideBuildFile#BuildFileExport . In past `export` section was used to only expot those dependencies which are used by the public interface (headers files) of the package. But that option was dropped as on OSX we had to keep the build and export dependencies same. Now the only thing one need to have in `<export>` section is the generated shared library name or `<lib name="1"/>` so that dependent packages can link against this library. If poackage generates an edm plugin or package is source only ( no shared library generated) then there is no need to have export section.
