### ISSUE TITLE
ProductNotFound in Run3 workflows 11824.0 and 11825.0 in 10_6_X IB

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#33988]
For some while,  there are issues with Run3 workflows 11824.0 and 11825.0 in 10_6_X IB, for example:

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_6_X_2021-06-05-1100/pyRelValMatrixLogs/run/11825.0_ZEE_13+ZEE_13TeV_TuneCUETP8M1_2021PU_GenSimFullINPUT+DigiFullPU_2021PU+RecoFullPU_2021PU+HARVESTFullPU_2021PU+NanoFull_2021PU/step5_ZEE_13+ZEE_13TeV_TuneCUETP8M1_2021PU_GenSimFullINPUT+DigiFullPU_2021PU+RecoFullPU_2021PU+HARVESTFullPU_2021PU+NanoFull_2021PU.log#/143-143

   [0] Processing  Event run: 1 lumi: 17 event: 1605 stream: 3
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module PATTauRefSelector/'finalBoostedTaus'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<pat::Tau>
Looking for module label: slimmedTausBoostedNewID
Looking for productInstanceName: 

It should be related to https://github.com/cms-sw/cmssw/pull/33587
It could be we should switch on nanoAOD_addBoostedTauIds_switch for Run3:
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/NanoAOD/python/nano_cff.py#L422-L424

It may not be urgent as 10_6_X will not be used for Run3 workflows, but for tracking the issue I opened an issue here.

**Comment by qliphy** [comment]
assign @cms-sw/xpog-l2  
adding @swozniewski

**Comment by qliphy** [comment]
adding @swozniewski

**Comment by mariadalfonso** [comment]
@swozniewski
we have to set the future (nanov9 and Run3) as default and redefine the past with the modifiers! so probably in
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/NanoAOD/python/nano_cff.py#L418-L419
 
```
nanoAOD_addTauIds_switch = cms.untracked.bool(True),        
nanoAOD_addBoostedTauIds_switch = cms.untracked.bool(True)
```
then line 421-424 can be simplified !

**Comment by mariadalfonso** [comment]
@swozniewski
any news ?

**Comment by swozniewski** [comment]
Sorry, I missed your first note! Thanks for pinging me again. It looks like we were not careful enough with backporting from master. In master, there is no extra flag defined for steering that the boostedTaus are only produced for future versions and therefore it was encoded as the NOT of previous eras (obviously not knowing what the future modifiers will be called).
In 10_6_X there is an additional line combined with this NOT ( https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/NanoAOD/python/nano_cff.py#L423 ). It is not present in master and breaks this logic. I don't know why it was added in 10_6_X. @mariadalfonso , you added it, maybe you remember. From the commit message I'd assume that it was just to add latest modifiers but without technical necessity.
Altogether, I think we could simply drop this line (1). Also the tau ID task for conventional taus should not be necessary for Run3 (incorrect as well at the moment).
Alternatively, since a flag is used in this implementation, it is also possible to switch defaults and work without the NOT (2). Also in this case, the given line would be useless and removed. I don't see a particular reason why this should not work here.
@mariadalfonso please let me know which is your preferred solution (even though I suppose it is (2)) and I will create a PR.

**Comment by swozniewski** [comment]
With 'this line' I meant https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/NanoAOD/python/nano_cff.py#L423

**Comment by swozniewski** [comment]
I just noticed that in 10_6_X, the latest deepTauID version is only available in miniAOD for certain run2-modifiers: https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L405-L411
Therefore, Run3 would still require an execution of the nanoAOD_addTauIds function. I'd therefore suggest to keep the default  of nanoAOD_addTauIds_switch as true and only set it to false for the modifiers used in the place I linked.

**Comment by mariadalfonso** [comment]
+xpog

resolved in linked PR
