### ISSUE TITLE
Ecal and Hcal Local GPU Reco crashes on missing detector

### ISSUE THREAD

**Issue by Sam-Harper** [cms-sw/cmssw#34197]
A bug was exposed last MWGR in that both HCAL and ECAL local reconstruction on a GPU do not have protections when the respective detector is out. 

This is explicitly in the HBHERecHitProducerGPU
>cmsRun: /build/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_3_1-slc7_amd64_gcc900/build/CMSSW_11_3_1-build/tmp/BUILDROOT/ebcff69f73237d0d563ea1e7c33f2d83/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_1/src/RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu:1064: void hcal::reconstruction::entryPoint(const hcal::reconstruction::InputDataGPU&, hcal::reconstruction::OutputDataGPU&, const hcal::reconstruction::ConditionsProducts&, hcal::reconstruction::ScratchDataGPU&, const hcal::reconstruction::ConfigParameters&, cudaStream_t): Assertion `startingSample == 0 || startingSample == 2' failed.

and a similar crash was observed in ECAL

To reproduce simply run over any run with the appropriate detector missing.

**Comment by makortel** [comment]
assign reconstruction, heterogeneous

**Comment by makortel** [comment]
FYI @cms-sw/ecal-dpg-l2 @cms-sw/hcal-dpg-l2 @vkhristenko

**Comment by fwyzard** [comment]
An other corner case that needs to be tested and possibly addressed is the unpacking and local reconstruction of *calibration* data.

It may also be useful to check if data taken in non-standard conditions (different zero suppresion, etc.) is properly handled.

**Comment by thomreis** [comment]
Is there a recipe to reproduce this? Running at P5 with a specific HLT configuration? @amassiro FYI even though I guess you know already.

**Comment by fwyzard** [comment]
@mzarucki does FOG have some samples to reproduce the issues ?

**Comment by mzarucki** [comment]
Hi all,

@smorovic put the file from the run 342053 that was crashing in NFS `/nfshome0/smorovic/gpu-test`

The HLT menu used was `/cdaq/cosmic/commissioning2021/MWGR4/Cosmics_GPUTest1_V2/V2` which requires the upgraded ConfDB (briefly described [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/HLTOnlineTestStand#Testing_with_GPUs)).

Cheers,
Mateusz

**Comment by fwyzard** [comment]
Hi Mateusz,
thanks... however I think if we want the DPGs to investigate the problem,
we need some more conventional instructions.

1. can you provide the instructions (CMSSW release, etc.) and a full fump
of the menu that can be run out of the box ?

2. do we have files from the ECAL-only and HCAL-only runs ? if we do, could
you list them explicitly? if we don't, vcan you list explicitly some other
files that should be used ?

3. can you test the instructions (release, config file, input files) to
make sure the crash is reproducible on the online GPU machines (without
hikton/hltd) ?

Of course, "you" as in "anybody from FOG" :-)

This should make it easier for the DPGs to reproduce the problems, and thus
fix them.

.A

**Comment by mzarucki** [comment]
Hi Andrea, all,

I came up with the simplest set of instructions to reproduce the errors, by copying the HLT menu file and raw input files from @smorovic into my directory on NFS (`/nfshome0/mzarucki/GPUTests`).

As a first step, one would need to be logged into one of the GPU machines with a working area set up - all instructions are included in the GPU development Twiki: https://twiki.cern.ch/twiki/bin/viewauth/CMS/TriggerDevelopmentWithGPUs

I will let @fwyzard comment on which machines are best to use. Concerning the working area, it could be either on NFS (`/nfshome0/`) or on the `/data/user/$USER` directory of the machine, as described [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/TriggerDevelopmentWithGPUs#Local_disk_space).

The release to set up is `CMSSW_11_3_1_patch1`. You can copy the HLT GPU menu configuration file from: `/nfshome0/mzarucki/GPUTests/Cosmics_GPUTest1_V2-V2.py`. On top of the standard configuration, there is a block of code which sets up the [DAQ source](https://patatrack.web.cern.ch/patatrack/wiki/DAQSource), including the local input file:

```
process.EvFDaqDirector = cms.Service(
    "EvFDaqDirector",
    runNumber=cms.untracked.uint32(342053),
    baseDir=cms.untracked.string("tmp"),
    buBaseDir=cms.untracked.string(
        "/nfshome0/mzarucki/CMSSW_11_3_1_patch1/src"
    ),
    useFileBroker=cms.untracked.bool(False),
    fileBrokerKeepAlive=cms.untracked.bool(True),
    fileBrokerPort=cms.untracked.string("8080"),
    fileBrokerUseLocalLock=cms.untracked.bool(True),
    fuLockPollInterval=cms.untracked.uint32(2000),
    requireTransfersPSet=cms.untracked.bool(False),
    selectedTransferMode=cms.untracked.string(""),
    mergingPset=cms.untracked.string(""),
    outputAdler32Recheck=cms.untracked.bool(False),
)

process.source.fileNames = cms.untracked.vstring("/nfshome0/mzarucki/GPUTests/ECALin_HCALout/run342053/run342053_ls0013_index000002.raw")
#process.source.fileNames = cms.untracked.vstring("/nfshome0/mzarucki/GPUTests/HCALin_ECALout/run342110/run342110_ls0023_index000000.raw")
process.source.fileListMode = True
```

where one would have to update the `buBaseDir` to your CMSSW directory.

To recreate the HCAL crash from run 342053 with ECAL in and HCAL out ([e-log](http://cmsonline.cern.ch/cms-elog/1117986)), one would use the file that is already set up (`/nfshome0/mzarucki/GPUTests/ECALin_HCALout/run342053/run342053_ls0013_index000002.raw`). 

To recreate the ECAL crash from run 342175 with HCAL in and ECAL out ([e-log](http://cmsonline.cern.ch/cms-elog/1118295)), we have another raw file locally available from run 342110 with the same setup (`/nfshome0/mzarucki/GPUTests/HCALin_ECALout/run342110/run342110_ls0023_index000000.raw`). In the `EvFDaqDirector` one would have to update the `runNumber`, as well as the `process.source.fileNames` of course.

@fwyzard, @Sam-Harper please comment if there is anything else to add.

Cheers,
Mateusz

PS. @Sam-Harper has updated the `hltGetConfiguration` command for dumping GPU menus, however, this is not (yet) working on the GPU machines. Therefore, a local copy is the simplest alternative. The menus that were ran are also temporarily saved in `/var/log/hltd/pid/` on the machines that were used in the DAQ configuration (`fu-c2a02-37-[01-04]`).

**Comment by thomreis** [comment]
Thanks @mzarucki for the detailed recipe. I think this should be enough to get going.
However, @fwyzard is the 11_3_1_patch1 release installed on the GPU machines? I find only 11_3_0_patch1.

**Comment by fwyzard** [comment]
@thomreis all offline releases are actually available from `/cvmfs`; I've added instruction for using them to the twiki: https://twiki.cern.ch/twiki/bin/view/CMS/TriggerDevelopmentWithGPUs#Setting_up_a_working_area_fo_AN2 .

**Comment by thomreis** [comment]
@fwyzard thanks I got it to work. I must have had a cached version of the twiki without those instructions.
I can now reproduce the crash.

**Comment by fwyzard** [comment]
no, I just added them one hour ago :-)

**Comment by thomreis** [comment]
I have made PRs to `master` and `CMSSW_11_3_X` with a fix for the ECAL out crash.

**Comment by Sam-Harper** [comment]
thanks Thomas!

**Comment by Sam-Harper** [comment]
@cms-sw/hcal-dpg-l2 is there a timeline the HCAL DPG to have a look at this? Thanks!

**Comment by mseidel42** [comment]
@mariadalfonso could you have a look, please?

**Comment by slava77** [comment]
+reconstruction

- ECAL: #34292 and #34293
- HCAL: #34429 (master) and #34428 (113X)

**Comment by mzarucki** [comment]
Dear all,


As initially [reported by us](https://indico.cern.ch/event/1062405/contributions/4468133/attachments/2288269/3889700/HLTReport_CRuZeT_RunOrganization_27.07.2021_Zarucki.pdfpage=5) during yesterday's Run Organization meeting and during today's [Daily Run Meeting](http://schwick.web.cern.ch/schwick/rctools/dailyReport/detailReport/display/2021-07-28), we are seeing HCAL and Pixel crashes when running over data that does not include HCAL, ECAL and Pixel in the run. It appears that unfortunately the additional protections implemented in _CMSSW_11_3_3_ were insufficient. The details of the crashes are included in the following [e-log](http://cmsonline.cern.ch/cms-elog/1121249), and it appears that the nature of these are different than the ones that were initially reported in this ticket above. We also saw that Pixel has recreated the issues and are investigating in https://github.com/cms-sw/cmssw/issues/34659.


We are continuing our tests to isolate and cross-check the ECAL protections, however, we wanted to make you aware of this issue.


Best regards,
Mateusz on behalf of TSG FOG

**Comment by mariadalfonso** [comment]
@mzarucki  can you give me the HCAL instruction on how to reproduce the problem as you did last time in https://github.com/cms-sw/cmssw/issues/34197#issuecomment-868476197 ?

**Comment by mzarucki** [comment]
Dear all,

We have been doing a number of tests on both Hilton and a separate GPU machine to better understand the crashes and try to isolate them (as it is a 3D problem). Apologies for the delay, however, certain crashes caused the Hilton GPU machine to become unreachable, requiring manual intervention by the sysadmins each time ([CMSONS-13216](https://its.cern.ch/jira/browse/CMSONS-13216)).

To summarise the investigations in a few bullets:
- We have prepared dedicated menus that only run one type of local GPU reconstructions ([e-log 1](http://cmsonline.cern.ch/cms-elog/1121506) + [e-log 2](http://cmsonline.cern.ch/cms-elog/1121305)). 
- Therefore, rather than running over different sets of data with different configurations of systems in/out of global, we were able to run just over [run 343762](https://cmsoms.cern.ch/cms/runs/report?cms_run=343762&cms_run_sequence=GLOBAL-RUN) which excludes ECAL, HCAL and Pixel.
- We have reproduced both the HCAL and Pixel crashes on the GPU Hilton.
- @mariadalfonso I have tried to reproduce the HCAL crash on one of the other GPU machines (similarly as with the recipe above):
  - The menu is located in _/nfshome0/mzarucki/GPUTests/CosmicsGPUFixed_HcalOnly-V1.py_
  - The data is located in  _/nfshome0/mzarucki/GPUTests/ECALout_HCALout_PIXELout/run343762/run_343762.root_
  - Unfortunately, I am not able to reproduce the exact crash in the original report ([e-log](http://cmsonline.cern.ch/cms-elog/1121249)). I posted the error message below [*]. It is not too explicit but hopefully the setup can help debug the issue.
  - An alternative would be to try to reproduce the HCAL crashes in the same way as done by Pixel in [#34659](https://github.com/cms-sw/cmssw/issues/34659). The same file is located on EOS: _/eos/cms/store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/FOG/CRUZET_2021_data/run_343762.root_

I will continue the summary in the next post.

Best,
Mateusz

[*]
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'
  what():  bad lexical cast: source type value could not be interpreted as target

A fatal system signal has occurred: abort signal
The following is the call stack containing the origin of the signal.

...

Current Modules:

Module: non-CMSSW (crashed)
```

**Comment by fwyzard** [comment]
Hi all,

what is the expected behaviour if HCAL is not in the run ?
  - produce an empty collection of HCAL rechits
  - do not produce any HCAL rechit collection ?

.A

**Comment by mzarucki** [comment]
Dear all,

[continuing from the previous post]

- Concerning the ECAL protections, as already reported, we have not seen any crashes when running over a menu with only ECAL reconstruction over the same data ([e-log](http://cmsonline.cern.ch/cms-elog/1121305)).
- We were able test the Pixel PR (https://github.com/cms-sw/cmssw/pull/34684) by pointing the Hilton to a local _CMSSW 11_3_3_ install, with the PR included on top. I do not see any crashes when using the _PixelOnly_ menu running over the same data.
- I have also ran the above setup (with Pixel PR) with a menu (`/cdaq/test/gennai/CMSSW_11_3_2/CosmicsGPUFixed_NoHcal/V1`) that contains only Pixel + ECAL reconstruction (under the assumption that the ECAL protections are fine). I saw the following ECAL crash [*], which I think it would be important for the ECAL experts to have a look at.
  - We did see similar errors of the type `std::runtime_error/std::bad_alloc exception` in the initial tests ([e-log](http://cmsonline.cern.ch/cms-elog/1121249)), however, since we were running with a complete GPU menu, the full logs were masked by the other crashes (and everything was rather convoluted).
  - When I try to recreate the crash on one of the other GPU machines (with Pixel PR on top of _11_3_3_), using the menu `/nfshome0/mzarucki/GPUTests/CosmicsGPUFixed_NoHcal-V1.py` I get the same (uninformative) crash as with the HCAL recipe above related to ` what():  bad lexical cast`.

Honestly, it is a bit surprising, since the `EcalOnly` menu worked fine on our tests. One also wouldn't expect the two different reconstructions to influence one another. It appears that the crashes were masked in the early tests. Or could this be some strange edge case?

Best regards,
Mateusz

[*] 
```
%MSG-e EcalUncalibRecHitProducerGPU:   EcalUncalibRecHitProducerGPU:hltEcalUncalibRecHitGPU 30-Jul-2021 13:09:50 CEST  Run: 343762 Event: 4185
max number of channels exceeded. See options 'maxNumberHitsEB and maxNumberHitsEE'
%MSG

std::bad_alloc exception
%MSG-e EcalUncalibRecHitProducerGPU:   EcalUncalibRecHitProducerGPU:hltEcalUncalibRecHitGPU 30-Jul-2021 13:15:32 CEST  Run: 343762 Event: 4296
max number of channels exceeded. See options 'maxNumberHitsEB and maxNumberHitsEE'
%MSG
terminate called after throwing an instance of 'std::runtime_error'
```

**Comment by thomreis** [comment]
Hi @mzarucki, thanks for the detailed analysis. Does the exception with ECAL and Pixel reco happen at the first event or only later?

**Comment by mzarucki** [comment]
Quick update: @fwyzard kindly pointed out that the reason for the `what(): bad lexical cast` is related to a misconfiguration of the `EvFDaqDirector` for the `.root` input file that we have available (picked up by `process.source.fileListMode = True`). Without this setting, the _HcalOnly_ menu does not crash on the input file - therefore, we cannot reproduce what is seen on Hilton.

I am trying to generate a proper input `.raw` file from the `.root` file, so that it mirrors to what is done on Hilton.

In parallel, I will try to have a look at your question @thomreis.

Therefore, in the meantime, I suggest to hold off trying this recipe until we have a reproducible setup.

Best regards,
Mateusz

**Comment by mzarucki** [comment]
Hi again,

@fwyzard managed to reproduce the HCAL crash by requiring the `cmsRun` job to be run with multiple threads.

Here is a simplfied recipe @mariadalfonso:
```
cmsrel CMSSW_11_3_3
cd CMSSW_11_3_3/src
cmsenv
cp /nfshome0/mzarucki/GPUTests/CosmicsGPUFixed_HcalOnly-V1_modified.py .
cmsRun CosmicsGPUFixed_HcalOnly-V1_modified.py
```

The _modified_ configuration file already includes the following changes:
- Pointing to the input file `/nfshome0/mzarucki/GPUTests/ECALout_HCALout_PIXELout/run343762/run_343762.root`
- Removed `process.source.fileListMode = True` (defaults to `False`)
- Has `numberOfThreads` and `numberOfStreams` hardcoded to 8 (rather than using the command line argument)

I am trying to create a similar recipe for what we saw with ECAL, however, currently it is not reproducing the crash (even with multiple threads). Concerning your question @thomreis, on a first glance at the log files, it looks like it occurs from the first processed event. I will still confirm this.

Best regards,
Mateusz

**Comment by thomreis** [comment]
Thanks. I was so far not able to reproduce the crash for ECAL + Pixel. I think a `.raw` input file would help get it to run for me as well.

**Comment by mzarucki** [comment]
Hi @thomreis,

I managed to generate a `.raw` file from the `.root` file: `/nfshome0/mzarucki/GPUTests/ECALout_HCALout_PIXELout/run343762/run343762_ls0001_index000005.raw`

Furthermore, I also managed to recreate the ECAL crash using the following config `/nfshome0/mzarucki/GPUTests/CosmicsGPUFixed_NoHcal-V1_modified.py` with CMSSW_11_3_3 that includes the Pixel PR on top (mirroring what is done on Hilton). Here I am again using the DAQ source (ie. again setting `process.source.fileListMode = True`).

I hope that this can help you debug the issue we were seeing.

Cheers,
Mateusz

**Comment by fwyzard** [comment]
With the attached version of [`CosmicsGPUFixed_NoHcal-V1_modified.py`](https://github.com/cms-sw/cmssw/files/6927390/CosmicsGPUFixed_NoHcal-V1_modified.txt) (modified to read a normal .root file) I get errors about some pixel kernels, while the ECAL part looks fine.

In fact, if I comment out the `HLT_Pixel_v1` path, the job runs to completion, and the summary shows that the ECAL modules run fine:
```
TrigReport ---------- Module Summary ------------
TrigReport    Visited   Executed     Passed     Failed      Error Name
...
TrigReport      87060      21765      21765          0          0 hltEcalDetIdToBeRecovered
TrigReport          0          0          0          0          0 hltEcalDigis
TrigReport     217650      21765      21765          0          0 hltEcalDigis@cuda
TrigReport      43530      21765      21765          0          0 hltEcalDigisGPU
TrigReport          0          0          0          0          0 hltEcalPhiSymFilter
TrigReport          0          0          0          0          0 hltEcalRecHit
TrigReport      43530      21765      21765          0          0 hltEcalRecHit@cuda
TrigReport          0          0          0          0          0 hltEcalUncalibRecHit
TrigReport      43530      21765      21765          0          0 hltEcalUncalibRecHit@cuda
TrigReport      43530      21765      21765          0          0 hltEcalUncalibRecHitGPU
TrigReport      43530      21765      21765          0          0 hltEcalUncalibRecHitSoA
```

**Comment by fwyzard** [comment]
Investigating some more, if I comment out the ECAL paths (`HLT_ECALHT1_v1`, `HLT_ECALHT1_NoGPU_v1`, `HLT_ECALHT1_GPU_v1`), the job **also** succeeds, and I can see that the pixel code ran:
```
TrigReport ---------- Module Summary ------------
TrigReport    Visited   Executed     Passed     Failed      Error Name
...
TrigReport          0          0          0          0          0 hltSiPixelClusters
TrigReport      43530      21765      21765          0          0 hltSiPixelClustersCUDA
TrigReport      21765      21765      21765          0          0 hltSiPixelDigisClusters
TrigReport      21765      21765      21765          0          0 hltSiPixelDigisSoA
TrigReport          0          0          0          0          0 hltSiPixelRecHits
TrigReport      43530      21765      21765          0          0 hltSiPixelRecHits@cuda
TrigReport      21765      21765      21765          0          0 hltSiPixelRecHitsCUDA
...
TrigReport      87060      21765      21765          0          0 hltPixelTracks
TrigReport      21765      21765      21765          0          0 hltPixelTracksCUDA
TrigReport      21765      21765      21765          0          0 hltPixelTracksFilter
TrigReport      21765      21765      21765          0          0 hltPixelTracksFitter
TrigReport          0          0          0          0          0 hltPixelTracksSoA
TrigReport      21765      21765      21765          0          0 hltPixelTracksSoA@cuda
...
```

**Comment by fwyzard** [comment]
While keeping all paths enabled, the job always crashes. So there seems to be some destructive interference between the ECAL and Pixel reconstruction :-/

**Comment by fwyzard** [comment]
@mzarucki could you confirm that - with 11.3.3 plus the latest fixes - running **only** the ECAL paths **or** the Pixel paths works also on Hilton ?

**Comment by mzarucki** [comment]
Hi @fwyzard,

Yes, our previous tests have already shown this. I have re-done them and confirm that we see no crashes when running only one set of path types in _11_3_3_ + fixes. We saw this already for ECAL in the pure _11_3_3_ release, and we see this for Pixel (_11_3_3_ + Pixel PR) and HCAL (_11_3_3_ + HCAL PR).

Cheers,
Mateusz

**Comment by thomreis** [comment]
I could reproduce the crash with the configuration of @mzarucki. It happens always with 2 or more threads.

I have extended a bit the error message just before the crash and it seems that there is a wrong number of channels passed in the digis.
```
%MSG-e EcalUncalibRecHitProducerGPU:   EcalUncalibRecHitProducerGPU:hltEcalUncalibRecHitGPU 04-Aug-2021 10:10:48 CEST  Run: 343762 Event: 2109
Max number of channels exceeded in barrel or endcap. Number of barrel channels: 2294272000 with maxNumberHitsEB=61200, number of endcap channels: 32689 with maxNumberHitsEE=14648
%MSG
----- Begin Fatal Exception 04-Aug-2021 10:10:54 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 343762 lumi: 1 event: 2109 stream: 1
   [1] Running path 'HLT_ECALHT1_GPU_v1'
   [2] Prefetching for module CaloTowersCreator/'hltTowerMakerEcal'
   [3] Prefetching for module EcalRecHitProducer/'hltEcalRecHit@cuda'
   [4] Prefetching for module EcalUncalibRecHitConvertGPU2CPUFormat/'hltEcalUncalibRecHit@cuda'
   [5] Prefetching for module EcalCPUUncalibRecHitProducer/'hltEcalUncalibRecHitSoA'
   [6] Calling method for module EcalUncalibRecHitProducerGPU/'hltEcalUncalibRecHitGPU'
Exception Message:
A std::exception was thrown.

/data/user/treis/ecal_local_reco/CMSSW_11_3_3/src/RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitMultiFitAlgoGPU.cu, line 118:
cudaCheck(cudaGetLastError());
cudaErrorInvalidConfiguration: invalid configuration argument
----- End Fatal Exception -------------------------------------------------
```
In principle the number of channels should be zero.
The crash is not always the same after the error message. I also got this one already:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  
/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_3_3-slc7_amd64_gcc900/build/CMSSW_11_3_3-build/tmp/BUILDROOT/402e2a5eeeb9630ea9f5469bb50cc947/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_3/src/HeterogeneousCore/CUDACore/src/ScopedContext.cc, line 86:
cudaCheck(cudaStreamAddCallback(stream, cudaScopedContextCallback, new CallbackData{waitingTaskHolder_, device}, 0));
cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by fwyzard** [comment]
> The crash is not always the same after the error message.

The problem is that - if the error happens inside a kernel, running asynchronously on the GPU - it till be reported by the first CUDA runtime call after it, in any thread.

This can happen in the memory allocator or in the framework support calls, because they are quite frequent and kind of wrap all other CUDA modules, even if the error is not there.

**Comment by thomreis** [comment]
While the crash happens in the `EcalUncalibRecHitProducerGPU` the reason for it seems to be in the `EcalRawToDigiGPU` module already where the false number of channels is stored in the digis.

**Comment by fwyzard** [comment]
looking at the code of `EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc`:
```c++
void EcalRawToDigiGPU::acquire(edm::Event const& event,
                               edm::EventSetup const& setup,
                               edm::WaitingTaskWithArenaHolder holder) {
...
  // unpack if at least one FED has data
  if (counter > 0) {
    ecal::raw::entryPoint(
        inputCPU, inputGPU, outputGPU_, scratchGPU, outputCPU_, conditions, ctx.stream(), counter, currentCummOffset);
  }
}

void EcalRawToDigiGPU::produce(edm::Event& event, edm::EventSetup const& setup) {
  cms::cuda::ScopedContextProduce ctx{cudaState_};

  // get the number of channels
  outputGPU_.digisEB.size = outputCPU_.nchannels[0];
  outputGPU_.digisEE.size = outputCPU_.nchannels[1];

  ctx.emplace(event, digisEBToken_, std::move(outputGPU_.digisEB));
  ctx.emplace(event, digisEEToken_, std::move(outputGPU_.digisEE));

  // reset ptrs that are carried as members
  outputCPU_.nchannels.reset();
}
```
my guess is that by **not** calling `ecal::raw::entryPoint(...)`, `outputCPU_.nchannels` is not properly set, and `outputGPU_.digisEB.size` gets a random value (same for EE).

**Comment by fwyzard** [comment]
So, it might be enough to add
```c++
  outputCPU_.nchannels[0] = 0;
  outputCPU_.nchannels[1] = 0;
```
right before
```
  // unpack if at least one FED has data
  if (counter > 0) {
    ecal::raw::entryPoint(
        inputCPU, inputGPU, outputGPU_, scratchGPU, outputCPU_, conditions, ctx.stream(), counter, currentCummOffset);
  }
```

**Comment by fwyzard** [comment]
or there may be other fields that should be initialised properly instead of skipping the call altogether - I don't know by heart

**Comment by thomreis** [comment]
Yes that is my guess as well. Checking that now.

**Comment by thomreis** [comment]
Confirmed.

**Comment by thomreis** [comment]
So
```
  // output cpu
  outputCPU_ = {cms::cuda::make_host_unique<uint32_t[]>(2, ctx.stream())};
```
in https://github.com/cms-sw/cmssw/blob/master/EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc#L108 does not initialise the object?

**Comment by fwyzard** [comment]
I think it just allocates the memory, but doesn't perform any initialisation.

**Comment by fwyzard** [comment]
By the way, looking again at the code, it's a bit of a waste to deallocate and reallocate 2 integers at every event...
It should be few ms faster to allocate them once (in the constructor, but only if CUDA is available) and simply resetting the values to 0 at the end of produce.

But let's keep this separate from the fix itself.

**Comment by thomreis** [comment]
PRs with the fix for the ECAL crash:
- master #34765 
- 12_0_X #34766 
- 11_3_X #34768

**Comment by mzarucki** [comment]
Hi all,

Just wanted to confirm with you that running our Hilton GPU tests over run 343762 with all three PRs (Pixel https://github.com/cms-sw/cmssw/pull/34684, HCAL https://github.com/cms-sw/cmssw/pull/34750 and ECAL https://github.com/cms-sw/cmssw/pull/34768) on top of _CMSSW_11_3_3_ we do not see any more crashes (as documented in this [e-log](http://cmsonline.cern.ch/cms-elog/1121989)).

Thank you for the quick reaction.

Best regards,
Mateusz on behalf of FOG

**Comment by perrotta** [comment]
Can this issue get closed, then?

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mzarucki** [comment]
Dear all,

From the FOG side, I would like to report that we have tested the full GPU menu in [_CMSSW_11_3_4_](https://github.com/cms-sw/cmssw/releases/CMSSW_11_3_4) in [run 344449](https://cmsoms.cern.ch/cms/runs/report?cms_run=344449) with ECAL, HCAL and Pixel out of the run and we saw no issues (as reported in this [e-log](http://cmsonline.cern.ch/cms-elog/1122504) and today's [Daily Run meeting](http://schwick.web.cern.ch/schwick/rctools/dailyReport/detailReport/display/2021-08-10) just now). This confirms that the updated protections as working well.

Best regards,
Mateusz on behalf of FOG
