### ISSUE TITLE
duplicated dictionaries in IB CMSSW_12_0_X_2021-07-16-2300 

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34533]
https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py/slc7_amd64_gcc900/www/fri/12.0-fri-23/CMSSW_12_0_X_2021-07-16-2300/testLogs/dupDict-edmPD.log

<h3> Information about duplicated dictionaries or dictionaries defined in the wrong place (lib).  </h3>
<h3>  </h3>

object found multiple times | libs/xml files the object is found in
-- | --
CaloTrkProcessing | **pluginCalibCalorimetryEcalTrivialCondModules.so****pluginSimG4CMSCaloPlugins.so**
HFChamberSensitiveDetector | **pluginSimG4CMSHcalForwardLibWriter.so****pluginSimG4CMSShowerLibraryProducerPlugins.so**
HFWedgeSensitiveDetector | **pluginSimG4CMSHcalForwardLibWriter.so****pluginSimG4CMSShowerLibraryProducerPlugins.so**

**Comment by qliphy** [comment]
Related to https://github.com/cms-sw/cmssw/pull/34510/

**Comment by qliphy** [comment]
assign simulation

**Comment by civanch** [comment]
@qliphy , @bsunanda , may be we revert this MR for some time?

**Comment by qliphy** [comment]
@civanch  You mean we revert https://github.com/cms-sw/cmssw/pull/34510 , right?

**Comment by civanch** [comment]
Yes, exactly.

**Comment by qliphy** [comment]
ok, done with https://github.com/cms-sw/cmssw/pull/34535

**Comment by Dr15Jones** [comment]
This should not have been reverted. The problem was a false positive caused by looking at a patch build of an IB instead of a full build. The duplicate dictionary checker is not smart enough to realize that there were two places it was looking for the plugins, in the patch area and in the full area associated to the patch. The plugin system will always first pick the items from the patch and only if a plugin is not in the patch will it fallback to the full area. So there was no problem.

**Comment by smuzaffar** [comment]
@qliphy, I agree with @Dr15Jones . the duplicate dicts errors are only on patch builds. A full builds should have cleaned up these errors. There was no need to revert #34510.

**Comment by qliphy** [comment]
@smuzaffar @Dr15Jones  Ah, ok, thanks!  Sorry I didn't know that.  I will recover #34510 then if there is no further comment.
