### ISSUE TITLE
IB error in workflow 4007.0:   invalid PDG id: 9010221

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34586]
In IB CMSSW_12_0_X_2021-07-21-2300

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-21-2300/pyRelValMatrixLogs/run/4007.0_QCD_Pt_30_80_BCtoE_8TeV+QCD_Pt_30_80_BCtoE_8TeV+DIGIPU1+RECOPUDBG/step1_QCD_Pt_30_80_BCtoE_8TeV+QCD_Pt_30_80_BCtoE_8TeV+DIGIPU1+RECOPUDBG.log#/267-267

----- Begin Fatal Exception 22-Jul-2021 09:11:33 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 6 stream: 2
   [1] Running path 'generation_step'
   [2] Calling method for module GenParticleProducer/'genParticlesForFilter'
Exception Message:
invalid PDG id: 9010221

Pythia8 is upgraded to version 306 in this IB:
https://github.com/cms-sw/cmsdist/pull/7116

Is this related?  @mkirsano

**Comment by qliphy** [comment]
assign generators

**Comment by mkirsano** [comment]
I will have a look. @smrenna probably again some PDG code is changed.

**Comment by agrohsje** [comment]
hi @mkirsano. are you able to follow-up?

**Comment by mkirsano** [comment]
Hello, yes, I am looking

27/07/21 18:49, agrohsje пишет:

**Comment by smuzaffar** [comment]
any update?

**Comment by qliphy** [comment]
From [1] https://github.com/cms-sw/cmssw/blob/master/SimGeneral/HepPDTESSource/data/particle.tbl#L372
and  [2] https://github.com/cms-sw/cmssw/blob/master/SimGeneral/HepPDTESSource/data/pythiaparticle.tbl#L372
the pid for f0(980) and several other particles are different.

If I change manually above [2] to match [1], then the error with workflow 4007.0 seems to be gone.

@cms-sw/generators-l2  @smrenna  Would you please have a look at [1] and [2] and suggest what changes to be done (e.g. should we update [2] according to [1])?

BTW: this error seems to be rare and depending on random numbers.   Occasionally it will produce a f0(980) particle and then trigger the error. 
You can reproduce the error with
runTheMatrix.py -l 4007.0 --job-reports -t 4 --ibeos
however, with 
runTheMatrix.py -l 4007.0 --job-reports -t 2 --ibeos  
or other thread numbers,  there is no such error.

**Comment by smuzaffar** [comment]
looks like woprkflow 4007.0 is now running successfully in the IBs. Do we know which PR fixed it? Was it a side effect of https://github.com/cms-sw/cmssw/pull/34710 ?

**Comment by agrohsje** [comment]
i don't see any connection. it is not related to pythia8. i think simulation should decide and comment more on the 2 files and what we should adjust. @smrenna can confirm but i don't think this is about gen itself.

**Comment by smrenna** [comment]
As far as I can tell, this has to do with a definition in HepPDT.

-- Steve


From: agrohsje ***@***.***>
Reply-To: cms-sw/cmssw ***@***.***>
Date: Thursday, August 19, 2021 at 11:26 AM
To: cms-sw/cmssw ***@***.***>
Cc: Stephen Mrenna ***@***.***>, Mention ***@***.***>
Subject: Re: [cms-sw/cmssw] IB error in workflow 4007.0: invalid PDG id: 9010221 (#34586)


i don't see any connection. it is not related to pythia8. i think simulation should decide and comment more on the 2 files and what we should adjust. @smrenna<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smrenna&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P6TR6eMSzDEOLYeqW0ECsQ&m=zZtFWNtHth4FZ6DbEtde0kFdAnhhnSBJ7Qp7XUdn6VI&s=0gR32p1YDO6X6sEmGZLKaWAvAZpOB44oNuiRUODBMn8&e=> can confirm but i don't think this is about gen itself.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cms-2Dsw_cmssw_issues_34586-23issuecomment-2D902055348&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P6TR6eMSzDEOLYeqW0ECsQ&m=zZtFWNtHth4FZ6DbEtde0kFdAnhhnSBJ7Qp7XUdn6VI&s=TG2la5Dq_OmEQAvY0NKKslpJ6StddagRZoRT0dNDs_w&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABLSEJDSUZYCMWZIFOWXBBTT5UWBNANCNFSM5AZ5MRTA&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P6TR6eMSzDEOLYeqW0ECsQ&m=zZtFWNtHth4FZ6DbEtde0kFdAnhhnSBJ7Qp7XUdn6VI&s=iJo6gOHsgkCKXC3X1QO0hDBPdVWrUM0tEPh-qpR51nA&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P6TR6eMSzDEOLYeqW0ECsQ&m=zZtFWNtHth4FZ6DbEtde0kFdAnhhnSBJ7Qp7XUdn6VI&s=KrXDx5SxdwZTf9J7TV2Gz7-9H8R5dUeq1LMmP87hqSg&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P6TR6eMSzDEOLYeqW0ECsQ&m=zZtFWNtHth4FZ6DbEtde0kFdAnhhnSBJ7Qp7XUdn6VI&s=QAfWtHrAx_3r20mROtk5nbw-i6a9sQc33IXYf1athDg&e=>.

**Comment by mrodozov** [comment]
I checked this IBs, for which it was failing
CMSSW_12_1_X_2021-08-17-2300
CMSSW_12_1_X_2021-08-16-2300
and it ran for both. So it's not due to pr that got in

**Comment by qliphy** [comment]
> looks like woprkflow 4007.0 is now running successfully in the IBs. Do we know which PR fixed it? Was it a side effect of #34710 ?

Yes, I think the random number gets changes. 
As mentioned above,  Occasionally this workflow will produce a f0(980) particle and then trigger the error.

I just did a test with CMSSW_12_1_X_2021-08-19-1100
it seems the error now appears at 17th event:

runTheMatrix.py -l 4007.0 --job-reports -t 4 --ibeos --command="-n 1000"
...
Begin processing the 17th record. Run 1, Event 17, LumiSection 1 on stream 3 at 20-Aug-2021 03:45:15.933 CEST
----- Begin Fatal Exception 20-Aug-2021 03:45:15 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 16 stream: 2
   [1] Running path 'simulation_step'
   [2] Calling method for module GenParticleProducer/'genParticlesForFilter'
Exception Message:

**Comment by agrohsje** [comment]
@civanch this is the PR we just talked about in ORP.

**Comment by perrotta** [comment]
assign simulation

**Comment by civanch** [comment]
Hi all,

data file [1] includes correct PDG numbers for a0(980), a+-(980), and f0(980). This correspond to Geant4 data and PDG data. There is a small difference in mass, which does not affect anything. There is also uncertainty in width of these mesons, which is natural due to complex dynamic quark continence of these mesons. 

From my point of view, [1] should be used and [2] should be removed. PDG codes inside [2] are incorrect for these mesons.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@qliphy @cms-sw/generators-l2 can this issus get closed now?

**Comment by qliphy** [comment]
Yes, should be fixed now by #35262
