### ISSUE TITLE
[GCC11] RecoPixelVertexing/PixelTrackFitting error: identifier "Eigen::fix<(int)-1> " is undefined in device code

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#34918]
Build log: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc11/CMSSW_12_1_X_2021-08-16-1100/RecoPixelVertexing/PixelTrackFitting

Error message example:
```
(...)/include/eigen3/Eigen/src/LU/PartialPivLU.h(412): error: identifier "Eigen::fix<(int)-1> " is undefined in device code
```

**Comment by makortel** [comment]
assign reconstruction, heterogeneous

**Comment by fwyzard** [comment]
It's not clear to me if this is a problem with CUDA/NVCC or with our changes to Eigen (and the older versions of NVCC were more tolerant).

So I've started a discussion about it on the NVIDIA forum ( https://forums.developer.nvidia.com/t/breaking-change-for-eigen-code-in-nvcc-11-3-and-later-vs-nvcc-11-2-and-earlier/186800 ) and opened a bug report about it ( https://developer.nvidia.com/nvidia_bug/3361469 ).

If it turns out this is a problem with (our changes to) Eigen, I think I've also found a workaround we can use, and I have a merge request for upstream Eigen that should address this: https://gitlab.com/libeigen/eigen/-/merge_requests/586 .

**Comment by fwyzard** [comment]
A backport for the tentative fix is in https://github.com/cms-externals/eigen-git-mirror/pull/7 .

**Comment by smuzaffar** [comment]
this has been fixed
