### ISSUE TITLE
CSC and DT Alignment in Phase2 MC

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#36012]
This is to follow the discussion on `applyAlignment = True ` for Phase-2 DT and CSC.
Thanks to the report from @cvuosalo which shows that we currently apply alignment for Phase-2 DD4hep, 
https://indico.cern.ch/event/1093855/contributions/4600336/attachments/2340006/3990240/dd4migratestatus05Nov2021Update.pdf

Checking more the config, it seems we apply alignment in both DDD and DD4hep for both CSC and DT,
https://github.com/cms-sw/cmssw/blob/master/Geometry/CSCGeometryBuilder/plugins/CSCGeometryESModule.cc#L85
https://github.com/cms-sw/cmssw/blob/master/Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.cc
(no config to overwrite this)

It is unclear if alignment should be there, as we are simulating the ideal/perfect alignment for Phase-2 detector AFAIU. The way that Tracker deals with this is to introduce the switch to OFF in 2026 geometry dictionary,
https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2026Geometry.py#L180

Should we do the same for DT and CSC?

**Comment by srimanob** [comment]
assign geometry, dt-dpg, csc-dpg

**Comment by srimanob** [comment]
assign upgrade

**Comment by battibass** [comment]
@srimanob : I don't know if this is still relevant, but, in case, I note down my recalls and opinion here:

When I was dealing with MUO POG activities directly, I recall that the decision was intentional, in order to avoid making Phase-2 high-pT analysis results overly optimistic. But we are talking about the Technical Proposal / Scope Document days.

After that, plenty of studies were performed, mostly the ones from MUON-17-001, of which I extract the following results:

https://cds.cern.ch/record/2703645/files/Figure_014-a.png
https://cds.cern.ch/record/2703645/files/Figure_014-b.png

Though made using the Run-2 tracker with misalignments applied, they seem to point to the fact that, at least concerning the core, the resolution of the pT assignment for high-energy muons would not change too much. Though I do not recall what happens for tails of the resolution (which are also relevant for high-pT searches).

Anyhow, I guess that the decision about how to deal with that is more on the shoulders of @cms-sw/muon-pog-l2 than on the ones of DPGs. One other thing I would consider (even if less relevant), is consistency with what GEMs are doing as well, hence I also include @cms-sw/gem-dpg-l2 .

**Comment by battibass** [comment]
Of course, apologies for getting to this so late.

**Comment by sscruz** [comment]
@srimanob sorry for being late on this. We have discussed a bit internally and agreed that the reason why choice was made in the past is still valid (although as Carlo points out this is likely not to make a difference). So because of that we think it's reasonable to keep the CSC and DT alignment as it is. Let us know if there are other constraints we should take into account. 
Cheers,
Sergio (also for @gkaratha )

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
This PR can close. The alignment is available in Phase-2 DD4hep workflow.
