### ISSUE TITLE
No compression defined in SKIM output

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#37150]
It seems skim outputs does not have compression by default. This includes
- output module which clones from AOD (e.g. EXOMONOPOLE)
- new defined output module (e.g. BPHSkim)

`cmsDriver.py step3 --conditions auto:run2_data -s RAW2DIGI,L1Reco,RECO,SKIM:EXOMONOPOLE+BPHSkim,PAT --datatier AOD,MINIAOD --eventcontent AOD,MINIAOD --data --process reRECO --scenario pp --era Run2_2018 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2018 --python MONOPOLE_cfg.py -n 500 --no_exec --filein file:root://eoscms.cern.ch//eos/cms/store/data/Run2018D/EGamma/RAW/v1/000/320/822/00000/1441432A-8997-E811-8BD0-FA163EA21B5C.root --fileout file:step3.root --nThreads 8`

Comparing outputs from above cmsDriver with and without compression from Monopole:
- Output without compression: 1.86 MB/event
- Output with LZMA-level4: 1.66 MB/event
- Output with ZSTD-level4: 1.74 MB/event 

Should the compression be default for SKIM outputs? 
Should the code be manage centrally (if possible), or each skim takes care for compression config?

**Comment by makortel** [comment]
> It seems skim outputs does not have compression by default

Actually the default behavior of `PoolOutputModule` is to compress with ZLIB-9 (and there is no way to disable compression). Changing the default to ZSTD-4 was agreed in core software meeting two weeks ago (PR to be done soon) because it seems to be better than ZLIB-9 in all (tested) cases (like here).

I don't know the history, but I'd guess the default compression was deemed good enough for skims. How much do skims use disk (tape?) space compared e.g. to AOD? LZMA has a sizable computational cost (including connection to CPU efficiency), so that tradeoff would require a careful study.

**Comment by makortel** [comment]
assign core, pdmv

**Comment by srimanob** [comment]
As I see on the skims I use, they are on tape also, e.g.
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FMET%2FRun2016G-EXOMONOPOLE-21Feb2020_UL2016-v1%2FUSER

**Comment by srimanob** [comment]
As clarification that compression is done by default, I think this ticket can be closed.
