### ISSUE TITLE
Problem parsing the enum in reco::Muon::Selector

### ISSUE THREAD

**Issue by mariadalfonso** [cms-sw/cmssw#38899]
Since this PR [0] we have some problem with parsing the enum defined in the 
DataFormats/MuonReco/interface)/MuonSelectors.h

This issue affects the nano[1], now the ID are all empty; at the same time this has been seen also in another places[2].

This doesn't work
`tightId = Var("passed('CutBasedIdTight')",bool,doc="cut-based ID, tight WP"),
`
this yes

`tightId = Var("passed(8)",bool,doc="cut-based ID, tight WP"),
`

We need some help from the core group.

[0] https://github.com/cms-sw/cmssw/pull/36179/files
[1] https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/muons_cff.py#L128
[2] https://github.com/cms-sw/cmssw/blob/47dded9ac5760e86d4ce6aaa18189f10765ef303/DQM/GEM/python/gemEfficiencyAnalyzer_cff.py#L9

@jpata @clacaputo @slava77  @sscruz

**Comment by mariadalfonso** [comment]
assign core,xpog

**Comment by makortel** [comment]
Can the comment in https://github.com/cms-sw/cmssw/blob/47dded9ac5760e86d4ce6aaa18189f10765ef303/DQM/GEM/python/gemEfficiencyAnalyzer_cff.py#L9-L10 be interpreted that the name worked in 12_2_0 but not in 12_3_0?

One big difference between 12_2_0 and 12_3_0 is ROOT, 6.22 vs. 6.24.

**Comment by makortel** [comment]
I see the `SimpleCandidateFlatTableProducer` uses
https://github.com/cms-sw/cmssw/blob/a1ee449d0c95cbe0ce77e39a3ba396879d0437a4/PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h#L170-L171
uses `StringObjectFunction` and `StringCutObjectSelector` that use ROOT underneath.

**Comment by makortel** [comment]
@mariadalfonso Could you provide a recipe to reproduce? I tried with the unit test https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/test/testCutParser.cc with
```diff
@@ -73,9 +73,9 @@ void testCutParser::checkHit(const std::string &cut, bool res, const SiStripRecH
 void testCutParser::checkMuon(const std::string &cut, bool res, const reco::Muon &mu) {
   edm::TypeWithDict t(typeid(reco::Muon));
   o = edm::ObjectWithDict(t, const_cast<void *>(static_cast<const void *>(&mu)));
-  sel.reset();
   for (int lazy = 0; lazy <= 1; ++lazy) {
     std::cerr << "parsing " << (lazy ? "lazy " : "") << "cut: \"" << cut << "\"" << std::endl;
+    sel.reset();
     CPPUNIT_ASSERT(reco::parser::cutParser<reco::Muon>(cut, sel, lazy));
     CPPUNIT_ASSERT((*sel)(o) == res);
     StringCutObjectSelector<reco::Muon> select(cut, lazy);
@@ -245,4 +245,11 @@ void testCutParser::checkAll() {
   CPPUNIT_ASSERT((!hitThrow.hasPositionAndError()) || (hitThrow.localPosition().x() == 1));
   checkHit("!hasPositionAndError || (localPosition.x = 1)", true, hitOk);
   checkHit("!hasPositionAndError || (localPosition.x = 1)", true, hitThrow);
+
+  reco::Muon muon;
+  muon.setSelector(reco::Muon::CutBasedIdTight, true);
+  checkMuon("passed('CutBasedIdTight')", true, muon);
+  checkMuon("!passed('CutBasedIdTight')", false, muon);
+  checkMuon("passed('CutBasedIdLoose')", false, muon);
+  checkMuon("!passed('CutBasedIdLoose')", true, muon);
 }
```
but was not able to reproduce the problem.

**Comment by vlimant** [comment]
`CPPUNIT_ASSERT_EQUAL(StringToEnumValue<reco::Muon::Selector>("MvaIDwpTight"),long(reco::Muon::MvaIDwpTight));
`
 is a way to produce an error, from CMSSW_12_4_4

The issue seems to be that the parser casts the enum to int before recasting to any other value, loosing most information along the way.

The hard way to fix : https://github.com/cms-sw/cmssw/compare/CMSSW_12_4_X...vlimant:cmssw:fw_change_for_nano_muon_masks letting the parser always use long for enumerators.

The nicer way : https://github.com/cms-sw/cmssw/compare/CMSSW_12_4_X...vlimant:cmssw:nano_change_for_nano_muon_masks not abusing the enum to store bit mask, but rather store the bit number instead. This has implications on user's code, most likely and would probably have to be done with care.

With both separately, the issue in nano muons is gone.

**Comment by vlimant** [comment]
BTW @mariadalfonso, as we were discussing, the parser for muon was partially broken even before, when `LowPtMvaMedium = 1UL << 33` was introduced, as it's beyond what unsigned int can store.

**Comment by sscruz** [comment]
thanks a lot for this @vlimant 
I personally would prefer the option in https://github.com/cms-sw/cmssw/compare/CMSSW_12_4_X...vlimant:cmssw:nano_change_for_nano_muon_masks, since it is much cleaner. This shouldn't have an impact in users code that is using the recommended way of accessing the selectors, which is through the enum

**Comment by mariadalfonso** [comment]
is ok with everybody in updating the data format ?
if so, JR can make a PR to both master and 12_4.

**Comment by sscruz** [comment]
It looks good for us (MUO)

**Comment by mariadalfonso** [comment]
+xpog

**Comment by swertz** [comment]
@cms-sw/core-l2 I think this can be closed?

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
