### ISSUE TITLE
Issues related to FastTimerService and HLT

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#39756]
I just want to report here two problems about FastTimerService and the HLT online DQM .

1) [DQM: HLT / TimerService / Running on AMD EPYC 7763 64-Core Processor with 24 streams on 32 threads](https://cmsweb.cern.ch/dqm/online/start?runnr=360459;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads;focus=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads/event%20time_thread_byls;zoom=yes;)

![image](https://user-images.githubusercontent.com/6177433/196465075-9cb5cb8e-0a75-44ce-9d93-44634a6f954a.png)

Here the timing seems wrong of a factor of 2. Our offline measurements showed that the timing should be above 300 ms at high pileup.

2)  Plots timing [VsPU](https://cmsweb.cern.ch/dqm/online/start?runnr=360459;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads;focus=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads/event%20time_real_VsPU;zoom=yes;) and [VsSCAL](https://cmsweb.cern.ch/dqm/online/start?runnr=360459;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads;focus=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads/event%20allocated_VsScalLumi;zoom=yes;) are empty.

@cms-sw/hlt-l2

**Comment by makortel** [comment]
assign hlt

**Comment by missirol** [comment]
(Noted, I will try to understand this in the next days, unless it is considered important to fix this asap.)

FYI: @fwyzard

**Comment by fwyzard** [comment]
> Plots timing [VsPU](https://cmsweb.cern.ch/dqm/online/start?runnr=360459;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads;focus=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads/event%20time_real_VsPU;zoom=yes;) and [VsSCAL](https://cmsweb.cern.ch/dqm/online/start?runnr=360459;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads;focus=HLT/TimerService/Running%20on%20AMD%20EPYC%207763%2064-Core%20Processor%20with%2024%20streams%20on%2032%20threads/event%20allocated_VsScalLumi;zoom=yes;) are empty.

The reason is that the `FastTimerServiceClient` that is responsible for filling those plots is trying to read the information about luminosity and pileup from SCAL, which does not exist any more in Run-3.

I inquired about it a few months ago, and according to @mmusich's [answer](https://cms-talk.web.cern.ch/t/access-to-the-online-luminosity-from-the-hlt-or-online-dqm/12712) the solution would be to change the code to read those information from 
> the `OnlineLuminosityRecord` from the `onlineMetaDataDigis`.

Unfortunately I never had time to work on the changes :-/

**Comment by fwyzard** [comment]
> Here the timing seems wrong of a factor of 2. Our offline measurements showed that the timing should be above 300 ms at high pileup.

@silviodonato keep in mind that as long as the cpu usage is below ~70%, it's almost like running without hyperthreading, so it would make sense to observe a timing roughly a factor 2 (I'd expect 1.8x) faster than on a fully used machine.

**Comment by fwyzard** [comment]
OK, some more information: I've re-run over the first lumisections of run 360459 (the same one of @silviodonato's plot), using similar conditions as what we have online (`CMSSW_12_4_10`, same menu and global tag, 8 jobs times 32 threads/24 streams) and looked at the **CPU time** (Silvio's plot is for CPU time):

![image](https://user-images.githubusercontent.com/4069793/196517825-bc4058ce-083a-4e4a-82f2-682f954d6e7a.png)

Taking `total - other` (which is what the `FastTimerService` plots) I get `260 ms/ev`:
![image](https://user-images.githubusercontent.com/4069793/196518495-10f40b5f-9182-4ac2-a6d3-e7208fdf2eeb.png)


If I zoom on the DQM plot we see that for the first 2-3 lumisections the CPU time measured on the HLT farm was indeed `258 ms/ev`:
![image](https://user-images.githubusercontent.com/4069793/196518986-b63d42c5-ad31-49c3-8897-591c75b8771b.png)

I'm looking at the first two lumisections because at the beginning of the run the HLT has buffered some data, while it was loading the application, starting the jobs, and getting the first conditions -- so the whole farm will run at the maximum capacity until the buffer has been drained.

Keeping all these effects in mind, I would say that the online measurement is in very good agreement with an online-like measurement done in the same conditions 👍🏻 

One last comment is about the CPU time vs real (wall clock) time: of course what actually matters for keeping up with the L1 rate is the latter.

The plot for the real time looks similar, just a bit higher:
![image](https://user-images.githubusercontent.com/4069793/196520089-3f230316-1133-4095-a93d-b7e72fcfac22.png)

Zooming on the first lumisections shows a similar effect, with a peak for the first lumisection around `298 ms/ev`:
![image](https://user-images.githubusercontent.com/4069793/196520328-2e0d5165-3c15-46d3-95aa-cef2a7b09506.png)

From my online-like measurement I get `417 - 118 = 299 ms/ev` for the real time:
![image](https://user-images.githubusercontent.com/4069793/196520531-297f1e0c-0f1b-4016-acf7-0b00eb9c5dd6.png)
which is also very consistent with the online value for the first lumisection.

So... the measurements done on the online machines reproduce pretty accurately the HLT timing measured online (better than I imagined before making this check).

And the comparison between the timing value of `~ 200 ms/ev` (`~210 ms/ev` real) after the first lumisections and the initial peak of `260 ms/ev` (`~300 ms/ev` real) gives us an indication of the effect of hyperthreading at the level of occupancy we have around pileup 50.

**Comment by silviodonato** [comment]
Thanks a lot @fwyzard ! So
- we should/can check the timing including the hyper-threading effect by looking at the first lumisections
- the DQM plot doesn't include the "others" part (~10%).

**Comment by fwyzard** [comment]
> we should/can check the timing including the hyper-threading effect by looking at the first lumisections

Yes, but only for runs that start already in stable beams, otherwise there is very little to run.

> the DQM plot doesn't include the "others" part (~10%).

Correct - and the difference is more significative for "real time" than for "cpu time".

**Comment by missirol** [comment]
+hlt
