### ISSUE TITLE
Invalid json values in StatisticsSenderService UDP packages to CMSSW Popularity service

### ISSUE THREAD

**Issue by mrceyhun** [cms-sw/cmssw#39966]
**Affected service**
As CMS Monitoring, our CMSSSW Popularity service(cms udp collector) collects UDP packages which are sent from CMSSW services. The url and the port of the service can be found in site configurations: i.e. `/cvmfs/cms.cern.ch/SITECONF/T0_CH_CERN/JobConfig/site-local-config_EOS_PILOT_EC.xml`, `<statistics-destination name=` part. And AFAIK, this CMSSW service sends the UDP packages: [cms-sw/cmssw/Utilities/StorageFactory/src/StatisticsSenderService.cc](https://github.com/cms-sw/cmssw/blob/b4a3539184ea6103abbb842028ec43d3e111ce26/Utilities/StorageFactory/src/StatisticsSenderService.cc#L228)

**Bug description**
In incoming UDP packages, some JSONs include invalid character for `read_single_sigma` field, see:  `"read_single_sigma":-nan`. `-nan` has `-` prefix. For security reasons, full JSON is not shared.

**Request and solutions**
We can parse these values in our end but the best approach is to fix it in producer side.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@mrceyhun Could you share me privately (e.g. via mattermost or email) the full JSON?

**Comment by makortel** [comment]
We had this problem earlier in https://github.com/cms-sw/cmssw/issues/29412 and https://github.com/cms-sw/cmssw/issues/35142, and a related problem in https://github.com/cms-sw/cmssw/issues/36349. The NaNs were fixed with https://github.com/cms-sw/cmssw/pull/35362, and the latter problem with https://github.com/cms-sw/cmssw/pull/35505. Both fixes should have been backported to all relevant old release cycles.

I see we also added CMSSW version to the StatisticsSenderService in https://github.com/cms-sw/cmssw/pull/37220, that was also backported to the same set of old release cycles.

@mrceyhun shared the message content to me privately, and it did not have the CMSSW version, so it sounds very likely to me that these jobs are using an old CMSSW release that does not have the fixes.

**Comment by makortel** [comment]
With further correlation attempts with @mrceyhun it seems plausible that the jobs used CMSSW versions in 10_6_X (part of the UL campaigns) earlier than 10_6_29_patch1 (which was the first to contain the fix https://github.com/cms-sw/cmssw/pull/35505). So it seems there we can't really do anything.

(I also noticed that no 10_6_X release has been cut after the backport of #37220 was merged)

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close

**Comment by makortel** [comment]
Written that, if any further investigation indicates that a CMSSW version with the fix still results in invalid JSON, let's reopen this issue (or open a new one).
