### ISSUE TITLE
Change in ele_trigger after adding HLT to Phase-2 workflow

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#40700]
This is to follow up on the difference in ele_trigger plot after merging https://github.com/cms-sw/cmssw/pull/40412

See comment: https://github.com/cms-sw/cmssw/pull/40665#issuecomment-1416017886

**Comment by srimanob** [comment]
assign upgrade

**Comment by missirol** [comment]
What is the issue exactly?

This kind of difference is expected, because [that MonitorElement is filled](https://github.com/cms-sw/cmssw/blob/a31eb307f66ca16c2fd799a5b44539d030792dec/DQMOffline/EGamma/plugins/ElectronGeneralAnalyzer.cc#L96) based on [`TriggerResults::HLT`](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMOffline/EGamma/python/electronGeneralAnalyzer_cfi.py#L20), and #40412 changed the HLT menu used in those wfs (thus, the change in the MonitorElement).

That said, this MonitorElement does not seem very useful to me (we have a dedicated plugin to monitor the TriggerResults of HLT in the offline DQM, i.e. [HLTFiltersDQMonitor](https://github.com/cms-sw/cmssw/blob/a31eb307f66ca16c2fd799a5b44539d030792dec/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L8)). Maybe it could be removed, but this is up to DQM and E/Gamma.

**Comment by missirol** [comment]
please close

The extra histograms that introduced confusion were removed in #40788 and #40806.

**Comment by srimanob** [comment]
+upgrade
