### ISSUE TITLE
Add tests or workflows that read existing scouting data

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#41040]
In order to make sure we retain the ability to read old scouting data (which is part of RAW backwards compatibility guarantees), it would be good to add workflows (or other tests) that read in old scouting data.

Following up a comment in https://github.com/cms-sw/cmssw/pull/41025#issuecomment-1465863947.

**Comment by makortel** [comment]
assign hlt, pdmv

**Comment by missirol** [comment]
@makortel, thanks for opening this issue.

My first naive thought was to add unit test(s) in `DataFormats/Scouting/test/`.

[This](https://gist.github.com/missirol/8f0799e460a2945c0207f08512b612f4) is an example for the Run-3 scouting data formats. In my understanding, this simple cfg should fail if a non-backward-compatible change is introduced.

I wonder if you had something different in mind, since you included PdmV.

Is such a unit test worth adding ?

**Comment by makortel** [comment]
I thought a straightforward way would be to add a workflow in `runTheMatrix`, but I'd be fine with a unit test as well.

**Comment by missirol** [comment]
I'm trying to take the unit test of https://github.com/cms-sw/cmssw/issues/41040#issuecomment-1466272571 one test further, writing a test with 2 steps:

 - step 1: read the Scouting collections from an input file, and write them to an EDM output file;
 - step 2: dump the content of the Scouting collections in the output of step-1 to a text file, and compare that text file to a reference.

Step-1 should fail if non-bckwd-compatible changes are introduced.

Step-2 is meant to check that the values of the products remain the same. The 'con' of step-2 is that (1) one needs to add this reference file, and (2) this reference file might have to be updated in the future (for example, if a certain variable is renamed). Also, this reference file needs to be 'small' if it is to stay in the `test/` folder (as opposed to cms-data).

Does this go in the right direction? Any suggestions?

This attempt is in
https://github.com/missirol/cmssw/tree/ad597a6493b98b5e192aa628e149031d6627e24b/DataFormats/Scouting/test

(caveat: the test currently fails, because printing of [`Run3ScoutingHitPatternPOD`](https://github.com/missirol/cmssw/blob/ad597a6493b98b5e192aa628e149031d6627e24b/DataFormats/Scouting/test/testRun3Scouting_step2_output_expected.txt#L487) needs to improved)

**Comment by Dr15Jones** [comment]
@missirol instead of doing it in 2 steps, I'd suggest creating a EDAnalyzer which takes as parameters the values you expect and then have the EDAnalyzer read the scouting object from the event and compare the values in the scouting object to the values given in the parameter.

**Comment by wddgit** [comment]
I'm working on the new unit tests now. I'm planning on following the pattern in #41631. The only difference will be that I will make one test for Run 3 formats and another test for the rest of them. So I will group them and not have one test per class type. If you have any comments to that pattern, then it would be easier if I knew now and I could just do it that way in the first draft.

Is this a complete list of Scouting data classes? I'm just listing all the files in the only directory that I know about. Are there any of them that were never used and never will be used to store data? Are there any still under rapid development where I should just wait and not waste time on them yet?

Singularity> ls DataFormats/Scouting/interface/
Run3ScoutingCaloJet.h
Run3ScoutingElectron.h
Run3ScoutingHitPatternPOD.h
Run3ScoutingMuon.h
Run3ScoutingPFJet.h
Run3ScoutingParticle.h
Run3ScoutingPhoton.h
Run3ScoutingTrack.h
Run3ScoutingVertex.h
ScoutingCaloJet.h
ScoutingElectron.h
ScoutingMuon.h
ScoutingPFJet.h
ScoutingParticle.h
ScoutingPhoton.h
ScoutingTrack.h
ScoutingVertex.h

**Comment by wddgit** [comment]
One thing I noticed that is mildly odd. Some of these classes have class version 2 in the classes_def.xml file. I'm not sure if this is still true, but versions 0, 1, 2 are special values to ROOT. I think it causes extra byte count information to be included in the persistent format or something like that and different behavior... Was this intentional? We usually start the version at 3. I don't know whether this is a real problem or not, but it is not the usual way I have seen these before.

Some of these classes have multiple versions. Do we need test files with all versions or can the older ones be ignored and just start out with the current latest version? I think we only need the ones where there is actually data or monte carlo in long term storage somewhere.

**Comment by wddgit** [comment]
I guess given that all the version 2 classes are run 2 classes, there is nothing that can be done about it at this point. I'll just ignore that. Probably didn't matter much since no one noticed before.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
Tests were added in https://github.com/cms-sw/cmssw/pull/41834 and in https://github.com/cms-sw/cmssw/pull/41913 (with mock data).

**Comment by makortel** [comment]
+core
