### ISSUE TITLE
Cut on Jets pT in AOD

### ISSUE THREAD

**Issue by clacaputo** [cms-sw/cmssw#41105]
As spotted by @slava77, looking at the number of jets in a recent relval (this was in /RelValZMM_PU_13p6/CMSSW_12_4_11_patch3-PU_124X_mcRun3_2022_realistic_v12_PDMVRELVALS167-v1/AODSIM (pileup 2022_LHC_Simulation_10h_2h), the nJets distribution has an average of 94  in the ak4PF CHS. It looks like our jet reco even after CHS is filling essentially all phase space available. Are all these jets meaningful? Perhaps some selections could even save some space in AOD.
![image](https://user-images.githubusercontent.com/6500336/226359978-ead3f6b8-0ab3-4ec8-adc9-09f4db60c912.png)

**Comment by clacaputo** [comment]
assign reconstruction

**Comment by clacaputo** [comment]
type jetmet

**Comment by clacaputo** [comment]
@laurenhay, @cms-sw/jetmet-pog-l2  could you please have a look?

**Comment by clacaputo** [comment]
Hi @slava77 , do you have any link to the original jet multiplicity plot?

**Comment by anmalara** [comment]
Hi, to come back to this.
I think that the culprit might be a wrong JEC version that was uploaded for chs jets. 
see the current validation that is done by @rseidita with the new GT for [chs](https://tinyurl.com/2nwz5l3c) and [puppi](https://tinyurl.com/2glpjonz) jets.

Based on this, I think there is no need to adjust any threshold and it would be resolved from the new campaign.
Please do report back if this problem is still there in the future.

**Comment by clacaputo** [comment]
+reconstruction

- solved by new GT, see https://github.com/cms-sw/cmssw/issues/41105#issuecomment-1577101856
