### ISSUE TITLE
No SiStripFedCablingRcd error with D95 Patatrack workflow

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#42196]
When testing workflow `23634.595` or `23634.596` (from https://github.com/cms-sw/cmssw/pull/41011), I face an issue (*). Any clue or I miss something? Thanks. 

To reproduce the error:

1. Checkout the most recent release, i.e. CMSSW_13_2_X_2023-07-05-1100
2. git cms-addpkg Configuration/PyReleaseValidation
3. edit [this line](https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L834), to add D95
4. get the workflow, `runTheMatrix.py --what upgrade -l 23634.595 -t 8 --wm init`
5. Run GEN-SIM, DIGI-HLT, and error will show up in the DQM step (step3 RECO+DQM).

**Update: I think current D88 workflow is also facing the same issue. Not sure why we don't spot it before.**

(*)
```
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 1
   [1] Prefetching for module SiStripMonitorTrack/'HLTSiStripMonitorTrack'
   [2] Calling method for EventSetup module SiStripConnectivity/'sistripconn'
   [3] While getting dependent Record from Record SiStripDetCablingRcd
Exception Message:
No "SiStripFedCablingRcd" record found in the EventSetup.
```

FYI @AdrianoDee @gartung

**Comment by srimanob** [comment]
For new profiling workflow (.59621), it should be OK. The issue is on DQM step. Sorry for the noise @gartung

**Comment by srimanob** [comment]
FYI @cms-sw/trk-dpg-l2

**Comment by mmusich** [comment]
> Prefetching for module SiStripMonitorTrack/'HLTSiStripMonitorTrack

One could naively ask why you run the DQM for a detector that does not exist in the phase2 detector (SiStrip)

**Comment by srimanob** [comment]
> > Prefetching for module SiStripMonitorTrack/'HLTSiStripMonitorTrack
> 
> One could naively ask why you run the DQM for a detector that does not exist in the phase2 detector (SiStrip)

OK, I assumed it was handled somehow internally (like skipping) as default workflows run (23634.0) until the end.  Thx.

**Comment by srimanob** [comment]
The current condition of patatrack wf include `"PixelOnly" in self.suffix`, that results of no workflow for Phase-2. The https://github.com/cms-sw/cmssw/pull/41011 proposes to remove. 

If you have some hints on how this is skipped in normal workflow with DQM available, it is very welcomed. So I can try to avoid using `phase2_common` in many places to add exception. 

Thanks very much.

**Comment by mmusich** [comment]
This happens because here:

https://github.com/cms-sw/cmssw/blob/debf6595c5323faca5b340ad0a865ddc99bb088b/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1392

you have `@standardDQM` which in turn runs `DQMOffline`

https://github.com/cms-sw/cmssw/blob/d9d4aec32230b7d62e51c4622dfd654e8cea106a/DQMOffline/Configuration/python/autoDQM.py#L214

which runs the HLTMonitoring

https://github.com/cms-sw/cmssw/blob/debf6595c5323faca5b340ad0a865ddc99bb088b/DQMOffline/Configuration/python/DQMOffline_cff.py#L182-L186

which is composed by:

https://github.com/cms-sw/cmssw/blob/debf6595c5323faca5b340ad0a865ddc99bb088b/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L208-L210

which finally includes `sistripMonitorHLTsequence`

https://github.com/cms-sw/cmssw/blob/debf6595c5323faca5b340ad0a865ddc99bb088b/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L191-L205

Regular Phase-2 workflows use `DQM:@phase2` and not `@standardDQM` . I think you would need to speciate it in the phase-2 case. @AdrianoDee FYI

**Comment by srimanob** [comment]
assign upgrade,heterogeneous

**Comment by AdrianoDee** [comment]
Thanks Marco, I've updated https://github.com/cms-sw/cmssw/pull/41011 to include a fix for that.

**Comment by mmusich** [comment]
This has actually nothing to do with the heterogeneous category, and as far as I can tell from the last round of tests in https://github.com/cms-sw/cmssw/pull/41011 I gather this issue could be signed and closed.

**Comment by fwyzard** [comment]
+heterogeneous

(I agree it's not to do with it)

**Comment by srimanob** [comment]
+Upgrade
