### ISSUE TITLE
Wf 4.76 (`ZMuSkim2012D`) fails on `FallbackFileOpenError`

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#43140]
e.g. in [CMSSW_13_3_X_2023-10-28-1100](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_X_2023-10-28-1100/pyRelValMatrixLogs/run/4.76_ZMuSkim2012D/step2_ZMuSkim2012D.log#/) and in many `cmssw` PRs.

**Comment by makortel** [comment]
Looks like a transient error, the workflow ran fine e.g. in CMSSW_13_3 2023-10-29-0000. @mmusich Do you expect some kind of action, or could this issue be closed?

**Comment by mmusich** [comment]
>  Do you expect some kind of action, or could this issue be closed?

It looked very persistent to be transient. Was the file in question put back on eos, or did the query change in the meanwhile?

**Comment by smuzaffar** [comment]
The file in question [a] was never cached by ibeos caching system. IBs were using file [b], which is cached in cmsbuild ibeos area, but due to das client glitch the das query [c] did not return [b] in the result. That is why IBs tried to open next file in list.

Anyway, I had forced re-run the das query to get the correct list of files which fixed this issue.

[a]
```
/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root
```

[b]
```
/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0A3C1F91-2ECD-E311-8E64-90E6BA442F3F.root
```

[c]
```
dasgoclient --limit 0 --query 'file dataset=/SingleMu/Run2012D-ZMu-15Apr2014-v1/RAW-RECO run=208307'
dasgoclient --limit 0 --query 'file dataset=/SingleMu/Run2012D-ZMu-15Apr2014-v1/RAW-RECO run=207454'
```

**Comment by makortel** [comment]
Thanks @smuzaffar

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
