### ISSUE TITLE
Maybe-uninitialized variables in Alignment/OfflineValidation/macros/momentumBiasValidation.C

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43775]
In [CMSSW_14_0_CPP20_X_2024-01-22-1100](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_0_CPP20_X_2024-01-22-1100/Alignment/OfflineValidation) IB, the following warnings about potentially uninitialized variables are emitted:

```
  <...>: warning: 'lowLim' may be used uninitialized [-Wmaybe-uninitialized]
    97 |     { return ::new((void*)__location) _Tp(std::forward<_Args>(__args)...); }
      |              ^
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C: In function 'extractgausparams':
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C:43:12: note: 'lowLim' was declared here
   43 |     double lowLim;
      |            ^
```

```
  <...>: warning: 'upLim' may be used uninitialized [-Wmaybe-uninitialized]
    97 |     { return ::new((void*)__location) _Tp(std::forward<_Args>(__args)...); }
      |              ^
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C: In function 'extractgausparams':
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C:44:12: note: 'upLim' was declared here
   44 |     double upLim;
      |            ^
```

**Comment by iarspider** [comment]
assign Alignment/OfflineValidation

**Comment by perrotta** [comment]
@iarspider `lowLim` and `upLim` will never be uninitialized, because the loop that defines them (starting in  https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/macros/momentumBiasValidation.C#L50) would at least be run once (when `iteration = 0`).

Of course, if we want to shut up the warning a whatever initial value can be given to those two variables, but nothing will change in the flow of the macro.
