### ISSUE TITLE
PFRecHitTopologyESProducer may access and invalid SoA index

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#44789]
Enabling range checks shows that `PFRecHitTopologyESProducer` may access and invalid SoA index:
```
----- Begin Fatal Exception 21-Apr-2024 12:07:14 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 379617 lumi: 3 event: 467845 stream: 0
   [1] Running path 'DST_PFScouting_SingleMuon_v2'
   [2] Prefetching for module PFClusterSoAProducer@alpaka/'hltParticleFlowClusterHBHESoA'
   [3] Prefetching for EventSetup module PFRecHitHCALTopologyESProducer@alpaka/'hltESPPFRecHitHCALTopology'
   [4] Calling method for EventSetup module PFRecHitHCALTopologyESProducer@alpaka/'hltESPPFRecHitHCALTopology'
Exception Message:
A std::exception was thrown.
Out of range index in mutable neighbours(size_type index): index -1 vs size 23328
----- End Fatal Exception -------------------------------------------------
```

**Comment by fwyzard** [comment]
type pf

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by fwyzard** [comment]
A minimal fix is available in #44790 (for 14.1.x) and #44791 (for 14.0.x).

**Comment by fwyzard** [comment]
@jsamudio @fllor @hatakeyamak while looking into this, I noticed a realised there is a minor inconsistency in the code:
  - `neighbours` is a matrix of `int32_t` (signed)
  - `detId2denseId` returns an `uint32_t` (unsigned)

Is it intended ?
If it is intended, could you add a `static_cast` in the appropriate places to mark it as such ?
If it is not intended, could you look for a way to make it uniform ?

In either case, could you introduce a named constant to identify invalid dense ids, instead of using `-1` or `0xffffffff` ?

Thank you !

**Comment by fllor** [comment]
You are right. A denseId should always be a `uint_32t` with `0xffffffff` representing an invalid entry. The named constant also makes sense.

@jsamudio @hatakeyamak Since I do not have access to the CMS infrastructure anymore, could one of you do the commit?
For the `int32_t`, I think you just need to change these two lines:
https://github.com/cms-sw/cmssw/blob/3fb8b0edb88bcba34579ca4b9867427862eda51d/DataFormats/ParticleFlowReco/interface/PFRecHitSoA.h#L14
https://github.com/cms-sw/cmssw/blob/3fb8b0edb88bcba34579ca4b9867427862eda51d/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.dev.cc#L158

For the named constant, just do `grep -rw 0xffffffff RecoParticleFlow/PFRecHitProducer/` to find all occurrences. Though I am not quite sure right now what is happening in this line:
https://github.com/cms-sw/cmssw/blob/3fb8b0edb88bcba34579ca4b9867427862eda51d/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.dev.cc#L33
This should probably be left unchanged.

**Comment by jsamudio** [comment]
I am currently traveling, but will tackle this once I reach my destination.
