### ISSUE TITLE
Noisy PileupJetIdProducer in Prompt reconstruction

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#45099]
While investigating a PromptReco reproducer in https://github.com/cms-sw/cmssw/issues/45089#issue-2322763515 I noticed many printouts along
```
%MSG-e FactorizedJetCorrectorCalculator:   PileupJetIdProducer:pileupJetIdCalculatorPUPPIDQM 29-May-2024 23:36:50 CEST  Run: 381067 Event: 682965806
jet phi is not set
%MSG
```
from `pileupJetIdCalculatorPUPPIDQM` and `pileupJetIdCalculatorCHSDQM`. In that example job, in 26466 events there were total of 4733863 printouts, corresponding to 767 MB of log.

Could these be silenced in some way?

**Comment by makortel** [comment]
assign reconstruction, dqm

**Comment by makortel** [comment]
Could somebody look into this? The amount of logs is quite substantial.

**Comment by jfernan2** [comment]
type jetmet

**Comment by jfernan2** [comment]
@iatakisi as current DQM Offline expert, could you please have a look?

**Comment by nurfikri89** [comment]
@makortel @jfernan2 has this been resolved? I can take a look at this from the jetmet side.

**Comment by jfernan2** [comment]
No, it has not, please have a llok and make a proposal for solution. Thanks

**Comment by nurfikri89** [comment]
The printouts appear because one of the levels in the latest JECs is now dependent on jet phi. The variable is not explicitly set here:

https://github.com/cms-sw/cmssw/blob/77c6c383f4c1af489c3778cc052abe2e737c0808/RecoJets/JetProducers/plugins/PileupJetIdProducer.cc#L158-L165

Simply adding `jecCor_->setJetPhi(jet.phi());` suppress the message. I have tested that the prinouts no longer appear using `RunPromptReco.py`. The PRs for the master and `14_0_X` branches will be submitted shortly.

**Comment by jfernan2** [comment]
Thanks @nurfikri89 !

**Comment by jfernan2** [comment]
+1
Fixed by https://github.com/cms-sw/cmssw/pull/45270
