### ISSUE TITLE
improve testing of ECAL-laser-farm workflow(s)

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#45450]
The updates in https://github.com/cms-sw/cmssw/pull/44892 addressed https://github.com/cms-sw/cmssw/issues/44643 (although I see the latter issue is still open, so maybe there is more to it). They were first tested online using `CMSSW_14_0_7_HLTTest`, then deployed as part of `CMSSW_14_0_9`. More details can be found in [CMSHLT-3230](https://its.cern.ch/jira/browse/CMSHLT-3230).

This update led to a problem in the production jobs running in the ECAL laser farm. This was caught only after deploying the update online, and it was promptly fixed in https://github.com/cms-sw/cmssw/pull/45247 (which was backported and included in `CMSSW_14_0_9_patch1` and `CMSSW_14_0_10`).

Given that the issue was not caught during PR tests nor IBs, it looks like the production workflows running in the ECAL laser farm are not fully tested in CMSSW [*].

It would be useful to add/improve these tests, in order to avoid similar issues in the future.

[*] For what I understood, at least one of these workflows uses as input source an instance of `StreamerInputModule` (maybe `WatcherSource`). I see there are tests related to `WatcherSource` in `CalibCalorimetry/EcalLaserSorting/test/`, but apparently these passed during the testing of https://github.com/cms-sw/cmssw/pull/44892.

**Comment by mmusich** [comment]
> (I guess, not sure if other areas need to be included)

daq sounds like a safe bet

**Comment by makortel** [comment]
assign daq

**Comment by smorovic** [comment]
I debugged again this problem and it turns out it was triggered only when multiple metadata event were found in one streamer file...this is the reason why there is no crash with current test, which generated files contain only one metadata event (i.e. no merging from multiple processes).

I am expanding `EventFilter/Utilities` test, which already runs DQM-like configuration, to run WatcherSource configuration on files merged from two processes.

While we could modify `CalibCalorimetry/EcalLaserSorting` tests, this would have to reuse DAQ test configuration files, so we can as well have it EvF/Utilities area. Another benefit is that DQM test will also be done with files merged from two processes, which isn't the case now.

**Comment by smorovic** [comment]
Test added with #45465
I think backport is not needed (any changes that can cause problems here will need to be backported from master).

**Comment by missirol** [comment]
Thanks @smorovic !
