### ISSUE TITLE
ROOT 6.32 validation

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#45556]
@makortel , CMSSW_14_1_0_pre6 is in build phase, should we build CMSSW_14_1_0_pre6_ROOT632 to start the validation of root 6.32 for it possible integration in CMSSW 15.0 ?

**Comment by makortel** [comment]
assign core, pdmv

**Comment by makortel** [comment]
> should we build CMSSW_14_1_0_pre6_ROOT632 to start the validation of root 6.32 for it possible integration in CMSSW 15.0 ?

Let's build it.

**Comment by smuzaffar** [comment]
I have opened https://github.com/cms-sw/cmssw/issues/45557

**Comment by smuzaffar** [comment]
CMSSW_14_1_0_pre6_ROOT632 is available now (https://github.com/cms-sw/cmssw/issues/45557)
Release validation ticket: https://its.cern.ch/jira/browse/PDMVRELVALS-249

**Comment by smuzaffar** [comment]
CMSSW_14_1_0_pre6_ROOT632 Relval campaign: https://cms-pdmv-prod.web.cern.ch/valdb/campaigns/search/root632

**Comment by AdrianoDee** [comment]
Some issues spotted by [electrons](https://cms-talk.web.cern.ch/t/valdb-14-1-0-pre6-2024-root632-campaign-notification/53300/12). Consider that the samples share exactly the same GEN events (for noPU, for PU we re-run only from RECO).

**Comment by makortel** [comment]
Thanks @AdrianoDee. Is this difference being investigated already?

**Comment by AdrianoDee** [comment]
Let me tag @SanghyunKoand and @cochando as EGM RECO conveners so that they can have a look at it.

**Comment by AdrianoDee** [comment]
Let me tag @SanghyunKo  and @cochando as EGM RECO conveners so that they can have a look at it.

**Comment by AdrianoDee** [comment]
Yes

**Comment by makortel** [comment]
@AdrianoDee progress on the validation seems slow... E.g. for the failure in electrons, given the success in ECAL, reports from tracking and tracker (maybe photons?) would be interesting.

**Comment by AdrianoDee** [comment]
@makortel I'll ask tracking/tracker/photons validators to have a look. Unfortunately, validators can't go much faster give the number of validations we regularly have. And on top of that we had to prioritize the validation campaigns for the MC productions. I'll keep an eye on that to see how it progress (technically the deadline is two days from now).

**Comment by SanghyunKo** [comment]
We looked into various plots for electrons, but still struggling to understand what happened here. The problematic variable is E/p, and the ECAL variable looks okay... which suggest the tracking issue. The puzzling thing is that the problematic region is 2.5 < |η| < 3, where we have no tracker (but only pixels). So it would be helpful if there is any independent report related to the pixel (seeding).

**Comment by makortel** [comment]
> I'll ask tracking/tracker/photons validators to have a look. Unfortunately, validators can't go much faster given the number of validations we regularly have. And on top of that we had to prioritize the validation campaigns for the MC productions. I'll keep an eye on that to see how it progress (technically the deadline is two days from now).

@AdrianoDee Any news?

**Comment by srimanob** [comment]
Hi @cms-sw/pdmv-l2 @SanghyunKo 

Could you please clarify about samples you are using? I see difference results when I try to compare between STDs, and between KITFARM_SpecialRVs. Do I understand correctly that issue shows up only when you share the same GEN.

Thanks.

With STDs: I don't see different in the EoP plot
`/RelValZEE_14/CMSSW_14_1_0_pre6-140X_mcRun3_2024_realistic_v15_STD_2024_PU-v1/DQMIO`
`/RelValZEE_14/CMSSW_14_1_0_pre6_ROOT632-140X_mcRun3_2024_realistic_v15_STD_RecoOnly_2024_PU-v1/DQMIO`
DQM: https://tinyurl.com/2atp76fg
<img width="800" alt="ZEE_14TeV_STD" src="https://github.com/user-attachments/assets/34efb489-ac14-419c-8fad-c9e1315799bb">
Both share the same RAW:` /RelValZEE_14/CMSSW_14_1_0_pre6-PU_140X_mcRun3_2024_realistic_v15_STD_2024_PU-v1/GEN-SIM-DIGI-RAW`

With KITFARM_SpecialRVs (the ones that EGamma use from [plot definition](https://cms-egamma.web.cern.ch/validation/Electrons/Releases/14_1_0_pre6_2024_DQM_std/FullvsFull_CMSSW_14_1_0_pre6_ROOT632/RECO-RECO_ZEE_14/definitions.txt)), I see the difference in the EoP plot as reported:
`/RelValZEE_14/CMSSW_14_1_0_pre6-140X_mcRun3_2024_realistic_v15_2024_KITFARM_x86_SpecialRV-v1/DQMIO`
`/RelValZEE_14/CMSSW_14_1_0_pre6_ROOT632-140X_mcRun3_2024_realistic_v15_2024_KITFARM_ROOT632_SpecialRV-v1/DQMIO`
DQM: https://tinyurl.com/2annk7cd
<img width="800" alt="ZEE_14TeV_KITFARM" src="https://github.com/user-attachments/assets/3d5da31b-14a6-46ae-85f7-5c2ad471056f">
Both share the same GEN: `/RelValZEE_14/CMSSW_14_1_0_pre6-140X_mcRun3_2024_realistic_v15_2024_GENOnly_KITFARM_x86_SpecialRV-v1/GEN`

**Comment by srimanob** [comment]
I think I can reproduce this strange behaviors.
Blue: Same RAWSIM, RECO only
Orange: Same GENSIM, DIGI+RECO
Something is going strange in DIGI-L1-HLT step.
DQM: [https://tinyurl.com/29gy99bl](https://tinyurl.com/29gy99bl)

<img width="800" alt="Screenshot 2567-11-21 at 21 41 12" src="https://github.com/user-attachments/assets/02bbc48e-8e23-49d7-8d8d-107a250bfac8">

**Comment by srimanob** [comment]
Tracker DIGI seems to show discrepancy which I don't expect as these samples come from the same GEN-SIM and NoPU.
Tracker Digi Strip: https://tinyurl.com/2xzrjx39
PXBarrel: https://tinyurl.com/2chjhahg (seem off in low ADC counts)

@cms-sw/trk-dpg-l2 @henriettepetersen @sroychow 
Could you please have look? Any modules that may affect heavily from ROOT?

**Comment by srimanob** [comment]
Hi,
I found that when I fix the `pDetIDAssociationInfo` [here](https://github.com/cms-sw/cmssw/blob/master/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc#L178) which is may be used uninitialized, I get a converge result. It is not fully converge to the ROOT 630 but clearly improve. Result seems to be in good agreement when the fix is applied in both 630 and 632. See plot below.

Still no clue why ROOT plays role here, @dpiparo @makortel and clues?
Plot uses the same GEN-SIM, DQM in https://tinyurl.com/24jmmovz
Black = ROOT 630
Blue = ROOT630 + Fix
Orange = ROOT 632
Red = ROOT 632 + Fix

<img width="1076" alt="Screenshot 2567-11-22 at 08 41 00" src="https://github.com/user-attachments/assets/5b5ced6c-2a8b-45cd-a317-5b1e5521a7e3">

**Comment by srimanob** [comment]
From EGamma report, I get a confusion a bit. Red is 630, Blue is 632. It seems in opposite on what I get.

<img width="803" alt="Screenshot 2567-11-22 at 08 58 49" src="https://github.com/user-attachments/assets/231673b0-5b1e-4417-8213-a6150211870f">

**Comment by AdrianoDee** [comment]
> @AdrianoDee Any news?

Traacking validators have started [looking into this](https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/MC/CMSSW_14_1_0_pre6_ROOT632/index.html) and are investigating.

**Comment by beaudett** [comment]
Hi @srimanob 
I re-checked the EGM validation plot you copy/pasted and I confirm that red is `DQM_V0002_R000000001__ RelValTTbar_14TeV__CMSSW_14_1_0_pre6_ROOT632-140X_mcRun3_2024_realistic_v15_2024_KITFARM_ROOT632_SpecialRV-v1__DQMIO.root` and blue is `RECO 14_1_0_pre6 : DQM_V0002_R000000001__ RelValTTbar_14TeV__CMSSW_14_1_0_pre6-140X_mcRun3_2024_realistic_v15_2024_KITFARM_x86_SpecialRV-v1__DQMIO.root` 

Two additional remarks. 
1) Checking how this plot is done, I saw that it is a TProfile obtained from a 2D plot which has a range [0,5] while the E/p especially in this region (2.5<|eta|<3) can be larger. The track reconstruction and fit and thus the pT is difficult to reconstruct in this region. 
2) Unless I am mistaken, those plots are *not* the RecoOnly

 I'll report here as soon as I have additional information, but I am starting to wonder whether we have been looking into fluctuations.

**Comment by AdrianoDee** [comment]
> 2\. Unless I am mistaken, those plots are _not_ the RecoOnly

Correct they are not RecoOnly but they share exactly the same GEN events. So, in principle, any discrepancy we see does not come from fluctuations (given also the wfs have run on 100% of the events). For TTbar specifically:
- [TTbar for ROOT632 ](https://cms-pdmv-prod.web.cern.ch/relval/relvals?prepid=CMSSW_14_1_0_pre6_ROOT632__Run3_2024_noPU_KITFARM_SpecialRV-TTbar_14TeV-00001&shown=1049599&page=0&limit=50)
- [TTbar for standard pre6](https://cms-pdmv-prod.web.cern.ch/relval/relvals?prepid=CMSSW_14_1_0_pre6__Run3_2024_noPU_KITFARM_x86_SpecialRV-TTbar_14TeV-00001&shown=1049599&page=0&limit=50)
- [The common GEN](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelValTTbar_14TeV%2FCMSSW_14_1_0_pre6-140X_mcRun3_2024_realistic_v15_2024_GENOnly_KITFARM_x86_SpecialRV-v1%2FGEN) (run with standard `14_1_0_pre6`)

**Comment by srimanob** [comment]
Note that, my plot in https://github.com/cms-sw/cmssw/issues/45556#issuecomment-2493093663 share the same GEN-SIM, so no fluctuation in GEN+SIM. And it is NoPU.

**Comment by AdrianoDee** [comment]
An additional note in the links above:

> TTbar for ROOT632
[TTbar for standard pre6](https://cms-pdmv-prod.web.cern.ch/relval/relvals?prepid=CMSSW_14_1_0_pre6__Run3_2024_noPU_KITFARM_x86_SpecialRV-TTbar_14TeV-00001&shown=1049599&page=0&limit=50)
[The common GEN](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelValTTbar_14TeV%2FCMSSW_14_1_0_pre6-140X_mcRun3_2024_realistic_v15_2024_GENOnly_KITFARM_x86_SpecialRV-v1%2FGEN) (run with standard 14_1_0_pre6)

You can see the statistics also for the ALCARECO data-tiers. The fact that they some small discrepancies between the two seems to point to the fact that the differences in the objects end up having an effect on the event selected for the different streams.

**Comment by makortel** [comment]
@srimanob 

> I found that when I fix the `pDetIDAssociationInfo` [here](https://github.com/cms-sw/cmssw/blob/master/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc#L178) which is may be used uninitialized, I get a converge result. 

I don't see how `pDetIDAssociationInfo` would get used uninitialized. The only use of `pDetIDAssociationInfo` that I see is under `if (makeDigiSimLinks_)`, which is the same condition for the initialization of `pDetIDAssociationInfo`. (also, de-referencing uninitialized pointer should have a high chance of segfault instead of producing incorrect results, although the latter is a real possibility too)

> It is not fully converge to the ROOT 630 but clearly improve. Result seems to be in good agreement when the fix is applied in both 630 and 632. See plot below.

Can I ask how did you technically produce the blue (`/RelValZEE_2024_NoPU_ROOT630_GS1ROF/CMSSW_14_1_0_pre6-phase1_2024_realistic/DQMIO`) and red (`/RelValZEE_2024_NoPU_ROOT632_GS1ROF/CMSSW_14_1_0_pre6-phase1_2024_realistic/DQMIO`)? I mean, I would have assumed the RelVal DQM GUI contains data only from samples produced by the RelVal machinery, and RelVal machinery uses only CMSSW releases and can't include changes done in local developer areas.

So I'm wondering if the plot https://tinyurl.com/24jmmovz is showing mainly fluctuations (or non-reproducibilities?) of running the same code twice?

**Comment by srimanob** [comment]
Hi @makortel 

What I did include

(1) Run batch on CMSSW_14_1_0_pre6 and CMSSW_14_1_0_pre6_ROOT632 (using singularity cmssw-el8 on cern batch). Each job, random number changes, also lumi number.

(2) add `= 0` in the line `AssociationInfoForChannel* pDetIDAssociationInfo;`

(3) Run step1 (first time only, with ROOT630, no fix), step2, step3 and keep GEN-SIM and DQM files in` /eos/cms/store/group/offcomp_upgrade-sw/srimanob/ROOT632/Test1-SameRaw/`. GEN-SIM reused for step2 with 630+fix, 632, 632+fix.

(4) Do harvesting locally, and rename it to fit the format.

(5) Upload to DQM GUI using 
`https://raw.githubusercontent.com/cms-sw/cmssw/master/DQMServices/FileIO/scripts/visDQMUpload.py`
i.e.
`python3 visDQMUpload.py https://cmsweb.cern.ch/dqm/relval DQM....root`

I am running for more stat since noon (new fresh one). I may able to show that is not fluctuation, and it can reproducible. If you look on the eos directory above, files that I made plot are in 2XXX folder. The new 3XXX is on going independently.

**Comment by srimanob** [comment]
> I don't see how `pDetIDAssociationInfo` would get used uninitialized. 
I see the same which I puzzled it has quite strong effect on this plot. `scram b` shows the warning on this, so I just try as mentioned above to see the result.

```
 inlined from 'accumulateSimHits' at src/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc:213:76:
/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_tree.h:737:73: warning: 'pDetIDAssociationInfo' may be used uninitialized [-Wmaybe-uninitialized]
  737 |       { return static_cast<_Link_type>(this->_M_impl._M_header._M_parent); }
      |                                                                         ^
src/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc: In member function 'accumulateSimHits':
src/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc:178:32: note: 'pDetIDAssociationInfo' was declared here
  178 |     AssociationInfoForChannel* pDetIDAssociationInfo;  // I only need this if makeDigiSimLinks_ is true...
      |                                ^
```

**Comment by makortel** [comment]
> > I don't see how `pDetIDAssociationInfo` would get used uninitialized.
> > I see the same which I puzzled it has quite strong effect on this plot. `scram b` shows the warning on this, so I just try as mentioned above to see the result.
> 
> ```
>  inlined from 'accumulateSimHits' at src/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc:213:76:
> /cvmfs/cms.cern.ch/el9_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_tree.h:737:73: warning: 'pDetIDAssociationInfo' may be used uninitialized [-Wmaybe-uninitialized]
>   737 |       { return static_cast<_Link_type>(this->_M_impl._M_header._M_parent); }
>       |                                                                         ^
> src/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc: In member function 'accumulateSimHits':
> src/SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc:178:32: note: 'pDetIDAssociationInfo' was declared here
>   178 |     AssociationInfoForChannel* pDetIDAssociationInfo;  // I only need this if makeDigiSimLinks_ is true...
>       |                                ^
> ```

Thanks. I see this warning also in the build log of the IB https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_2_X_2024-11-21-2300/SimTracker/SiStripDigitizer, seems to be coming from the LTO. @smuzaffar We might want to reconsider reporting these warnings in the IB dashboard (at least when they come via the standard library)

On one hand we have seen false positive warnings from LTO. On the other hand this is a bit scary, because in this case I'd expect the compiler to be able to figure out the `pDetIDAssociationInfo` could not be uninitialized where it is used, and therefore I'm then wondering if the LTO optimizer would be doing something weird?

**Comment by srimanob** [comment]
With high stat (20,000 events), it seems to show that it is fluctuation.
https://tinyurl.com/24jm6kod

<img width="800" alt="Screenshot 2567-11-22 at 17 37 01" src="https://github.com/user-attachments/assets/1ae6aaa1-1bae-4592-aa5d-81e5ff04226b">

I will do larger stat tonight, and compare what I see from low and high stats using the same sets.

**Comment by srimanob** [comment]
I compare 9k events and 39k events, it seems to converge. So look like statistical fluctuation.

<img width="800" alt="v4_9kevents" src="https://github.com/user-attachments/assets/9c754567-dd8b-407a-9bed-0052867bdb3f">
<img width="800" alt="v4_39kevents" src="https://github.com/user-attachments/assets/a27264dd-bcac-4067-8f4f-8d9797e3079b">

Here is 2D plots that make above profile plot. Statistics at Eta=~3 is very small.
<img width="800" alt="v42D_9kevents" src="https://github.com/user-attachments/assets/0d4bd99b-0df1-49e5-9431-d7160512787b">
<img width="800" alt="v42D_39kevents" src="https://github.com/user-attachments/assets/bb58448c-b292-47cd-8319-23c5f404c918">

If @cms-sw/pdmv-l2 would like to confirm. You may try to run high stat relvals.

**Comment by makortel** [comment]
Thanks @srimanob! (reminds me of past technical validation rounds, e.g. https://github.com/cms-sw/cmssw/issues/36339)

I wonder though if these plots have shown any "false positives" before?

**Comment by srimanob** [comment]
Hi @makortel 
Seem not, here is the [link](https://cms-egamma.web.cern.ch/validation/Electrons/Releases/index.php?actionFrom=/12_1_0_pre4_ROOT624_2021_DQM_std/FullvsFull_CMSSW_12_1_0_pre4_ROOT624/RECO-RECO_ZEE_14&cchoice=diff#EeleOPoutVsEta_pfx):
<img width="1292" alt="Screenshot 2567-11-23 at 00 51 54" src="https://github.com/user-attachments/assets/b4a0d188-42c7-4d24-b6e7-f2e9fdbf64f9">

**Comment by AdrianoDee** [comment]
Thanks Phat! I'm sending some 100k wfs (for the flagship samples TTbar, Zee, ...) just to close the loop. As a note to us (PdmV) for the next rounds we should produce very high stats samples, at least for some core processes (again TTbar etc.). For this round we just doubled the usual stats.

**Comment by beaudett** [comment]
Hi @makortel 
There has been differences for this plot in the previous validations, but limited to one sample. What triggered the alarm here was the fact we could see deviations at the same place in different samples

**Comment by beaudett** [comment]
Arnaud (@archiron ) has done the plots with the RecoOnly sample of that validation
[1] https://cms-egamma.web.cern.ch/validation/Electrons/Releases/14_1_0_pre6_2024_DQM_std/FullvsFull_CMSSW_14_1_0_pre6_ROOT632-RecoOnly/PU-PU_ZpToEE_m6000_14TeV/gifs/h_ele_EoPVsEta_Extended_pfx.gif
[2] https://cms-egamma.web.cern.ch/validation/Electrons/Releases/14_1_0_pre6_2024_DQM_std/FullvsFull_CMSSW_14_1_0_pre6_ROOT632-RecoOnly/PU-PU_ZEE_14/gifs/h_ele_EoPVsEta_Extended_pfx.gif
[3] https://cms-egamma.web.cern.ch/validation/Electrons/Releases/14_1_0_pre6_2024_DQM_std/FullvsFull_CMSSW_14_1_0_pre6_ROOT632-RecoOnly/PU-PU_TTbar_14TeV/gifs/h_ele_EoPVsEta_Extended_pfx.gif

and they show a perfect agreement, which is very reassuring.

**Comment by beaudett** [comment]
Hi,
I have updated the [report](https://cms-pdmv-prod.web.cern.ch/valdb/campaigns/14_1_0_pre6_2024_ROOT632/report/Reconstruction.FullSim.Electron) 
If you agree, I propose to change the status to ok.

**Comment by smuzaffar** [comment]
@makortel , validation reports seems good now ( though many are missing). should we move to root 6.32 for 15.0.X now?

**Comment by srimanob** [comment]
@cms-sw/pdmv-l2 
Do you still waiting validation reports? Thx.

**Comment by AdrianoDee** [comment]
Yes, there are still some I'd like you to see there. Do you have a deadline on your side cor integrating this?

**Comment by makortel** [comment]
> validation reports seems good now ( though many are missing). should we move to root 6.32 for 15.0.X now?

I wonder if we want to have the microarchitecture change (x86-64-v2 to v3) validated in the same prerelease where we deploy ROOT 6.32? (while theoretically the ROOT update is validated here, I wouldn't be surprised if we'd see similar statistical fluctuations in the pre-release where the ROOT update is deployed)

I was originally thinking we'd do the microarchitecture change in pre1, but I'm not sure if the discussion (even on the "big picture) in https://github.com/dmwm/WMCore/issues/12168 would converge "soon" (ok, I haven't fully digested the comments made since last Wednesday).

**Comment by makortel** [comment]
> Yes, there are still some I'd like you to see there. Do you have a deadline on your side cor integrating this?

@AdrianoDee If we'd want to deploy ROOT 6.32 for pre1 (but see the discussion on microarchitecture), we should make do the update (i.e. merge https://github.com/cms-sw/cmsdist/pull/9541) about now (in order to get it tested in all IB flavors, and have some time to react in case of problems, before pre1 will be built next week).

We should deploy 6.32 in pre2 at the latest (second-to-last prerelease), so counting backwards
* Jan 14 pre2 is built
* Jan 7 need to deploy ROOT 6.32 in `master`
* However, CERN has just opened on Jan 6, and we can probably reasonably expect only little progress on the validation during the 2 weeks of CERN closure. I think we should also avoid the deployment right before the CERN closure, so in a way a preferable deployment time would be around Dec 16 at the latest (and after pre1 has been built).

So there is about a week to two weeks to conclude (or to Jan 6 if really really needed).

**Comment by AdrianoDee** [comment]
(I edited the comment above. I think we should be able to close the validation this week. Then for ROOT integrated in pre1 depends a bit on when we'll end up cutting it.)

**Comment by AdrianoDee** [comment]
Just to say that, while we still don't have all the reports, for me we have the quorum to say the validation was successful.

**Comment by makortel** [comment]
Thanks @AdrianoDee! @smuzaffar Should we deploy ROOT 6.32 in default IB early next week (after the pre1 has been built)?

**Comment by smuzaffar** [comment]
> Thanks @AdrianoDee! @smuzaffar Should we deploy ROOT 6.32 in default IB early next week (after the pre1 has been built)?

yes, sounds good.

**Comment by smuzaffar** [comment]
ROOT 6.32 is now integrated in 15.0.X IBs. I also have replaced ROOT632 IBs with ROOT634 Ibs

**Comment by AdrianoDee** [comment]
+pdmv
Validation successful

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
