### ISSUE TITLE
Deployment of multi-architecture setup in 14_0_X

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#45654]
Moving the discussion from https://github.com/cms-sw/cmssw/issues/45596#issuecomment-2260619344 to here (following a request in ORP earlier today).

To summarize, we would deploy the multi-architecture setup used in 14_1_X in 14_0_X, and stop building the separate 14_0_MULTIARCHS_X. In the upcoming multi-architecture setup, 14_0_X will default to `sse3`, and the use of `x86-64-v3` or automatic decision between `sse3` and `x86-64-v3` needs to be explicitly set.

This "explicit setting" is a change in behavior compared to 14_0_X_MULTIARCHS_X that the DAQ should take into account when such release gets deployed.

The purpose of this issue is to coordinate the moment to do this change between core software, ORP, and DAQ.

**Comment by makortel** [comment]
assign core, daq

**Comment by smorovic** [comment]
Hello,
what will be needed to use x86-64-v3 by default where available, is it just setting `SCRAM_TARGET=auto`?
In HLT, at runtime, we run cmsenv directly on installation area and we don't use project areas. If we need to also run `scram b enable-multi-targets` even on release base, it won't work because that needs write access to the area.

I can work on this from Aug 19th and later. It is trivial if it is only environment change and we can add it to hltd script, but it needs to be coordinated and deployed at the same time as the release is switched to - or, better, before if it doesn't have any effect on previous releases.

**Comment by fwyzard** [comment]
Setting `SCRAM_TARGET=auto` is not enough.

Looking at what `scram b enable-multi-targets` does, it might be enough to `touch $CMSSW_RELEASE/.SCRAM/$SCRAM_ARCH/multi-targets` in addition to that ?

@smuzaffar would it work if we do it in the release area after installing the RPM ?

**Comment by smuzaffar** [comment]
No @fwyzard , creating `$CMSSW_RELEASE/.SCRAM/$SCRAM_ARCH/multi-targets` is not enough. The project hook `$CMSSW_RELEASE/.SCRAM/$SCRAM_ARCH/multi-targets` ( which is run when one creates a dev area) enables multi-targets env for dev are if both `$CMSSW_RELEASE/.SCRAM/$SCRAM_ARCH/multi-targets`  exists and project was build with `SCRAM_TARGET=auto`. Currently only `MULTIARCHS` releases are built with `SCRAM_TARGET=auto`

**Comment by fwyzard** [comment]
OK, so there is no way to turn a "default" release into one with multi-targets enabled ?

What about if we do `scram b enable-multi-targets` in the _release_ area right after installing it ?

**Comment by smuzaffar** [comment]
> What about if we do scram b enable-multi-targets in the release area right after installing it ?

hummm, might work, let me test it

**Comment by smuzaffar** [comment]
Note that once you enable multi-target for release area then by default your dev areas are also multi-targets enabled and any checked out package in your dev area will be build for all multi-targets

**Comment by davidlange6** [comment]
in the context of doing post-install changes to release areas, how does one then figure out if multi-target was on or off after the fact?

**Comment by smuzaffar** [comment]
`cmsenv` (either in release area or dev area) should then set `SCRAM_TARGET` environment variable. 
- `SCRAM_TARGET=auto` means scram will try to find and use the best  micro-arch available
- `SCRAM_TARGET=default` means multi-target are disabled and scram will use the default micro-arch

**Comment by smuzaffar** [comment]
> Does one need to run scram config scram-target=auto every time, or is it enough to run it just once in the installation area ?

It is enough to run it once

**Comment by makortel** [comment]
Mostly for my curiosity, why do you want to set the target to automatic decision rather than setting it to `x86-64-v3` explicitly?

**Comment by fwyzard** [comment]
No reason - we are looking for a way to do at HLT what `scram config scram-target=auto` does in a user area.

Are there any advantages from setting `x86-64-v3` explicitly ?

**Comment by fwyzard** [comment]
I understood that an environment variable is not enough, one needs to run `scram config ...` anyway ?

**Comment by smuzaffar** [comment]
Ok let me explain how currently CMSSW_14_1_X multiarchs build  works.
- We build CMSSW_14_1_X (IBs and pre-releases) with mutiarchs enabled (`default` is `x86-64-v2` while extra micro arch is `x86-64-v3`)
- Release is configured to always use `default` micro arch (`SCRAM_TARGET` env set via config/Self.xml file). So setting cmssw env directly from release will always use `default` micro-arch. This was done so that production jobs and user jobs always we the `default` micro-arch.
- As release is configured to always use `default` , so there was no point in building the extra micro-arch for user dev area. So when one creates the dev area for CMSSW_14_1_X then scram configured it to disabled the build of extra micro-arch.
- If user wants to build/enable the multi-archs for dev area then they have to run `scram build enable-multi-targets` (which internally change the configuration to allow building for extra micro-arch + change the SCRAM_TARGET to `auto`). This user had to do for every newly created dev area.

For Online/HLT deployment , @fwyzard wants that when CMSSW_14_0_X release is deployed then it is configured with `SCRAM_TARGET=auto` so that setting up cmssw env from release can also use the best micro-arch. Also user dev area based on such deployment will also have multi-arch enabled.

As we do not want to build separate releases for offline and online deployment, so one idea was that we use scram site configuration and in the `%post` install script configure the release according to the scram site configuration. This will allow HLT form to set their site configuration once and all future release can make use of it.

Of course we can set scram site config for HLT to use `x86-64-v3` and scram will still perform all the checks to make sure that it uses `x86-64-v3` or fall back to `default`. Setting scram-target to `x86-64-v3` also means when we have to test a release with `x86-64-v4` then we have to remember to do something extra e.g. either updating the scram site config to user explicitly changing the scram-target in his/her dev area.

I think setting `scram-target=auto` is a safe option.

**Comment by fwyzard** [comment]
@smuzaffar thanks for the summary and clarification.

To double check: it is not possible to use the `x86-64-v3` target just setting an environment variable when doing `cmsenv` from the release area. Correct ?

**Comment by fwyzard** [comment]
OK, thanks.

**Comment by fwyzard** [comment]
> As we do not want to build separate releases for offline and online deployment, so one idea was that we use scram site configuration and in the `%post` install script configure the release according to the scram site configuration. This will allow HLT form to set their site configuration once and all future release can make use of it.

@smuzaffar do you have a preferred mechanism for doing this ?

What I mean is, how should the scram site configuration be set, for the `%post` to pick it up ?

**Comment by smuzaffar** [comment]
Note that `SCRAM_TARGET=x86-64-v3 or better USER_SCRAM_TARGET=x86-64-v3` still works for setting up the env directly from the release area . It is only the dev area where it does not work as scram disables the multi-target when it create the dev area for a release with `SCRAM_TARGET=default`

**Comment by fwyzard** [comment]
Ah, wait.

So if we do the online equivalent of
```bash
cd /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre6
export SCRAM_TARGET=auto  # or x86-64-v3
cmsenv
```
we do get the `x86-64-v3` libraries.

For running the HLT, that should be enough - as @smorovic wrote, at HLT we run `cmsenv` directly from the installation area.

**Comment by smuzaffar** [comment]
right, setting the env directly from the release area will allow you to selected the micro-arch. 
I would suggest to use `USER_SCRAM_TARGET` instead of `SCRAM_TARGET` . Though `SCRAM_TARGET` works too but if you see the value of `SCRAM_TARGET` after cmsevn then it will be set to `default` (as config/Self.xml wants to set it to default).

**Comment by makortel** [comment]
> Ok let me explain how currently CMSSW_14_1_X multiarchs build works.

Thanks @smuzaffar for the clarifications. Could the behavior (for both setting environment directly from the release area, and via a developer area) be documented somewhere that would be more easy to find than this GitHub issue? (or is it already and I'm just being ignorant?)

**Comment by smuzaffar** [comment]
I will update `scram help` message

**Comment by smuzaffar** [comment]
> For running the HLT, that should be enough - as @smorovic wrote, at HLT we run `cmsenv` directly from the installation area.

@fwyzard , so should be update CMSSW_14_0_X configuration to build by default for x86-64-v2(default) and x86-64-v3 as an extra micro-arch (just like 14.1.X IBs/pre-releases)? 
Once enabled then next 14.0.X full release (CMSSW_14_0_15) will have multiple archs. Note that any patch release for CMSSW_14_0_14 (or earlier) will still have single arch and we need to build dedicated MULTIARCHS patch release for those.

**Comment by fwyzard** [comment]
> Note that any patch release for CMSSW_14_0_14 (or earlier) will still have single arch and we need to build dedicated MULTIARCHS patch release for those.

Mhm, this could be a problem.
Why is that ?
Is it the same for 14.1.x ?

**Comment by smuzaffar** [comment]
I mean, the patch releases for already built non-multi-arch releaes will still be non-multi-arch. As CMSSW_14_0_14 was built without multi-archs so its future patch releases will be non-multi-arch too.

**Comment by fwyzard** [comment]
Ah, OK, but after the switch patch releases like CMSSW_14_0_15_patch1 would also be multiarch ?

**Comment by fwyzard** [comment]
@smuzaffar, from the DAQ side we agree to move the 14.0.x releases to multiarchs starting with CMSSW_14_0_15 .

@smorovic will set `export USER_SCRAM_TARGET=x86-64-v3` before calling `cmsenv` in the release areas.

**Comment by smuzaffar** [comment]
> Ah, OK, but after the switch patch releases like CMSSW_14_0_15_patch1 would also be multiarch ?

yes

**Comment by makortel** [comment]
> update CMSSW_14_0_X configuration to build by default for x86-64-v2(default) and x86-64-v3

Just to make sure, for 14_0_X the default should be `sse3`, right? (since we moved the minimum to `x86-64-v2` only in 14_1_X)

**Comment by smuzaffar** [comment]
> > update CMSSW_14_0_X configuration to build by default for x86-64-v2(default) and x86-64-v3
> 
> Just to make sure, for 14_0_X the default should be `sse3`, right? (since we moved the minimum to `x86-64-v2` only in 14_1_X)

Ah right, 14.0.x default  instruction set is sse3

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cms-bot/pull/2316 enables multi-archs for 14.0.X

**Comment by smorovic** [comment]
@smuzaffar,
is it safe to `export USER_SCRAM_TARGET=x86-64-v3` for earlier releases such as CMSSW_14_0_14_MULTIARCHS?
We are planning to deploy it even before we have 14_0_15 and it would be simpler if we can already set it now.

**Comment by fwyzard** [comment]
I think setting it in the multiarch releases should be fine:
```
$ cd /data/cmssw/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_13_patch2_MULTIARCHS
$ export USER_SCRAM_TARGET=x86-64-v3
$ cmsenv
IMPORTANT: Setting CMSSW environment to use 'x86-64-v3' target.
```

And, on a non-multiarch release it doesn't seem to do anything.

**Comment by smuzaffar** [comment]
@smorovic , Yes it is safe to `export USER_SCRAM_TARGET=x86-64-v3` for earlier releases.

- for CMSSW_14_0_14 or earlier: this will not do any thing and `default` libs will be loaded anyway
- for MULTIARCHS IBs: It will still set/load `x86-64-v3` libs (if host support v3 othewise it will fall back to `default`)

**Comment by smorovic** [comment]
> I think setting it in the multiarch releases should be fine:
> 
> ```
> $ cd /data/cmssw/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_13_patch2_MULTIARCHS
> $ export USER_SCRAM_TARGET=x86-64-v3
> $ cmsenv
> IMPORTANT: Setting CMSSW environment to use 'x86-64-v3' target.
> ```
> 
> And, on a non-multiarch release it doesn't seem to do anything.

As we want to use x86-64-v3 in HLT, it seems safe (instead of automatic detection).
New hlltd which sets this was in fact installed today by hand and left running CDAQ after Lustre and NVMe SSD tests, so we are currently using it, but I wanted to ask anyway to be sure.
Tomorrow we'll push it 'officially' with puppet, also in Hilton.

**Comment by makortel** [comment]
+core
