### ISSUE TITLE
[DBG_X] 'nonnull' argument 't' compared to NULL

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#45998]
In DBG_X IB, the following warning was emitted:

```
>> Compiling edm plugin src/RecoHGCal/TICL/plugins/filters.cc
<gcc invocation>
In file included from src/FWCore/MessageLogger/interface/ErrorObj.h:136,
                 from src/FWCore/MessageLogger/interface/MessageSender.h:5,
                 from src/FWCore/MessageLogger/interface/MessageLogger.h:30,
                 from src/RecoHGCal/TICL/plugins/TracksterLinkingbySkeletons.cc:1:
src/FWCore/MessageLogger/interface/ErrorObj.icc: In member function 'edm::ErrorObj::opltlt<bool (std::array<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<float>, ROOT::Math::DefaultCoordinateSystemTag>, 3ul> const&, std::array<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<float>, ROOT::Math::DefaultCoordinateSystemTag>, 3ul> const&, float)>(bool ( const&)(std::array<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<float>, ROOT::Math::DefaultCoordinateSystemTag>, 3ul> const&, std::array<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<float>, ROOT::Math::DefaultCoordinateSystemTag>, 3ul> const&, float))edm::ErrorObj&':
  src/FWCore/MessageLogger/interface/ErrorObj.icc:28:10: warning: 'nonnull' argument 't' compared to NULL [-Wnonnull-compare]
    28 |     myOs << t;
      |     ~~~~~^~~~
```

[full log](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_2_DBG_X_2024-09-12-2300/RecoHGCal/TICL)

**Comment by makortel** [comment]
assign core

Let's start with this even if I believe the problem is not in the MessageLogger code

**Comment by makortel** [comment]
The referred `MessageLogger` code is
https://github.com/cms-sw/cmssw/blob/6e31ebe803aa3cd54ba56999036e36202a849dbc/FWCore/MessageLogger/interface/ErrorObj.icc#L25-L28
I guess the comparison wrt. `NULL` comes somewhere in the `std::ostringstream::operator<<()`?

The warning was emitted when compiling https://github.com/cms-sw/cmssw/blob/master/RecoHGCal/TICL/plugins/TracksterLinkingbySkeletons.cc . I didn't see any indication on the log about the line in `TracksterLinkingbySkeletons.cc`. Since the warning is specific to DBG_X, I guess the culprit needs to be a `LogDebug` / `LogTrace` trace (well, the file uses only `LogDebug`).

Another hint is the instantiation of `ErrorObj::opltlt()`, which points towards `std::array<ticl::Vector, 3>` being printed (`ticl::Vector` is a type alias for `math::XYZVectorF`). On a quick look I did not, however, see where `std::array<ticl::Vector, 3>` would be passed to `LogDebug`.

**Comment by Dr15Jones** [comment]
So the error message is weird as it says the type of T is a function 
```C++
bool (std::array<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<float>, ROOT::Math::DefaultCoordinateSystemTag>, 3ul> const&, std::array<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<float>, ROOT::Math::DefaultCoordinateSystemTag>, 3ul> const&, float)
```

**Comment by makortel** [comment]
Good catch! I guess the offending line is the second line in
https://github.com/cms-sw/cmssw/blob/6e31ebe803aa3cd54ba56999036e36202a849dbc/RecoHGCal/TICL/plugins/TracksterLinkingbySkeletons.cc#L306-307
that should be
```cpp
          LogDebug("TracksterLinkingbySkeletons") << "Two Points are in Cylinder  " << isInCyl << std::endl;
```

**Comment by Dr15Jones** [comment]
Found it

https://github.com/cms-sw/cmssw/blob/6e31ebe803aa3cd54ba56999036e36202a849dbc/RecoHGCal/TICL/plugins/TracksterLinkingbySkeletons.cc#L307

the FUNCTION `isInCylinder` is being passed to LogDebug, not the return value of the function.

**Comment by makortel** [comment]
assign RecoHGCal/TICL

(mostly for completeness)

**Comment by makortel** [comment]
+core

Core part is done

**Comment by jfernan2** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade
