### ISSUE TITLE
Release making improvements

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#8652]
@nclopezo - 

two requests for making the release process even easier

1) could the bot make a guess at the right release notes to make? If the guess is wrong, we'll remake them by hand

2) could we replace the bots email template with something like this (with the appropriate <a and /a> at the start and end). Then I can just click a button..

href="mailto:hn-cms-relAnnounce@cern.ch?subject=Production release CMSSW_6_2_0_SLHC25 now available&body=Hi all,%0D%0D The production patch release CMSSW_6_2_0_SLHC25_patch3 is now available for the following architectures:%0D%0D slc6_amd64_gcc472 (production)%0D%0D The release notes of what changed with respect to CMSSW_6_2_0_SLHC25_patch2 can be found at:%0D%0D https://github.com/cms-sw/cmssw/releases/CMSSW_6_2_0_SLHC25_patch3%0D%0D Cheers,%0D cms-bot ">Announce the release

**Comment by nclopezo** [comment]
Hi David,

I did it in cms-sw/cms-bot#423. You can now write "release-notes" only, and the bot will guess the previous release, you can still write "release-notes since..." as before. For the announcement email link, I left the template in the comment (see for example https://github.com/cms-sw/cmssw/issues/6375#issuecomment-90547494), to allow it to be used easily if you are using a computer in which the email client is not configured.
