### ISSUE TITLE
[CMSSW_7_5_X] Objects in wrong dictionaries

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#9364]
I looked at QA script results and there are some objects in wrong dictionaries, or rule file needs to be updated.

Details: https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc6_amd64_gcc491/www/sat/7.5.DEVEL-sat-23/CMSSW_7_5_DEVEL_X_2015-05-30-2300/testLogs/dupDict-lostDefs.log

```
./DataFormats/HcalIsolatedTrack/src/classes_def.xml
  RecoCandidate : edm::reftobase::Holder< reco::Candidate, edm::Ref< vector< reco::HcalIsolatedTrackCandidate >, reco::HcalIsolatedTrackCandidate, edm::refhelper::FindUsingAdvance< vector< reco::HcalIsolatedTrackCandidate >, reco::HcalIsolatedTrackCandidate > > >

./DataFormats/BTauReco/src/classes_def.xml
  TopObjects : reco::CATopJetProperties
  TopObjects : pair< edm::RefToBase< reco::Jet >, reco::CATopJetProperties >
```

@slava77  @cvuosalo @davidlange6 

If this is important to track, we should run this script while building CMSSW thus developer would be actual warnings before submitting PRs.

**Comment by slava77** [comment]
The placement of the dictionaries is correct.
- the HcalIsolatedTrack is a new type (IIRC), so the checker is unaware of it and it probably picks  the reftobase parent as the suggested placement (RecoCandidate would be inappropriate)
- the CATopJetProperties is intentional : see https://github.com/cms-sw/cmssw/pull/7298 and https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1317/2/1/1.html

@smuzaffar we need an update of the dictionary checker

**Comment by smuzaffar** [comment]
this is done here #9434
